NUTOOL_PIN.g_cfg_chips = [
    { name: "NUC990DF63YC", pkg: "LQFP216" },
    { name: "NUC990DF63YF", pkg: "LQFP216" },
    { name: "NUC990DF73YC", pkg: "LQFP216" },
    { name: "NUC990DF73YF", pkg: "LQFP216" },
    { name: "NUC990DK63YC", pkg: "LQFP128" },
    { name: "NUC990DK63YF", pkg: "LQFP128" },
    { name: "NUC990DK73YC", pkg: "LQFP128" },
    { name: "NUC990DK73YF", pkg: "LQFP128" },
    { name: "NUC990DR63YC", pkg: "LQFP64" },
    { name: "NUC990DR63YF", pkg: "LQFP64" },
    { name: "NUC990DR73YC", pkg: "LQFP64" },
    { name: "NUC990DR73YF", pkg: "LQFP64" }
];

NUTOOL_PIN.g_cfg_pkgs = {
    "LQFP128 (14*14)": [
        'HSUSB0_ID ', 'PA.0', 'PA.1', 'PA.2', 'PA.3', 'PA.4', 'PA.5', 'PA.6', 'VDDIO0', 'VDD12',
        'MVDD', 'MVDD', 'VDD12', 'PA.7', 'PA.8', 'PA.9', 'PA.10', 'PA.11', 'PA.12', 'VDD33',
        'PG.9', 'PG.8', 'PG.7', 'PG.6', 'PG.5', 'PG.3', 'PG.1', 'PG.0', 'PB.0', 'PB.6',
        'PB.4', 'AVSS', 'AVDD33', 'PB.7', 'PB.5', 'PB.1', 'PB.3', 'PB.2', 'VBAT33', 'X32_IN',
        'X32_OUT', 'PB.8', 'VDD12', 'PC.0', 'PC.1', 'PC.2', 'PC.3', 'PC.4', 'PC.5', 'PC.6',
        'PC.7', 'PC.8', 'PC.9', 'PC.10', 'PC.11', 'PC.12', 'PC.13', 'PC.14', 'PC.15', 'VDD33',
        'PD.2', 'PD.3', 'PD.4', 'VSS', 'PD.5', 'PD.6', 'PD.7', 'PD.8', 'PD.9', 'PD.10',
        'PD.11', 'PD.12', 'PD.13', 'PD.14', 'PD.15', 'PG.11', 'PG.12', 'PG.13', 'PG.14', 'PG.15',
        'nRESET', 'VDD12', 'MVDD', 'MVDD', 'VDD33', 'PF.0', 'PF.1', 'PF.2', 'PF.3', 'PF.4',
        'PF.5', 'PF.6', 'PB.13', 'VDD12', 'VSS', 'PF.7', 'PF.8', 'PF.9', 'PF.10', 'PF.11',
        'PF.12', 'VDD33', 'XT_IN', 'XT_OUT', 'PE.0', 'PE.1', 'PE.2', 'PE.3', 'PE.4', 'PE.5',
        'PE.6', 'PE.7', 'PE.8', 'PE.9', 'PE.10', 'PE.11', 'PE.12', 'VDD12/VDD12_USB1', 'HSUSB1_D-', 'HSUSB1_D+',
        'VDD33_USB1', 'HSUSB1_REXT', 'VDD12_USB0', 'HSUSB0_D-', 'HSUSB0_D+', 'VDD33_USB0', 'HSUSB0_REXT', 'VSS'
    ],
    "LQFP216 (24*24)": [
        'VSS', 'HSUSB0_ID ', 'PA.0', 'PA.1', 'PA.2', 'PA.3', 'PA.4', 'PA.5', 'PA.6', 'VDDIO0',
        'VSS', 'VDD12', 'VSS', 'VDD12', 'VSS', 'MVDD', 'VSS', 'MVDD', 'VSS', 'MVDD',
        'VSS', 'MVDD', 'VSS', 'MVDD', 'VSS', 'VSS', 'VSS', 'VDD12', 'PA.7', 'PA.8',
        'PA.9', 'PA.10', 'PA.11', 'PA.12', 'PA.13', 'PA.14', 'PA.15', 'PG.10', 'VDD33', 'PG.9',
        'PG.8', 'PG.7', 'PG.6', 'PG.5', 'PG.4', 'PG.3', 'PG.2', 'PG.1', 'PG.0', 'VSS',
        'VSS', 'PB.0', 'PB.6', 'PB.4', 'AVSS', 'AVDD33', 'PB.7', 'PB.5', 'PB.1', 'PB.3',
        'PB.2', 'AVREF', 'AVDD33', 'VBAT33', 'NC', 'NC', 'X32_IN', 'X32_OUT', 'VSS', 'VSS',
        'PB.8', 'VSS', 'VSS', 'VDD12', 'PC.0', 'PC.1', 'PC.2', 'PC.3', 'PC.4', 'VSS',
        'PC.5', 'VSS', 'PC.6', 'PC.7', 'PC.8', 'VSS', 'PC.9', 'VSS', 'PC.10', 'PC.11',
        'PC.12', 'PC.13', 'PC.14', 'PC.15', 'VDD12', 'VSS', 'VSS', 'PH.0', 'VDD33', 'PH.1',
        'PH.2', 'PH.3', 'PH.4', 'VSS', 'PH.5', 'PH.6', 'PH.7', 'PH.8', 'PH.9', 'VSS',
        'PD.0', 'PD.1', 'PB.9', 'PB.10', 'PB.11', 'PB.12', 'PD.2', 'PD.3', 'PD.4', 'PD.5',
        'PD.6', 'PD.7', 'PD.8', 'PD.9', 'PD.10', 'PD.11', 'PD.12', 'VSS', 'PD.13', 'PD.14',
        'PD.15', 'PG.11', 'PG.12', 'PG.13', 'PG.14', 'PG.15', 'nRESET', 'VDD33', 'VSS', 'VSS',
        'VDD12', 'MVDD', 'VSS', 'MVDD', 'VSS', 'MVDD', 'VSS', 'MVDD', 'VSS', 'VSS',
        'VSS', 'VDD33', 'PF.0', 'PF.1', 'PF.2', 'PF.3', 'PF.4', 'PF.5', 'PF.6', 'PB.13',
        'VDD12', 'VDD12', 'VSS', 'VSS', 'PF.7', 'PF.8', 'PF.9', 'VDD12', 'PF.10', 'PF.11',
        'VSS', 'PF.12', 'VDD33', 'XT_IN', 'XT_OUT', 'VSS', 'PE.0', 'PE.1', 'PE.2', 'VDD12',
        'PE.3', 'PE.4', 'PE.5', 'PE.6', 'PE.7', 'VDD33', 'PE.8', 'PE.9', 'PE.10', 'PE.11',
        'PE.12', 'VSS', 'VDD12', 'VSS', 'VDD12_USB1', 'VDD12_USB1', 'VSS_USB1', 'NC', 'NC', 'VSS_USB1',
        'HSUSB1_D-', 'HSUSB1_D+', 'VDD33_USB1', 'VDD33_USB1', 'HSUSB1_REXT', 'VDD12_USB0', 'VDD12_USB0', 'VSS_USB0', 'NC', 'NC',
        'VSS_USB0', 'HSUSB0_D-', 'HSUSB0_D+', 'VDD33_USB0', 'VDD33_USB0', 'HSUSB0_REXT'
    ],
    "LQFP64 (10*10)": [
        'HSUSB0_ID ', 'PA.0', 'PA.1', 'PA.2', 'PA.3', 'PA.4', 'PA.5', 'PA.6', 'VDDIO0', 'VDD12',
        'MVDD', 'VDD12', 'VDD33', 'PG.1', 'PG.0', 'PB.6', 'PB.4', 'AVDD33', 'PC.3', 'PC.4',
        'PC.5', 'PC.6', 'PC.8', 'PC.9', 'PC.10', 'PC.11', 'PC.12', 'PC.13', 'PC.14', 'PC.15',
        'VDD12', 'VDD33', 'PD.2', 'PD.3', 'PD.4', 'PD.5', 'nRESET', 'VDD12', 'MVDD', 'VDD33',
        'PF.0', 'PF.1', 'PF.2', 'PF.3', 'PF.4', 'PF.5', 'PF.6', 'VDD12', 'PF.7', 'PF.8',
        'PF.9', 'PF.11', 'PF.12', 'VDD33', 'XT_IN', 'XT_OUT', 'PE.11', 'VDD12/VDD12_USB1', 'VDD33_USB1', 'VDD12_USB0',
        'HSUSB0_D-', 'HSUSB0_D+', 'VDD33_USB0', 'HSUSB0_REXT'
    ],
    "PAD#": [
        'VSS'
    ]
};

NUTOOL_PIN.g_cfg_gpios = [
    { f: ['PA.0:0', 'QSPI0_SS1:1', 'EBI_nWAIT:2', 'I2C0_SDA:3', 'UART1_RXD:4', 'INT0:5', 'CAN3_RXD:7'] },
    { f: ['PA.1:0', 'EBI_nCS2:1', 'EBI_MCLK:2', 'I2C0_SCL:3', 'UART1_TXD:4', 'INT1:5', 'CAN3_TXD:7', 'QSPI0_CLK:9'] },
    { f: ['PA.2:0', 'UART6_nCTS:1', 'I2S_LRCK:2', 'SC0_nCD:3', 'JTAG1_TDO:4', 'CANFD0_RXD:6', 'I2C0_SMBAL:7', 'SPI2_SS1:8', 'QSPI0_MOSI0:9'] },
    { f: ['PA.3:0', 'UART6_nRTS:1', 'I2S_BCLK:2', 'SC0_PWR:3', 'JTAG1_TCK:4', 'BPWM1_CH5:5', 'CANFD0_TXD:6', 'I2C0_SMBSUS:7', 'SPI2_SS0:8', 'QSPI0_MISO0:9'] },
    { f: ['PA.4:0', 'UART6_RXD:1', 'I2S_DI:2', 'SC0_DAT:3', 'JTAG1_TMS:4', 'BPWM1_CH4:5', 'CANFD1_RXD:6', 'I2C1_SMBAL:7', 'SPI2_MISO:8', 'QSPI0_MOSI1:9'] },
    { f: ['PA.5:0', 'UART6_TXD:1', 'I2S_DO:2', 'SC0_CLK:3', 'JTAG1_TDI:4', 'BPWM0_CH5:5', 'CANFD1_TXD:6', 'I2C1_SMBSUS:7', 'SPI2_MOSI:8', 'QSPI0_MISO1:9'] },
    { f: ['PA.6:0', 'EBI_nCS1:1', 'I2S_MCLK:2', 'SC0_RST:3', 'JTAG1_nTRST:4', 'BPWM0_CH4:5', 'SPI2_CLK:8', 'QSPI0_SS0:9'] },
    { f: ['PA.7:0', 'EBI_nWR:1', 'UART2_nCTS:2', 'TM3_EXT:3', 'BPWM1_CH5:5'] },
    { f: ['PA.8:0', 'EBI_nRD:1', 'UART2_nRTS:2', 'TM3:3', 'BPWM1_CH4:5'] },
    { f: ['PA.9:0', 'EBI_nCS0:1', 'UART2_RXD:2', 'TM2_EXT:3', 'BPWM0_CH5:5'] },
    { f: ['PA.10:0', 'EBI_ADR10:1', 'UART2_TXD:2', 'TM2:3', 'BPWM0_CH4:5'] },
    { f: ['PA.11:0', 'EBI_ADR9:1', 'UART8_RXD:2', 'TM4_EXT:3', 'CANFD2_RXD:4'] },
    { f: ['PA.12:0', 'EBI_ADR8:1', 'UART8_TXD:2', 'TM4:3', 'CANFD2_TXD:4'] },
    { f: ['PA.13:0', 'EBI_ADR13:1', 'I2C1_SDA:2', 'TM1_EXT:3', 'CAN1_RXD:5', 'UART7_TXD:6', 'BPWM0_CH3:7', 'INT0:8'] },
    { f: ['PA.14:0', 'EBI_ADR14:1', 'I2C1_SCL:2', 'TM1:3', 'CAN1_TXD:5', 'UART7_RXD:6', 'BPWM0_CH2:7', 'INT1:8'] },
    { f: ['PA.15:0', 'EBI_ADR19:1', 'I2C0_SDA:2', 'TM5_EXT:3', 'CAN2_RXD:5', 'SPI1_SS0:6', 'BPWM0_CH1:7', 'I2S_LRCK:8'] },

    { f: ['PB.0:0', 'EBI_ADR12:1', 'UART2_nCTS:2', 'I2C2_SCL:3', 'ADC0_CH0:8'] },
    { f: ['PB.1:0', 'EBI_ADR17:1', 'I2C3_SDA:2', 'I2S_MCLK:3', 'CAN2_RXD:4', 'TM0_EXT:5', 'SPI1_SS1:6', 'UART9_TXD:7', 'ADC0_CH1:8'] },
    { f: ['PB.2:0', 'EBI_ADR2:1', 'CANFD3_RXD:2', 'UART9_nRTS:7', 'ADC0_CH2:8'] },
    { f: ['PB.3:0', 'EBI_ADR18:1', 'I2C3_SCL:2', 'INT2:3', 'CAN2_TXD:4', 'TM0:5', 'SPI0_SS1:6', 'UART9_RXD:7', 'ADC0_CH3:8'] },
    { f: ['PB.4:0', 'EBI_ADR14:1', 'I2C1_SCL:2', 'I2S_BCLK:3', 'UART7_RXD:5', 'SPI1_CLK:6', 'ADC0_CH4:8'] },
    { f: ['PB.5:0', 'EBI_ADR16:1', 'I2C2_SCL:2', 'I2S_DO:3', 'UART7_nRTS:5', 'SPI1_MISO:6', 'ADC0_CH5:8'] },
    { f: ['PB.6:0', 'EBI_ADR13:1', 'I2C1_SDA:2', 'I2S_LRCK:3', 'UART7_TXD:5', 'SPI1_SS0:6', 'ADC0_CH6:8'] },
    { f: ['PB.7:0', 'EBI_ADR15:1', 'I2C2_SDA:2', 'I2S_DI:3', 'UART7_nCTS:5', 'SPI1_MOSI:6', 'ADC0_CH7:8'] },
    { f: ['PB.8:0', 'EBI_ADR11:1', 'I2C2_SCL:2', 'CAN2_RXD:3', 'UART8_TXD:4', 'UART9_nCTS:5', 'SD0_nCD:6', 'TM0_EXT:7'] },
    { f: ['PB.9:0', 'UART3_TXD:1', 'BPWM1_CH3:2', 'TM0:3', 'CANFD0_RXD:4', 'SPI1_SS0:5', 'SD1_DAT0:6', 'eMMC1_DAT0:6'] },
    { f: ['PB.10:0', 'UART3_RXD:1', 'BPWM1_CH2:2', 'TM0_EXT:3', 'CANFD0_TXD:4', 'SPI1_CLK:5', 'SD1_DAT1:6', 'eMMC1_DAT1:6'] },
    { f: ['PB.11:0', 'UART3_nRTS:1', 'BPWM1_CH1:2', 'TM2_EXT:3', 'CANFD1_RXD:4', 'SPI1_MOSI:5', 'SD1_DAT2:6', 'eMMC1_DAT2:6', 'I2C3_SMBAL:8'] },
    { f: ['PB.12:0', 'UART3_nCTS:1', 'BPWM1_CH0:2', 'TM2:3', 'CANFD1_TXD:4', 'SPI1_MISO:5', 'SD1_DAT3:6', 'eMMC1_DAT3:6', 'I2C3_SMBSUS:8'] },
    { f: ['PB.13:0', 'EMAC1_RMII_PPS:1', 'INT2:2', 'TM4:3', 'BPWM0_CH2:4', 'UART3_TXD:5', 'SPI2_SS1:7', 'EBI_AD0:8'] },
    { f: ['PB.14:0'] },
    { f: ['PB.15:0'] },

    { f: ['PC.0:0', 'EBI_AD0:1', 'I2C2_SDA:2', 'CAN2_TXD:3', 'UART8_RXD:4', 'SPI0_SS1:5', 'TM0:7', 'SPI3_SS0:8'] },
    { f: ['PC.1:0', 'EBI_AD1:1', 'NAND_nCS:3', 'UART7_TXD:4', 'UART3_nCTS:5', 'SPI3_CLK:8'] },
    { f: ['PC.2:0', 'EBI_AD2:1', 'NAND_nWP:3', 'UART7_RXD:4', 'UART3_nRTS:5', 'SPI3_MOSI:8'] },
    { f: ['PC.3:0', 'EBI_AD3:1', 'NAND_ALE:3', 'I2C1_SCL:4', 'UART3_TXD:5', 'CAN0_RXD:7', 'SPI3_MISO:8'] },
    { f: ['PC.4:0', 'EBI_AD4:1', 'NAND_CLE:3', 'I2C1_SDA:4', 'UART3_RXD:5', 'SPI0_MOSI:6', 'CAN0_TXD:7'] },
    { f: ['PC.5:0', 'EBI_AD5:1', 'NAND_nWE:3', 'SPI0_SS0:5', 'SD0_CMD:6', 'eMMC0_CMD:6', 'UART1_TXD:7', 'UART7_nCTS:8'] },
    { f: ['PC.6:0', 'EBI_AD6:1', 'NAND_nRE:3', 'SC1_RST:4', 'SPI0_CLK:5', 'SD0_CLK:6', 'eMMC0_CLK:6', 'UART1_RXD:7'] },
    { f: ['PC.7:0', 'EBI_AD7:1', 'CANFD3_TXD:2', 'NAND_RDY:3', 'SC1_CLK:4', 'SPI0_MOSI:5', 'SD0_DAT0:6', 'eMMC0_DAT0:6', 'UART1_nRTS:7'] },
    { f: ['PC.8:0', 'EBI_AD8:1', 'CANFD2_RXD:2', 'NAND_DATA0:3', 'SC1_DAT:4', 'SPI0_MISO:5', 'SD0_DAT1:6', 'eMMC0_DAT1:6', 'UART1_nCTS:7'] },
    { f: ['PC.9:0', 'EBI_AD9:1', 'CANFD2_TXD:2', 'NAND_DATA1:3', 'SC1_PWR:4', 'I2C0_SMBAL:5', 'SD0_DAT2:6', 'eMMC0_DAT2:6', 'UART4_TXD:7'] },
    { f: ['PC.10:0', 'EBI_AD10:1', 'CANFD3_RXD:2', 'NAND_DATA2:3', 'SC1_nCD:4', 'I2C0_SMBSUS:5', 'SD0_DAT3:6', 'eMMC0_DAT3:6', 'UART4_RXD:7', 'SPI3_SS0:8'] },
    { f: ['PC.11:0', 'EBI_AD11:1', 'CANFD3_TXD:2', 'NAND_DATA3:3', 'SC0_RST:4', 'I2C1_SMBAL:5', 'UART7_nRTS:7', 'SPI3_CLK:8'] },
    { f: ['PC.12:0', 'EBI_AD12:1', 'CANFD0_RXD:2', 'NAND_DATA4:3', 'SC0_CLK:4', 'SD0_nCD:6', 'UART8_TXD:7', 'SPI3_MOSI:8'] },
    { f: ['PC.13:0', 'EBI_AD13:1', 'CANFD0_TXD:2', 'NAND_DATA5:3', 'SC0_DAT:4', 'UART8_RXD:7', 'SPI3_MISO:8'] },
    { f: ['PC.14:0', 'EBI_AD14:1', 'CANFD1_RXD:2', 'NAND_DATA6:3', 'SC0_PWR:4', 'SPI0_MOSI:5', 'UART8_nRTS:7'] },
    { f: ['PC.15:0', 'EBI_AD15:1', 'CANFD1_TXD:2', 'NAND_DATA7:3', 'SC0_nCD:4', 'I2C1_SMBSUS:5', 'UART8_nCTS:7', 'SPI3_SS1:8'] },

    { f: ['PD.0:0', 'QSPI0_SS1:1', 'UART5_TXD:2', 'TM1:3', 'INT2:4', 'CANFD2_RXD:6', 'SPI2_SS0:7', 'I2C2_SMBAL:8'] },
    { f: ['PD.1:0', 'SPI0_SS1:1', 'UART5_RXD:2', 'TM1_EXT:3', 'INT3:4', 'CANFD2_TXD:6', 'I2C2_SMBSUS:8'] },
    { f: ['PD.2:0', 'QSPI0_SS0:1', 'UART3_TXD:2', 'TM4_EXT:3'] },
    { f: ['PD.3:0', 'QSPI0_CLK:1', 'UART3_RXD:2', 'TM4:3'] },
    { f: ['PD.4:0', 'QSPI0_MOSI0:1', 'UART3_nRTS:2', 'TM5_EXT:3', 'CANFD2_RXD:6'] },
    { f: ['PD.5:0', 'QSPI0_MISO0:1', 'UART3_nCTS:2', 'TM5:3', 'CANFD2_TXD:6'] },
    { f: ['PD.6:0', 'QSPI0_MOSI1:1', 'UART2_TXD:2', 'CAN0_RXD:4'] },
    { f: ['PD.7:0', 'QSPI0_MISO1:1', 'UART2_RXD:2', 'CAN0_TXD:4'] },
    { f: ['PD.8:0', 'SPI0_SS0:1', 'UART6_nCTS:2', 'I2C0_SMBAL:5', 'BPWM1_CH5:6'] },
    { f: ['PD.9:0', 'SPI0_CLK:1', 'UART6_nRTS:2', 'I2C0_SMBSUS:5', 'BPWM1_CH4:6'] },
    { f: ['PD.10:0', 'SPI0_MOSI:1', 'UART6_TXD:2', 'I2C1_SMBAL:5', 'BPWM0_CH5:6'] },
    { f: ['PD.11:0', 'SPI0_MISO:1', 'UART6_RXD:2', 'I2C1_SMBSUS:5', 'BPWM0_CH4:6'] },
    { f: ['PD.12:0', 'UART4_TXD:1', 'TM2:2', 'CAN2_RXD:4', 'I2C3_SMBAL:5', 'BPWM0_CH0:6', 'SPI2_SS1:7', 'EBI_AD1:8'] },
    { f: ['PD.13:0', 'UART4_RXD:1', 'TM2_EXT:2', 'CAN2_TXD:4', 'I2C3_SMBSUS:5', 'BPWM0_CH1:6', 'SPI2_CLK:7', 'EBI_AD2:8'] },
    { f: ['PD.14:0', 'UART4_nRTS:1', 'TM3:2', 'I2C3_SCL:3', 'CAN1_RXD:4', 'BPWM0_CH2:6', 'SPI2_MOSI:7', 'EBI_AD3:8'] },
    { f: ['PD.15:0', 'UART4_nCTS:1', 'TM3_EXT:2', 'I2C3_SDA:3', 'CAN1_TXD:4', 'BPWM0_CH3:6', 'SPI2_MISO:7', 'EBI_AD4:8'] },

    { f: ['PE.0:0', 'EMAC0_RMII_RXERR:1', 'CAN0_RXD:2', 'UART4_nCTS:5', 'SPI3_SS1:6', 'I2C2_SMBAL:7'] },
    { f: ['PE.1:0', 'EMAC0_RMII_CRSDV:1', 'CAN0_TXD:2', 'UART4_nRTS:5', 'SPI3_CLK:6', 'I2C2_SMBSUS:7'] },
    { f: ['PE.2:0', 'EMAC0_RMII_RXD1:1', 'CAN1_RXD:2', 'UART4_RXD:5', 'SPI3_MOSI:6', 'I2C1_SMBAL:7'] },
    { f: ['PE.3:0', 'EMAC0_RMII_RXD0:1', 'CAN1_TXD:2', 'UART4_TXD:5', 'SPI3_MISO:6', 'I2C1_SMBSUS:7'] },
    { f: ['PE.4:0', 'EMAC0_RMII_REFCLK:1', 'CAN2_RXD:2', 'UART9_nCTS:5', 'I2C3_SMBAL:7'] },
    { f: ['PE.5:0', 'EMAC0_RMII_TXEN:1', 'CAN2_TXD:2', 'UART9_nRTS:5', 'I2C3_SMBSUS:7'] },
    { f: ['PE.6:0', 'EMAC0_RMII_TXD1:1', 'CAN3_RXD:2', 'UART9_RXD:5', 'I2C2_SMBAL:7'] },
    { f: ['PE.7:0', 'EMAC0_RMII_TXD0:1', 'CAN3_TXD:2', 'UART9_TXD:5', 'I2C2_SMBSUS:7'] },
    { f: ['PE.8:0', 'EMAC0_RMII_MDIO:1', 'UART6_RXD:5', 'I2C0_SMBAL:7', 'SPI2_SS0:8'] },
    { f: ['PE.9:0', 'EMAC0_RMII_MDC:1', 'UART6_TXD:5', 'I2C0_SMBSUS:7', 'SPI2_CLK:8'] },
    { f: ['PE.10:0', 'USB_OVC:1', 'CAN3_RXD:2', 'UART9_RXD:3', 'BPWM1_CH2:4', 'INT2:5', 'I2C0_SDA:6', 'SPI2_MOSI:8'] },
    { f: ['PE.11:0', 'USB0_VBUSVLD:1'] },
    { f: ['PE.12:0', 'USBH_PWREN:1', 'CAN3_TXD:2', 'UART9_TXD:3', 'BPWM1_CH3:4', 'INT3:5', 'I2C0_SCL:6', 'SPI2_MISO:8'] },
    { f: ['PE.13:0'] },
    { f: ['PE.14:0'] },
    { f: ['PE.15:0'] },

    { f: ['PF.0:0', 'EMAC1_RMII_RXERR:1', 'SD1_CMD:2', 'eMMC1_CMD:2', 'SC1_RST:4', 'UART7_nCTS:5', 'SPI3_SS0:6', 'BPWM1_CH5:7', 'EBI_AD5:8'] },
    { f: ['PF.1:0', 'EMAC1_RMII_CRSDV:1', 'SD1_CLK:2', 'eMMC1_CLK:2', 'SC1_CLK:4', 'UART7_nRTS:5', 'SPI3_CLK:6', 'BPWM1_CH4:7', 'EBI_AD6:8'] },
    { f: ['PF.2:0', 'EMAC1_RMII_RXD1:1', 'SD1_DAT0:2', 'eMMC1_DAT0:2', 'SC1_DAT:4', 'UART7_RXD:5', 'SPI3_MOSI:6', 'BPWM0_CH5:7', 'EBI_AD7:8'] },
    { f: ['PF.3:0', 'EMAC1_RMII_RXD0:1', 'SD1_DAT1:2', 'eMMC1_DAT1:2', 'SC1_PWR:4', 'UART7_TXD:5', 'SPI3_MISO:6', 'BPWM0_CH4:7', 'EBI_AD8:8'] },
    { f: ['PF.4:0', 'EMAC1_RMII_REFCLK:1', 'SD1_DAT2:2', 'eMMC1_DAT2:2', 'SC1_nCD:4', 'UART3_nCTS:5', 'SPI2_SS0:7', 'EBI_AD9:8'] },
    { f: ['PF.5:0', 'EMAC1_RMII_TXEN:1', 'SD1_DAT3:2', 'eMMC1_DAT3:2', 'BPWM0_CH0:4', 'UART3_nRTS:5', 'SPI2_CLK:7', 'EBI_AD10:8'] },
    { f: ['PF.6:0', 'EMAC1_RMII_TXD1:1', 'SD1_nCD:2', 'TM4_EXT:3', 'BPWM0_CH1:4', 'UART3_RXD:5', 'SPI2_MOSI:7', 'EBI_AD11:8'] },
    { f: ['PF.7:0', 'EMAC1_RMII_TXD0:1', 'UART1_nCTS:2', 'TM5_EXT:3', 'BPWM0_CH2:4', 'UART3_TXD:5', 'SPI2_MISO:7', 'EBI_AD12:8'] },
    { f: ['PF.8:0', 'EMAC1_RMII_MDIO:1', 'UART1_nRTS:2', 'TM1:3', 'BPWM0_CH3:4', 'ICE_CLK:5', 'SPI3_SS1:6', 'EBI_AD13:8'] },
    { f: ['PF.9:0', 'EMAC1_RMII_MDC:1', 'UART1_RXD:2', 'TM1_EXT:3', 'BPWM1_CH0:4', 'ICE_DAT:5', 'SPI3_SS0:6', 'EBI_AD14:8'] },
    { f: ['PF.10:0', 'EMAC0_RMII_PPS:1', 'UART1_TXD:2', 'TM5:3', 'BPWM1_CH1:4', 'CANFD3_TXD:6', 'EBI_AD15:8'] },
    { f: ['PF.11:0', 'UART0_RXD:1'] },
    { f: ['PF.12:0', 'UART0_TXD:1'] },
    { f: ['PF.13:0'] },
    { f: ['PF.14:0'] },
    { f: ['PF.15:0'] },

    { f: ['PG.0:0', 'EBI_ADR0:1', 'UART2_RXD:2', 'CLK_OUT:3', 'BPWM0_CH0:6'] },
    { f: ['PG.1:0', 'EBI_ADR1:1', 'UART2_TXD:2', 'RTC_1Hz_OUT:3', 'BPWM0_CH1:6'] },
    { f: ['PG.2:0', 'EBI_ADR2:1', 'UART2_nCTS:2', 'CANFD3_TXD:4', 'BPWM0_CH2:6'] },
    { f: ['PG.3:0', 'EBI_ADR3:1', 'UART2_nRTS:2', 'UART5_nCTS:3', 'BPWM0_CH3:6'] },
    { f: ['PG.4:0', 'EBI_ADR18:1', 'UART5_nCTS:2', 'CANFD3_RXD:4'] },
    { f: ['PG.5:0', 'EBI_ADR12:1', 'UART5_nRTS:2'] },
    { f: ['PG.6:0', 'EBI_ADR4:1', 'UART5_RXD:2', 'CANFD1_TXD:4', 'BPWM1_CH0:6'] },
    { f: ['PG.7:0', 'EBI_ADR5:1', 'UART5_TXD:2', 'CANFD1_RXD:4', 'BPWM1_CH1:6'] },
    { f: ['PG.8:0', 'EBI_ADR6:1', 'UART8_nRTS:2', 'CANFD0_TXD:4', 'BPWM1_CH2:6'] },
    { f: ['PG.9:0', 'EBI_ADR7:1', 'UART8_nCTS:2', 'CANFD0_RXD:4', 'BPWM1_CH3:6'] },
    { f: ['PG.10:0', 'EBI_AD0:1', 'I2C0_SCL:2', 'TM5:3', 'CAN2_TXD:5', 'SPI1_CLK:6', 'BPWM0_CH0:7', 'I2S_BCLK:8'] },
    { f: ['PG.11:0', 'SPI1_SS0:2', 'TM1:3', 'CAN0_RXD:4', 'UART5_nCTS:5', 'BPWM1_CH0:6', 'JTAG0_TDO:7', 'I2C2_SMBAL:8'] },
    { f: ['PG.12:0', 'SPI1_CLK:2', 'TM1_EXT:3', 'CAN0_TXD:4', 'UART5_nRTS:5', 'BPWM1_CH1:6', 'JTAG0_TCK:7', 'I2C2_SMBSUS:8'] },
    { f: ['PG.13:0', 'SPI1_MOSI:2', 'CAN1_RXD:4', 'UART5_RXD:5', 'BPWM1_CH2:6', 'JTAG0_TMS:7', 'I2C3_SMBAL:8'] },
    { f: ['PG.14:0', 'SPI1_MISO:2', 'CAN1_TXD:4', 'UART5_TXD:5', 'BPWM1_CH3:6', 'JTAG0_TDI:7', 'I2C3_SMBSUS:8'] },
    { f: ['PG.15:0', 'SPI0_SS1:1', 'SPI1_SS1:2', 'INT3:4', 'SPI2_SS1:5', 'CANFD3_RXD:6', 'JTAG0_nTRST:7', 'SPI3_SS1:8'] },

    { f: ['PH.0:0', 'UART1_TXD:1', 'UART2_nCTS:2', 'INT0:4', 'SPI0_SS0:5', 'SD0_nCD:6'] },
    { f: ['PH.1:0', 'UART1_RXD:1', 'UART2_nRTS:2', 'TM3:3', 'SD0_DAT0:6', 'eMMC0_DAT0:6'] },
    { f: ['PH.2:0', 'UART1_nRTS:1', 'CAN3_RXD:2', 'TM3_EXT:3', 'SD0_DAT1:6', 'eMMC0_DAT1:6'] },
    { f: ['PH.3:0', 'UART1_nCTS:1', 'CAN3_TXD:2', 'I2C3_SDA:3', 'SD0_DAT2:6', 'eMMC0_DAT2:6'] },
    { f: ['PH.4:0', 'UART9_TXD:1', 'UART8_nCTS:2', 'I2C3_SCL:3', 'SD0_DAT3:6', 'eMMC0_DAT3:6'] },
    { f: ['PH.5:0', 'UART9_RXD:1', 'UART8_nRTS:2', 'INT1:4', 'SPI0_MISO:5', 'SD0_CMD:6', 'eMMC0_CMD:6'] },
    { f: ['PH.6:0', 'UART9_nRTS:1', 'SPI0_CLK:5', 'SD0_CLK:6', 'eMMC0_CLK:6'] },
    { f: ['PH.7:0', 'UART9_nCTS:1', 'I2C2_SDA:3', 'INT1:4', 'SPI1_SS1:5', 'SD1_nCD:6'] },
    { f: ['PH.8:0', 'UART2_TXD:1', 'UART6_nCTS:2', 'I2C2_SCL:3', 'INT0:4', 'SD1_CMD:6', 'eMMC1_CMD:6'] },
    { f: ['PH.9:0', 'UART2_RXD:1', 'UART6_nRTS:2', 'SD1_CLK:6', 'eMMC1_CLK:6'] },
    { f: ['PH.10:0'] },
    { f: ['PH.11:0'] },
    { f: ['PH.12:0'] },
    { f: ['PH.13:0'] },
    { f: ['PH.14:0'] },
    { f: ['PH.15:0'] }
];

NUTOOL_PIN.g_cfg_gpiosDefines = [
];

NUTOOL_PIN.g_cfg_gpiosDescriptions = [
    'ADC0_CH0:ADC0 channel 0 analog input.',
    'ADC0_CH1:ADC0 channel 1 analog input.',
    'ADC0_CH2:ADC0 channel 2 analog input.',
    'ADC0_CH3:ADC0 channel 3 analog input.',
    'ADC0_CH4:ADC0 channel 4 analog input.',
    'ADC0_CH5:ADC0 channel 5 analog input.',
    'ADC0_CH6:ADC0 channel 6 analog input.',
    'ADC0_CH7:ADC0 channel 7 analog input.',
    'BPWM0_CH0:BPWM0 channel 0 output/capture input.',
    'BPWM0_CH1:BPWM0 channel 1 output/capture input.',
    'BPWM0_CH2:BPWM0 channel 2 output/capture input.',
    'BPWM0_CH3:BPWM0 channel 3 output/capture input.',
    'BPWM0_CH4:BPWM0 channel 4 output/capture input.',
    'BPWM0_CH5:BPWM0 channel 5 output/capture input.',
    'BPWM1_CH0:BPWM1 channel 0 output/capture input.',
    'BPWM1_CH1:BPWM1 channel 1 output/capture input.',
    'BPWM1_CH2:BPWM1 channel 2 output/capture input.',
    'BPWM1_CH3:BPWM1 channel 3 output/capture input.',
    'BPWM1_CH4:BPWM1 channel 4 output/capture input.',
    'BPWM1_CH5:BPWM1 channel 5 output/capture input.',
    'CAN0_RXD:CAN0 bus receiver input.',
    'CAN0_TXD:CAN0 bus transmitter output.',
    'CAN1_RXD:CAN1 bus receiver input.',
    'CAN1_TXD:CAN1 bus transmitter output.',
    'CAN2_RXD:CAN2 bus receiver input.',
    'CAN2_TXD:CAN2 bus transmitter output.',
    'CAN3_RXD:CAN3 bus receiver input.',
    'CAN3_TXD:CAN3 bus transmitter output.',
    'CANFD0_RXD:CANFD0 bus receiver input.',
    'CANFD0_TXD:CANFD0 bus transmitter output.',
    'CANFD1_RXD:CANFD1 bus receiver input.',
    'CANFD1_TXD:CANFD1 bus transmitter output.',
    'CANFD2_RXD:CANFD2 bus receiver input.',
    'CANFD2_TXD:CANFD2 bus transmitter output.',
    'CANFD3_RXD:CANFD3 bus receiver input.',
    'CANFD3_TXD:CANFD3 bus transmitter output.',
    'CLK_OUT:Internal clock selection output pin.',
    'EBI_AD0:EBI address/data bus bit 0.',
    'EBI_AD1:EBI address/data bus bit 1.',
    'EBI_AD10:EBI address/data bus bit 10.',
    'EBI_AD11:EBI address/data bus bit 11.',
    'EBI_AD12:EBI address/data bus bit 12.',
    'EBI_AD13:EBI address/data bus bit 13.',
    'EBI_AD14:EBI address/data bus bit 14.',
    'EBI_AD15:EBI address/data bus bit 15.',
    'EBI_AD2:EBI address/data bus bit 2.',
    'EBI_AD3:EBI address/data bus bit 3.',
    'EBI_AD4:EBI address/data bus bit 4.',
    'EBI_AD5:EBI address/data bus bit 5.',
    'EBI_AD6:EBI address/data bus bit 6.',
    'EBI_AD7:EBI address/data bus bit 7.',
    'EBI_AD8:EBI address/data bus bit 8.',
    'EBI_AD9:EBI address/data bus bit 9.',
    'EBI_ADR0:EBI address bus bit 0.',
    'EBI_ADR1:EBI address bus bit 1.',
    'EBI_ADR10:EBI address bus bit 10.',
    'EBI_ADR11:EBI address bus bit 11.',
    'EBI_ADR12:EBI address bus bit 12.',
    'EBI_ADR13:EBI address bus bit 13.',
    'EBI_ADR14:EBI address bus bit 14.',
    'EBI_ADR15:EBI address bus bit 15.',
    'EBI_ADR16:EBI address bus bit 16.',
    'EBI_ADR17:EBI address bus bit 17.',
    'EBI_ADR18:EBI address bus bit 18.',
    'EBI_ADR19:EBI address bus bit 19.',
    'EBI_ADR2:EBI address bus bit 2.',
    'EBI_ADR3:EBI address bus bit 3.',
    'EBI_ADR4:EBI address bus bit 4.',
    'EBI_ADR5:EBI address bus bit 5.',
    'EBI_ADR6:EBI address bus bit 6.',
    'EBI_ADR7:EBI address bus bit 7.',
    'EBI_ADR8:EBI address bus bit 8.',
    'EBI_ADR9:EBI address bus bit 9.',
    'EBI_MCLK:EBI external clock output pin.',
    'EBI_nCS0:EBI chip select 0 output pin.',
    'EBI_nCS1:EBI chip select 1 output pin.',
    'EBI_nCS2:EBI chip select 2 output pin.',
    'EBI_nRD:EBI read enable output pin.',
    'EBI_nWAIT:EBI external I/O wait control input pin.',
    'EBI_nWR:EBI write enable output pin.',
    'EMAC0_RMII_CRSDV:EMAC0 RMII Carrier Sense/Receive Data input pin.',
    'EMAC0_RMII_MDC:EMAC0 RMII PHY Management Clock output pin.',
    'EMAC0_RMII_MDIO:EMAC0 RMII PHY Management Data pin.',
    'EMAC0_RMII_PPS:EMAC0_RMII Pulse Per Second output pin.',
    'EMAC0_RMII_REFCLK:EMAC0 RMII Reference Clock input pin.',
    'EMAC0_RMII_RXD0:EMAC0 RMII Receive Data bus bit 0.',
    'EMAC0_RMII_RXD1:EMAC0 RMII Receive Data bus bit 1.',
    'EMAC0_RMII_RXERR:EMAC0 RMII Receive Data Error input pin.',
    'EMAC0_RMII_TXD0:EMAC0 RMII Transmit Data bus bit 0.',
    'EMAC0_RMII_TXD1:EMAC0 RMII Transmit Data bus bit 1.',
    'EMAC0_RMII_TXEN:EMAC0 RMII Transmit Enable output pin.',
    'EMAC1_RMII_CRSDV:EMAC1 RMII Carrier Sense/Receive Data input pin.',
    'EMAC1_RMII_MDC:EMAC1 RMII PHY Management Clock output pin.',
    'EMAC1_RMII_MDIO:EMAC1 RMII PHY Management Data pin.',
    'EMAC1_RMII_PPS:EMAC1_RMII Pulse Per Second output pin.',
    'EMAC1_RMII_REFCLK:EMAC1 RMII Reference Clock input pin.',
    'EMAC1_RMII_RXD0:EMAC1 RMII Receive Data bus bit 0.',
    'EMAC1_RMII_RXD1:EMAC1 RMII Receive Data bus bit 1.',
    'EMAC1_RMII_RXERR:EMAC1 RMII Receive Data Error input pin.',
    'EMAC1_RMII_TXD0:EMAC1 RMII Transmit Data bus bit 0.',
    'EMAC1_RMII_TXD1:EMAC1 RMII Transmit Data bus bit 1.',
    'EMAC1_RMII_TXEN:EMAC1 RMII Transmit Enable output pin.',
    'I2C0_SCL:I2C0 clock pin.',
    'I2C0_SDA:I2C0 data input/output pin.',
    'I2C0_SMBAL:I2C0 SMBus SMBALTER pin.',
    'I2C0_SMBSUS:I2C0 SMBus SMBSUS pin. (PMBus CONTROL pin)',
    'I2C1_SCL:I2C1 clock pin.',
    'I2C1_SDA:I2C1 data input/output pin.',
    'I2C1_SMBAL:I2C1 SMBus SMBALTER pin.',
    'I2C1_SMBSUS:I2C1 SMBus SMBSUS pin. (PMBus CONTROL pin)',
    'I2C2_SCL:I2C2 clock pin.',
    'I2C2_SDA:I2C2 data input/output pin.',
    'I2C2_SMBAL:I2C2 SMBus SMBALTER pin.',
    'I2C2_SMBSUS:I2C2 SMBus SMBSUS pin. (PMBus CONTROL pin)',
    'I2C3_SCL:I2C3 clock pin.',
    'I2C3_SDA:I2C3 data input/output pin.',
    'I2C3_SMBAL:I2C3 SMBus SMBALTER pin.',
    'I2C3_SMBSUS:I2C3 SMBus SMBSUS pin. (PMBus CONTROL pin)',
    'I2S_BCLK:I2S bit clock output pin.',
    'I2S_DI:I2S data input pin.',
    'I2S_DO:I2S data output pin.',
    'I2S_LRCK:I2S left right channel clock output pin.',
    'I2S_MCLK:I2S master clock output pin.',
    'ICE_CLK:',
    'ICE_DAT:',
    'INT0:External interrupt 0 input pin.',
    'INT1:External interrupt 1 input pin.',
    'INT2:External interrupt 2 input pin.',
    'INT3:External interrupt 3 input pin.',
    'JTAG0_TCK:JTAG0 clock input pin.',
    'JTAG0_TDI:JTAG0 data input pin.',
    'JTAG0_TDO:JTAG0 data output pin.',
    'JTAG0_TMS:JTAG0 test mode selection input pin.',
    'JTAG0_nTRST:JTAG0 reset input pin.',
    'JTAG1_TCK:JTAG1 clock input pin.',
    'JTAG1_TDI:JTAG1 data input pin.',
    'JTAG1_TDO:JTAG1 data output pin.',
    'JTAG1_TMS:JTAG1 test mode selection input pin.',
    'JTAG1_nTRST:JTAG1 reset input pin.',
    'NAND_ALE:NAND Flash address latch enable output pin.',
    'NAND_CLE:NAND Flash command latch enable output pin.',
    'NAND_DATA0:NAND Flash date bus bit 0.',
    'NAND_DATA1:NAND Flash date bus bit 1.',
    'NAND_DATA2:NAND Flash date bus bit 2.',
    'NAND_DATA3:NAND Flash date bus bit 3.',
    'NAND_DATA4:NAND Flash date bus bit 4.',
    'NAND_DATA5:NAND Flash date bus bit 5.',
    'NAND_DATA6:NAND Flash date bus bit 6.',
    'NAND_DATA7:NAND Flash date bus bit 7.',
    'NAND_RDY:NAND Flash ready/busy input pin.',
    'NAND_nCS:NAND Flash chip select pin.',
    'NAND_nRE:NAND Flash read enable output pin.',
    'NAND_nWE:NAND Flash write enable output pin.',
    'NAND_nWP:NAND Flash write protect input pin.',
    'PA.0:General purpose digital I/O pin.',
    'PA.1:General purpose digital I/O pin.',
    'PA.10:General purpose digital I/O pin.',
    'PA.11:General purpose digital I/O pin.',
    'PA.12:General purpose digital I/O pin.',
    'PA.13:General purpose digital I/O pin.',
    'PA.14:General purpose digital I/O pin.',
    'PA.15:General purpose digital I/O pin.',
    'PA.2:General purpose digital I/O pin.',
    'PA.3:General purpose digital I/O pin.',
    'PA.4:General purpose digital I/O pin.',
    'PA.5:General purpose digital I/O pin.',
    'PA.6:General purpose digital I/O pin.',
    'PA.7:General purpose digital I/O pin.',
    'PA.8:General purpose digital I/O pin.',
    'PA.9:General purpose digital I/O pin.',
    'PB.0:General purpose digital I/O pin.',
    'PB.1:General purpose digital I/O pin.',
    'PB.10:General purpose digital I/O pin.',
    'PB.11:General purpose digital I/O pin.',
    'PB.12:General purpose digital I/O pin.',
    'PB.13:General purpose digital I/O pin.',
    'PB.14:General purpose digital I/O pin.',
    'PB.15:General purpose digital I/O pin.',
    'PB.2:General purpose digital I/O pin.',
    'PB.3:General purpose digital I/O pin.',
    'PB.4:General purpose digital I/O pin.',
    'PB.5:General purpose digital I/O pin.',
    'PB.6:General purpose digital I/O pin.',
    'PB.7:General purpose digital I/O pin.',
    'PB.8:General purpose digital I/O pin.',
    'PB.9:General purpose digital I/O pin.',
    'PC.0:General purpose digital I/O pin.',
    'PC.1:General purpose digital I/O pin.',
    'PC.10:General purpose digital I/O pin.',
    'PC.11:General purpose digital I/O pin.',
    'PC.12:General purpose digital I/O pin.',
    'PC.13:General purpose digital I/O pin.',
    'PC.14:General purpose digital I/O pin.',
    'PC.15:General purpose digital I/O pin.',
    'PC.2:General purpose digital I/O pin.',
    'PC.3:General purpose digital I/O pin.',
    'PC.4:General purpose digital I/O pin.',
    'PC.5:General purpose digital I/O pin.',
    'PC.6:General purpose digital I/O pin.',
    'PC.7:General purpose digital I/O pin.',
    'PC.8:General purpose digital I/O pin.',
    'PC.9:General purpose digital I/O pin.',
    'PD.0:General purpose digital I/O pin.',
    'PD.1:General purpose digital I/O pin.',
    'PD.10:General purpose digital I/O pin.',
    'PD.11:General purpose digital I/O pin.',
    'PD.12:General purpose digital I/O pin.',
    'PD.13:General purpose digital I/O pin.',
    'PD.14:General purpose digital I/O pin.',
    'PD.15:General purpose digital I/O pin.',
    'PD.2:General purpose digital I/O pin.',
    'PD.3:General purpose digital I/O pin.',
    'PD.4:General purpose digital I/O pin.',
    'PD.5:General purpose digital I/O pin.',
    'PD.6:General purpose digital I/O pin.',
    'PD.7:General purpose digital I/O pin.',
    'PD.8:General purpose digital I/O pin.',
    'PD.9:General purpose digital I/O pin.',
    'PE.0:General purpose digital I/O pin.',
    'PE.1:General purpose digital I/O pin.',
    'PE.10:General purpose digital I/O pin.',
    'PE.11:General purpose digital I/O pin.',
    'PE.12:General purpose digital I/O pin.',
    'PE.13:General purpose digital I/O pin.',
    'PE.14:General purpose digital I/O pin.',
    'PE.15:General purpose digital I/O pin.',
    'PE.2:General purpose digital I/O pin.',
    'PE.3:General purpose digital I/O pin.',
    'PE.4:General purpose digital I/O pin.',
    'PE.5:General purpose digital I/O pin.',
    'PE.6:General purpose digital I/O pin.',
    'PE.7:General purpose digital I/O pin.',
    'PE.8:General purpose digital I/O pin.',
    'PE.9:General purpose digital I/O pin.',
    'PF.0:General purpose digital I/O pin.',
    'PF.1:General purpose digital I/O pin.',
    'PF.10:General purpose digital I/O pin.',
    'PF.11:General purpose digital I/O pin.',
    'PF.12:General purpose digital I/O pin.',
    'PF.13:General purpose digital I/O pin.',
    'PF.14:General purpose digital I/O pin.',
    'PF.15:General purpose digital I/O pin.',
    'PF.2:General purpose digital I/O pin.',
    'PF.3:General purpose digital I/O pin.',
    'PF.4:General purpose digital I/O pin.',
    'PF.5:General purpose digital I/O pin.',
    'PF.6:General purpose digital I/O pin.',
    'PF.7:General purpose digital I/O pin.',
    'PF.8:General purpose digital I/O pin.',
    'PF.9:General purpose digital I/O pin.',
    'PG.0:General purpose digital I/O pin.',
    'PG.1:General purpose digital I/O pin.',
    'PG.10:General purpose digital I/O pin.',
    'PG.11:General purpose digital I/O pin.',
    'PG.12:General purpose digital I/O pin.',
    'PG.13:General purpose digital I/O pin.',
    'PG.14:General purpose digital I/O pin.',
    'PG.15:General purpose digital I/O pin.',
    'PG.2:General purpose digital I/O pin.',
    'PG.3:General purpose digital I/O pin.',
    'PG.4:General purpose digital I/O pin.',
    'PG.5:General purpose digital I/O pin.',
    'PG.6:General purpose digital I/O pin.',
    'PG.7:General purpose digital I/O pin.',
    'PG.8:General purpose digital I/O pin.',
    'PG.9:General purpose digital I/O pin.',
    'PH.0:General purpose digital I/O pin.',
    'PH.1:General purpose digital I/O pin.',
    'PH.10:General purpose digital I/O pin.',
    'PH.11:General purpose digital I/O pin.',
    'PH.12:General purpose digital I/O pin.',
    'PH.13:General purpose digital I/O pin.',
    'PH.14:General purpose digital I/O pin.',
    'PH.15:General purpose digital I/O pin.',
    'PH.2:General purpose digital I/O pin.',
    'PH.3:General purpose digital I/O pin.',
    'PH.4:General purpose digital I/O pin.',
    'PH.5:General purpose digital I/O pin.',
    'PH.6:General purpose digital I/O pin.',
    'PH.7:General purpose digital I/O pin.',
    'PH.8:General purpose digital I/O pin.',
    'PH.9:General purpose digital I/O pin.',
    'QSPI0_CLK:Quad SPI0 serial clock pin.',
    'QSPI0_MISO0:Quad SPI0 MISO0 (Master In, Slave Out) pin.',
    'QSPI0_MISO1:Quad SPI0 MISO1 (Master In, Slave Out) pin.',
    'QSPI0_MOSI0:Quad SPI0 MOSI0 (Master Out, Slave In) pin.',
    'QSPI0_MOSI1:Quad SPI0 MOSI1 (Master Out, Slave In) pin.',
    'QSPI0_SS0:Quad SPI0 slave select 0 pin.',
    'QSPI0_SS1:Quad SPI0 slave select 1 pin.',
    'RTC_1Hz_OUT:RTC 1Hz output pin.',
    'SC0_CLK:Smart Card 0 clock pin.',
    'SC0_DAT:Smart Card 0 data pin.',
    'SC0_PWR:Smart Card 0 power pin.',
    'SC0_RST:Smart Card 0 reset pin.',
    'SC0_nCD:Smart Card 0 card detect pin.',
    'SC1_CLK:Smart Card 1 clock pin.',
    'SC1_DAT:Smart Card 1 data pin.',
    'SC1_PWR:Smart Card 1 power pin.',
    'SC1_RST:Smart Card 1 reset pin.',
    'SC1_nCD:Smart Card 1 card detect pin.',
    'SD0_CLK:SD/SDIO0 clock output pin.',
    'SD0_CMD:SD/SDIO0 command/response pin.',
    'SD0_DAT0:SD/SDIO0 data line bit 0.',
    'SD0_DAT1:SD/SDIO0 data line bit 1.',
    'SD0_DAT2:SD/SDIO0 data line bit 2.',
    'SD0_DAT3:SD/SDIO0 data line bit 3.',
    'SD0_nCD:SD/SDIO0 card detect input pin.',
    'SD1_CLK:SD/SDIO1 clock output pin.',
    'SD1_CMD:SD/SDIO1 command/response pin.',
    'SD1_DAT0:SD/SDIO1 data line bit 0.',
    'SD1_DAT1:SD/SDIO1 data line bit 1.',
    'SD1_DAT2:SD/SDIO1 data line bit 2.',
    'SD1_DAT3:SD/SDIO1 data line bit 3.',
    'SD1_nCD:SD/SDIO1 card detect input pin.',
    'SPI0_CLK:SPI0 serial clock pin.',
    'SPI0_MISO:SPI0 MISO (Master In, Slave Out) pin.',
    'SPI0_MOSI:SPI0 MOSI (Master Out, Slave In) pin.',
    'SPI0_SS0:SPI0 slave select 0 pin.',
    'SPI0_SS1:SPI0 slave select 1 pin.',
    'SPI1_CLK:SPI1 serial clock pin.',
    'SPI1_MISO:SPI1 MISO (Master In, Slave Out) pin.',
    'SPI1_MOSI:SPI1 MOSI (Master Out, Slave In) pin.',
    'SPI1_SS0:SPI1 slave select 0 pin.',
    'SPI1_SS1:SPI1 slave select 1 pin.',
    'SPI2_CLK:SPI2 serial clock pin.',
    'SPI2_MISO:SPI2 MISO (Master In, Slave Out) pin.',
    'SPI2_MOSI:SPI2 MOSI (Master Out, Slave In) pin.',
    'SPI2_SS0:SPI2 slave select 0 pin.',
    'SPI2_SS1:SPI2 slave select 1 pin.',
    'SPI3_CLK:SPI3 serial clock pin.',
    'SPI3_MISO:SPI3 MISO (Master In, Slave Out) pin.',
    'SPI3_MOSI:SPI3 MOSI (Master Out, Slave In) pin.',
    'SPI3_SS0:SPI3 slave select 0 pin.',
    'SPI3_SS1:SPI3 slave select 1 pin.',
    'TM0:Timer0 event counter input/toggle output pin.',
    'TM0_EXT:Timer0 external capture input/toggle output pin.',
    'TM1:Timer1 event counter input/toggle output pin.',
    'TM1_EXT:Timer1 external capture input/toggle output pin.',
    'TM2:Timer2 event counter input/toggle output pin.',
    'TM2_EXT:Timer2 external capture input/toggle output pin.',
    'TM3:Timer3 event counter input/toggle output pin.',
    'TM3_EXT:Timer3 external capture input/toggle output pin.',
    'TM4:Timer4 event counter input/toggle output pin.',
    'TM4_EXT:Timer4 external capture input/toggle output pin.',
    'TM5:Timer5 event counter input/toggle output pin.',
    'TM5_EXT:Timer5 external capture input/toggle output pin.',
    'UART0_RXD:UART0 data receiver input pin.',
    'UART0_TXD:UART0 data transmitter output pin.',
    'UART1_RXD:UART1 data receiver input pin.',
    'UART1_TXD:UART1 data transmitter output pin.',
    'UART1_nCTS:UART1 clear to Send input pin.',
    'UART1_nRTS:UART1 request to Send output pin.',
    'UART2_RXD:UART2 data receiver input pin.',
    'UART2_TXD:UART2 data transmitter output pin.',
    'UART2_nCTS:UART2 clear to Send input pin.',
    'UART2_nRTS:UART2 request to Send output pin.',
    'UART3_RXD:UART3 data receiver input pin.',
    'UART3_TXD:UART3 data transmitter output pin.',
    'UART3_nCTS:UART3 clear to Send input pin.',
    'UART3_nRTS:UART3 request to Send output pin.',
    'UART4_RXD:UART4 data receiver input pin.',
    'UART4_TXD:UART4 data transmitter output pin.',
    'UART4_nCTS:UART4 clear to Send input pin.',
    'UART4_nRTS:UART4 request to Send output pin.',
    'UART5_RXD:UART5 data receiver input pin.',
    'UART5_TXD:UART5 data transmitter output pin.',
    'UART5_nCTS:UART5 clear to Send input pin.',
    'UART5_nRTS:UART5 request to Send output pin.',
    'UART6_RXD:UART6 data receiver input pin.',
    'UART6_TXD:UART6 data transmitter output pin.',
    'UART6_nCTS:UART6 clear to Send input pin.',
    'UART6_nRTS:UART6 request to Send output pin.',
    'UART7_RXD:UART7 data receiver input pin.',
    'UART7_TXD:UART7 data transmitter output pin.',
    'UART7_nCTS:UART7 clear to Send input pin.',
    'UART7_nRTS:UART7 request to Send output pin.',
    'UART8_RXD:UART8 data receiver input pin.',
    'UART8_TXD:UART8 data transmitter output pin.',
    'UART8_nCTS:UART8 clear to Send input pin.',
    'UART8_nRTS:UART8 request to Send output pin.',
    'UART9_RXD:UART9 data receiver input pin.',
    'UART9_TXD:UART9 data transmitter output pin.',
    'UART9_nCTS:UART9 clear to Send input pin.',
    'UART9_nRTS:UART9 request to Send output pin.',
    'USB0_VBUSVLD:HSUSB0 external VBUS status pin.',
    'USBH_PWREN:HSUSB host external VBUS regulator enable pin.',
    'USB_OVC:HSUSB host bus power overcurrent detector pin.',
    'eMMC0_CLK:eMMC0 clock output pin.',
    'eMMC0_CMD:eMMC0 command/response pin.',
    'eMMC0_DAT0:eMMC0 data line bit 0.',
    'eMMC0_DAT1:eMMC0 data line bit 1.',
    'eMMC0_DAT2:eMMC0 data line bit 2.',
    'eMMC0_DAT3:eMMC0 data line bit 3.',
    'eMMC1_CLK:eMMC1 clock output pin.',
    'eMMC1_CMD:eMMC1 command/response pin.',
    'eMMC1_DAT0:eMMC1 data line bit 0.',
    'eMMC1_DAT1:eMMC1 data line bit 1.',
    'eMMC1_DAT2:eMMC1 data line bit 2.',
    'eMMC1_DAT3:eMMC1 data line bit 3.'
];

NUTOOL_PIN.g_cfg_wppin = {
    "LQFP128 (14*14)": [
        
    ],
    "LQFP216 (24*24)": [
        
    ],
    "LQFP64 (10*10)": [
        
    ],
    "PAD#": [
        
    ],
};

NUTOOL_PIN.g_cfg_wppin_comment = {
};

NUTOOL_PIN.g_cfg_unusedGPIO = {
    'NUC990DF63YC': {
        'ALL': ['ICE', 'CANFD0', 'CANFD1', 'CANFD2', 'CANFD3']
    },
    'NUC990DF63YF': {
        'ALL': ['ICE']
    },
    'NUC990DF73YC': {
        'ALL': ['ICE', 'CANFD0', 'CANFD1', 'CANFD2', 'CANFD3']
    },
    'NUC990DF73YF': {
        'ALL': ['ICE']
    },
    'NUC990DK63YC': {
        'ALL': ['ICE', 'CANFD0', 'CANFD1', 'CANFD2', 'CANFD3']
    },
    'NUC990DK63YF': {
        'ALL': ['ICE']
    },
    'NUC990DK73YC': {
        'ALL': ['ICE', 'CANFD0', 'CANFD1', 'CANFD2', 'CANFD3']
    },
    'NUC990DK73YF': {
        'ALL': ['ICE']
    },
    'NUC990DR63YC': {
        'ALL': ['ICE', 'NAND', 'SD0', 'EMAC0', 'SPI1', 'I2C2', 'I2C3', 'CAN1', 'CAN2', 'CANFD0', 'CANFD1', 'CANFD2', 'CANFD3', 'UART5', 'UART9', 'EBI']
    },
    'NUC990DR63YF': {
        'ALL': ['ICE', 'NAND', 'SD0', 'EMAC0', 'SPI1', 'I2C2', 'I2C3', 'CAN1', 'CAN2', 'UART5', 'UART9', 'EBI']
    },
    'NUC990DR73YC': {
        'ALL': ['ICE', 'NAND', 'SD0', 'EMAC0', 'SPI1', 'I2C2', 'I2C3', 'CAN1', 'CAN2', 'CANFD0', 'CANFD1', 'CANFD2', 'CANFD3', 'UART5', 'UART9', 'EBI']
    },
    'NUC990DR73YF': {
        'ALL': ['ICE', 'NAND', 'SD0', 'EMAC0', 'SPI1', 'I2C2', 'I2C3', 'CAN1', 'CAN2', 'UART5', 'UART9', 'EBI']
    }
};

NUTOOL_PIN.g_cfg_OrCAD = {
    "LQFP128 (14*14)": [
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', ''
    ],
    "LQFP216 (24*24)": [
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', ''
    ],
    "LQFP64 (10*10)": [
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''
    ],
    "PAD#": [
        ''
    ]
};

NUTOOL_PIN.g_cfg_regDescriptions = {};

NUTOOL_PIN.g_cfg_gpioMatrix = [];

NUTOOL_PIN.g_cfg_shareBits = [];

NUTOOL_PIN.g_cfg_addGPIO = {};

NUTOOL_PIN.decidepackageNumber = function (given_partNumber_package) {
    NUTOOL_PIN.g_packageNumber = NUTOOL_PIN.getPackageNumber(given_partNumber_package);
    let partNumber = NUTOOL_PIN.getPartNumber(given_partNumber_package);
    switch (partNumber) {
        case "NUC990DF63YC":
            NUTOOL_PIN.g_packageNumberIndex = "LQFP216 (24*24)";
            break;
        case "NUC990DF63YF":
            NUTOOL_PIN.g_packageNumberIndex = "LQFP216 (24*24)";
            break;
        case "NUC990DF73YC":
            NUTOOL_PIN.g_packageNumberIndex = "LQFP216 (24*24)";
            break;
        case "NUC990DF73YF":
            NUTOOL_PIN.g_packageNumberIndex = "LQFP216 (24*24)";
            break;
        case "NUC990DK63YC":
            NUTOOL_PIN.g_packageNumberIndex = "LQFP128 (14*14)";
            break;
        case "NUC990DK63YF":
            NUTOOL_PIN.g_packageNumberIndex = "LQFP128 (14*14)";
            break;
        case "NUC990DK73YC":
            NUTOOL_PIN.g_packageNumberIndex = "LQFP128 (14*14)";
            break;
        case "NUC990DK73YF":
            NUTOOL_PIN.g_packageNumberIndex = "LQFP128 (14*14)";
            break;
        case "NUC990DR63YC":
            NUTOOL_PIN.g_packageNumberIndex = "LQFP64 (10*10)";
            break;
        case "NUC990DR63YF":
            NUTOOL_PIN.g_packageNumberIndex = "LQFP64 (10*10)";
            break;
        case "NUC990DR73YC":
            NUTOOL_PIN.g_packageNumberIndex = "LQFP64 (10*10)";
            break;
        case "NUC990DR73YF":
            NUTOOL_PIN.g_packageNumberIndex = "LQFP64 (10*10)";
            break;
        default:
            NUTOOL_PIN.g_packageNumberIndex = NUTOOL_PIN.g_packageNumber;
            break;
    };
};