// chip content
NUTOOL_PIN.g_cfg_chips = [
    { name: "N9H20K11N", pkg: "LQFP128" },
    { name: "N9H20K31N", pkg: "LQFP128" },
    { name: "N9H20K51N", pkg: "LQFP128" },
    { name: "N9H20R11N", pkg: "TQFP64" }
];

NUTOOL_PIN.g_cfg_pkgs = {
    "LQFP128": [
        'GPB[2]', 'GPB[1]', 'GPB[0]', 'ISDA', 'ISCK', 'SPI0_CLK', 'SPI0_CS0_', 'SPI0_DI', 'SPI0_DO', 'SD0_DAT[2]', 
        'SD0_DAT[3]', 'SD0_CMD', 'SD0_CLK', 'SD0_DAT[0]', 'SD0_DAT[1]', 'XIN', 'XOUT', 'VDD18', 'VSSQ', 'VDDQ', 
        'VSSQ', 'MVDD', 'VSS', 'MVREF', 'PLL_UD_VDD18', 'UD_VSS', 'UD_DM', 'UD_DP', 'UD_VDD33', 'UD_REXT', 
        'LVDATA[17]', 'LVDATA[16]', 'LVDATA[15]', 'LVDATA[14]', 'LVDATA[13]', 'LVDATA[12]', 'LVDATA[11]', 'LVDATA[10]', 'LVDATA[9]', 'LVDATA[8]', 
        'LVDATA[7]', 'LVDATA[6]', 'LVDATA[5]', 'LVDATA[4]', 'LVDATA[3]', 'LVDATA[2]', 'LVDATA[1]', 'LVDATA[0]', 'LVDE', 'LVSYNC', 
        'VSS', 'LHSYNC', 'VDD18', 'LPCLK', 'VDD33', 'ADC_VSS33', 'ADC_TP_YM', 'ADC_TP_XM', 'ADC_TP_XP', 'ADC_TP_YP', 
        'ADC_VDD33', 'ADC_AIN[2]', 'ADC_AIN[3]', 'ADC_AIN[4]', 'RTC_XOUT', 'RTC_XIN', 'RTC_VDD1.8V', 'VDD33', 'GPA[6]', 'GPA[5]', 
        'GPA[4]', 'GPA[3]', 'GPA[2]', 'GPA[1]', 'GPA[0]', 'RST_', 'TCK', 'TMS', 'TDI', 'TDO', 
        'TRST_', 'UD_CDET', 'VDD18', 'MVDD', 'MVSS', 'MVREF', 'VSSQ', 'VDDQ', 'VDD33', 'ADAC_HPVSS33', 
        'ADAC_HPVDD33', 'ADAC_HPOUT_L', 'ADAC_HPOUT_R', 'ADAC_AVSS33', 'ADAC_VREF', 'ADAC_AVDD33', 'VDD18', 'GPA[7]', 'ND[0]', 'ND[1]', 
        'ND[2]', 'ND[3]', 'ND[4]', 'ND[5]', 'ND[6]', 'ND[7]', 'NBUSY1_', 'NBUSY0_', 'NWR_', 'NRE_', 
        'NCLE', 'NALE', 'NCS1_', 'VSS', 'NCS0_', 'VDD33', 'URTXD', 'URRXD', 'GPB[12]', 'GPB[11]', 
        'GPB[10]', 'GPB[9]', 'GPB[8]', 'GPB[7]', 'GPB[6]', 'GPB[5]', 'GPB[4]', 'GPB[3]'
    ],
    "TQFP64": [
        'SPI0_CLK', 'SPI0_CS0_', 'SPI0_DI', 'SPI0_DO', 'XIN', 'XOUT', 'VDD18', 'MVDD33', 'PLL_UD_VDD18', 'UD_DM', 
        'UD_DP', 'UD_VDD33', 'UD_REXT', 'LVDATA[15]', 'LVDATA[14]', 'LVDATA[13]', 'LVDATA[12]', 'LVDATA[11]', 'LVDATA[10]', 'LVDATA[9]', 
        'LVDATA[8]', 'LVDATA[7]', 'LVDATA[6]', 'LVDATA[5]', 'LVDATA[4]', 'LVDATA[3]', 'LVDATA[2]', 'LVDATA[1]', 'LVDATA[0]', 'LVDE', 
        'LVSYNC', 'LHSYNC', 'LPCLK', 'ADC_VDD33', 'RTC_VDD1.8V', 'VDD33', 'GPA[5]', 'GPA[4]', 'GPA[3]', 'GPA[2]', 
        'RST_', 'TCK', 'TMS', 'TDI', 'TDO', 'TRST_', 'UD_CDET', 'VDD18', 'MVDD33', 'MVDD33', 
        'AVDD33', 'VDD18', 'GPA[7]', 'GPD[6]', 'GPD[5]', 'GPD[8]', 'GPD[7]', 'GPE[9]', 'GPE[8]', 'VDD33', 
        'URTXD', 'URRXD', 'ISDA', 'ISCK'
    ]
};

NUTOOL_PIN.g_cfg_gpios = [
    { f: ['PA.0:0', 'LCD_DATA0:3', 'PWRON_SET0:8'] },
    { f: ['PA.1:0', 'LCD_DATA1:3', 'PWRON_SET1:8'] },
    { f: ['PA.2:0', 'LCD_DATA2:3', 'PWRON_SET2:8'] },
    { f: ['PA.3:0', 'LCD_DATA3:3', 'PWRON_SET3:8'] },
    { f: ['PA.4:0', 'LCD_DATA4:3', 'PWRON_SET4:8'] },
    { f: ['PA.5:0', 'LCD_DATA5:3', 'PWRON_SET5:8'] },
    { f: ['PA.6:0', 'LCD_DATA6:3', 'PWRON_SET6:8'] },
    { f: ['PA.7:0', 'LCD_DATA7:3', 'PWRON_SET7:8'] },
    { f: ['PA.8:0', 'LCD_DATA8:3', 'PWRON_SET8:8'] },
    { f: ['PA.9:0', 'LCD_DATA9:3', 'PWRON_SET9:8'] },
    { f: ['PA.10:0', 'LCD_DATA10:3'] },
    { f: ['PA.11:0', 'LCD_DATA11:3'] },
    { f: ['PA.12:0', 'PWM0:2', 'LCD_DATA12:3'] },
    { f: ['PA.13:0', 'PWM1:2', 'LCD_DATA13:3'] },
    { f: ['PA.14:0', 'PWM2:2', 'LCD_DATA14:3'] },
    { f: ['PA.15:0', 'PWM3:2', 'LCD_DATA15:3'] },

    { f: ['GPB[0]:0', 'UART5_TXD:1', 'NAND_nCS1:3', 'TM1_TGL:4', 'SPI0_SS1:5'] },
    { f: ['PB.1:0', 'UART5_RXD:1', 'NAND_RDY1:3', 'TM1_CAP:4', 'SPI1_SS1:5'] },
    { f: ['PB.2:0', 'UART6_TXD:1', 'PWM0:2', 'TM0_TGL:3'] },
    { f: ['PB.3:0', 'UART6_RXD:1', 'PWM1:2', 'TM0_CAP:3'] },
    { f: ['PB.4:0', 'UART6_RTS:1'] },
    { f: ['PB.5:0', 'UART6_CTS:1'] },
    { f: ['PB.6:0', 'SPI0_SS0:2'] },
    { f: ['PB.7:0', 'SPI0_CLK:2'] },
    { f: ['PB.8:0', 'SPI0_DO:2', 'D0:2'] },
    { f: ['PB.9:0', 'SPI0_DI:2', 'D1:2'] },
    { f: ['PB.10:0', 'UART10_TXD:1', 'SPI0_DATA2:2', 'CAN0_RXD:3'] },
    { f: ['PB.11:0', 'UART10_RXD:1', 'SPI0_DATA3:2', 'CAN0_TXD:3'] },
    { f: ['PB.12:0', 'UART10_TXD:1', 'SPI1_SS0:2'] },
    { f: ['PB.13:0', 'UART10_RXD:1', 'SPI1_CLK:2'] },
    { f: ['PB.14:0', 'UART10_RTS:1', 'SPI1_DO:2', 'D0:2'] },
    { f: ['PB.15:0', 'UART10_CTS:1', 'SPI1_DI:2', 'D1:2'] },

    { f: ['PC.0:0', 'eMMC_DATA0:1', 'NAND_DATA0:3'] },
    { f: ['PC.1:0', 'eMMC_DATA1:1', 'NAND_DATA1:3'] },
    { f: ['PC.2:0', 'eMMC_DATA2:1', 'NAND_DATA2:3'] },
    { f: ['PC.3:0', 'eMMC_DATA3:1', 'NAND_DATA3:3'] },
    { f: ['PC.4:0', 'eMMC_CMD:1', 'NAND_DATA4:3'] },
    { f: ['PC.5:0', 'eMMC_CLK:1', 'NAND_DATA5:3'] },
    { f: ['PC.6:0', 'UART10_TXD:1', 'TM0_TGL:2', 'NAND_DATA6:3'] },
    { f: ['PC.7:0', 'UART10_RXD:1', 'TM0_CAP:2', 'NAND_DATA7:3'] },
    { f: ['PC.8:0', 'UART10_RTS:1', 'TM1_TGL:2', 'NAND_nCS0:3'] },
    { f: ['PC.9:0', 'UART10_CTS:1', 'TM1_CAP:2', 'NAND_ALE:3'] },
    { f: ['PC.10:0', 'UART4_TXD:1', 'TM2_TGL:2', 'NAND_CLE:3'] },
    { f: ['PC.11:0', 'UART4_RXD:1', 'TM2_CAP:2', 'NAND_nWE:3'] },
    { f: ['PC.12:0', 'UART4_RTS:1', 'TM3_TGL:2', 'NAND_nRE:3'] },
    { f: ['PC.13:0', 'UART4_CTS:1', 'TM3_CAP:2', 'NAND_RDY0:3'] },
    { f: ['PC.14:0', 'PWM0:1', 'NAND_nWP:3'] },
    { f: ['PC.15:0'] },

    { f: ['PD.0:0', 'SD0_CMD:1'] },
    { f: ['PD.1:0', 'SD0_CLK:1'] },
    { f: ['PD.2:0', 'SD0_DAT0:1'] },
    { f: ['PD.3:0', 'SD0_DAT1:1'] },
    { f: ['PD.4:0', 'SD0_DAT2:1'] },
    { f: ['PD.5:0', 'SD0_DAT3:1'] },
    { f: ['PD.6:0', 'SD0_nCD:1'] },
    { f: ['PD.7:0', 'SD0_nPWR:1'] },
    { f: ['PD.8:0', 'EBI_nCS0:1', 'LCD_DATA16:3'] },
    { f: ['PD.9:0', 'EBI_nCS1:1', 'LCD_DATA17:3'] },
    { f: ['PD.10:0', 'EBI_nCS2:1', 'LCD_DATA18:3'] },
    { f: ['PD.11:0', 'EBI_nCS3:1', 'LCD_DATA19:3', 'UART9_TXD:4'] },
    { f: ['PD.12:0', 'EBI_nCS4:1', 'PWM0:2', 'LCD_DATA20:3', 'UART9_RXD:4'] },
    { f: ['PD.13:0', 'EBI_nWE:1', 'PWM1:2', 'LCD_DATA21:3'] },
    { f: ['PD.14:0', 'EBI_nOE:1', 'PWM2:2', 'LCD_DATA22:3', 'UART9_TXD:4'] },
    { f: ['PD.15:0', 'EBI_nWAIT:1', 'PWM3:2', 'LCD_DATA23:3', 'UART9_RXD:4'] },

    { f: ['PE.0:0', 'UART0_TXD:1'] },
    { f: ['PE.1:0', 'UART0_RXD:1'] },
    { f: ['PE.2:0', 'RMII_MDC:1', 'SD1_CMD:2', 'UART1_TXD:3'] },
    { f: ['PE.3:0', 'RMII1_MDIO:1', 'SD1_CLK:2', 'UART1_RXD:3'] },
    { f: ['PE.4:0', 'RMII1_TXDATA0:1', 'SD1_DAT0:2', 'UART1_RTS:3'] },
    { f: ['PE.5:0', 'RMII1_TXDATA1:1', 'SD1_DAT1:2', 'UART1_CTS:3', 'CLK_OUT:5'] },
    { f: ['PE.6:0', 'RMII1_TXEN:1', 'SD1_DAT2:2', 'UART1_DTR:3'] },
    { f: ['PE.7:0', 'RMII1_REFCLK:1', 'SD1_DAT3:2', 'UART1_DSR:3'] },
    { f: ['PE.8:0', 'RMII1_RXDATA0:1', 'SD1_nCD:2', 'UART1_RI:3'] },
    { f: ['PE.9:0', 'RMII1_RXDATA1:1', 'SD1_nPWR:2', 'UART1_CD:3'] },
    { f: ['PE.10:0', 'RMII1_CRSDV:1', 'UART8_TXD:2'] },
    { f: ['PE.11:0', 'RMII1_RXERR:1', 'UART8_RXD:2'] },
    { f: ['PE.12:0', 'UART8_RTS:1', 'UART3_TXD:2'] },
    { f: ['PE.13:0', 'UART8_CTS:1', 'UART3_RXD:2', 'RMII1_PPS:3', 'CLK_OUT:5'] },
    { f: ['PE.14:0', 'USB0_PWREN:1'] },
    { f: ['PE.15:0', 'USB1_PWREN:1'] },

    { f: ['PF.0:0', 'RMII0_MDC:1'] },
    { f: ['PF.1:0', 'RMII0_MDIO:1'] },
    { f: ['PF.2:0', 'RMII0_TXDATA0:1'] },
    { f: ['PF.3:0', 'RMII0_TXDATA1:1'] },
    { f: ['PF.4:0', 'RMII0_TXEN:1'] },
    { f: ['PF.5:0', 'RMII0_REFCLK:1'] },
    { f: ['PF.6:0', 'RMII0_RXDATA0:1'] },
    { f: ['PF.7:0', 'RMII0_RXDATA1:1'] },
    { f: ['PF.8:0', 'RMII0_CRSDV:1'] },
    { f: ['PF.9:0', 'RMII0_RXERR:1'] },
    { f: ['PF.10:0', 'USB_PWREN:1', 'WDT_nRST:2'] },
    { f: ['PF.11:0', 'TM2_TGL:1', 'INT0:2', 'UART2_TXD:3'] },
    { f: ['PF.12:0', 'TM2_CAP:1', 'INT1:2', 'UART2_RXD:3'] },
    { f: ['PF.13:0', 'TM3_TGL:1', 'INT2:2', 'UART2_RTS:3'] },
    { f: ['PF.14:0', 'TM3_CAP:1', 'INT3:2', 'UART2_CTS:3', 'RMII0_PPS:4'] },
    { f: ['PF.15:0'] },

    { f: ['PG.0:0', 'I2C0_SCL:1'] },
    { f: ['PG.1:0', 'I2C0_SDA:1'] },
    { f: ['PG.2:0', 'I2C1_SCL:1'] },
    { f: ['PG.3:0', 'I2C1_SDA:1'] },
    { f: ['PG.4:0', 'UART7_TXD:1', 'SPI1_DATA2:2', 'NAND_nCS1:3'] },
    { f: ['PG.5:0', 'UART7_RXD:1', 'SPI1_DATA3:2', 'NAND_RDY1:3'] },
    { f: ['PG.6:0', 'LCD_CLK:3'] },
    { f: ['PG.7:0', 'LCD_HSYNC:3'] },
    { f: ['PG.8:0', 'LCD_VSYNC:3'] },
    { f: ['PG.9:0', 'LCD_DEN:3'] },
    { f: ['PG.10:0', 'SC0_RST:1', 'I2S_MCLK:2'] },
    { f: ['PG.11:0', 'SC0_CLK:1', 'I2S_DO:2', 'UART6_TXD:3'] },
    { f: ['PG.12:0', 'SC0_DAT:1', 'I2S_DI:2', 'UART6_RXD:3'] },
    { f: ['PG.13:0', 'SC0_PWR:1', 'I2S_BCLK:2', 'UART6_RTS:3'] },
    { f: ['PG.14:0', 'SC0_CD:1', 'I2S_LRCK:2', 'UART6_CTS:3', 'CLK_OUT:5'] },
    { f: ['PG.15:0'] },

    { f: ['PH.0:0', 'USB0_VBUSVLD:1', 'INT0:2'] },
    { f: ['PH.1:0', 'USB_OVRCUR:1', 'INT1:2'] },
    { f: ['PH.2:0', 'I2C1_SCL:1', 'CAN0_RXD:2', 'PWM2:3', 'UART9_TXD:4', 'INT2:5'] },
    { f: ['PH.3:0', 'I2C1_SDA:1', 'CAN0_TXD:2', 'PWM3:3', 'UART9_RXD:4', 'INT3:5'] },
    { f: ['PH.4:0', 'EBI_ADDR0:1', 'RTC_TICK:2', 'UART1_TXD:3', 'INT4:4'] },
    { f: ['PH.5:0', 'EBI_ADDR1:1', 'UART1_RXD:3', 'INT5:4'] },
    { f: ['PH.6:0', 'EBI_ADDR2:1', 'SD1_CMD:3', 'INT6:4', 'UART1_RTS:5'] },
    { f: ['PH.7:0', 'EBI_ADDR3:1', 'SD1_CLK:3', 'INT7:4', 'UART1_CTS:5'] },
    { f: ['PH.8:0', 'EBI_ADDR4:1', 'SD1_DAT0:3', 'UART4_TXD:4'] },
    { f: ['PH.9:0', 'EBI_ADDR5:1', 'SD1_DAT1:3', 'UART4_RXD:4'] },
    { f: ['PH.10:0', 'EBI_ADDR6:1', 'SD1_DAT2:3', 'UART4_RTS:4'] },
    { f: ['PH.11:0', 'EBI_ADDR7:1', 'SD1_DAT3:3', 'UART4_CTS:4'] },
    { f: ['PH.12:0', 'EBI_ADDR8:1', 'SD1_nCD:3', 'UART8_TXD:4', 'SPI0_SS1:5'] },
    { f: ['PH.13:0', 'EBI_ADDR9:1', 'SPI1_SS1:3', 'UART8_RXD:4', 'SD1_nPWR:5'] },
    { f: ['PH.14:0', 'EBI_nBE0:1', 'CAN1_RXD:3', 'UART8_RTS:4'] },
    { f: ['PH.15:0', 'EBI_nBE1:1', 'CAN1_TXD:3', 'UART8_CTS:4'] },

    { f: ['PI.0:0', 'EBI_DATA0:1'] },
    { f: ['PI.1:0', 'EBI_DATA1:1', 'UART7_TXD:2', 'NAND_nCS0:3', 'INT6:4'] },
    { f: ['PI.2:0', 'EBI_DATA2:1', 'UART7_RXD:2', 'NAND_nWP:3', 'INT7:4'] },
    { f: ['PI.3:0', 'EBI_DATA3:1', 'VCAP_CLKO:2', 'NAND_ALE:3', 'I2C1_SCL:4', 'CAN0_RXD:5'] },
    { f: ['PI.4:0', 'EBI_DATA4:1', 'VCAP_PCLK:2', 'NAND_CLE:3', 'I2C1_SDA:4', 'CAN0_TXD:5'] },
    { f: ['PI.5:0', 'EBI_DATA5:1', 'VCAP_HSYNC:2', 'NAND_nWE:3', 'SD1_CMD:4', 'eMMC_CMD:5', 'UART1_TXD:6', 'SPI1_SS0:7'] },
    { f: ['PI.6:0', 'EBI_DATA6:1', 'VCAP_VSYNC:2', 'NAND_nRE:3', 'SD1_CLK:4', 'eMMC_CLK:5', 'UART1_RXD:6', 'SPI1_CLK:7', 'SC1_RST:8'] },
    { f: ['PI.7:0', 'EBI_DATA7:1', 'VCAP_FIELD:2', 'NAND_RDY0:3', 'SD1_DAT0:4', 'eMMC_DATA3:5', 'UART1_RTS:6', 'SPI1_DO:7', 'D0:7', 'SC1_CLK:8'] },
    { f: ['PI.8:0', 'EBI_DATA8:1', 'VCAP_DATA0:2', 'NAND_DATA0:3', 'SD1_DAT1:4', 'eMMC_DATA0:5', 'UART1_CTS:6', 'SPI1_DI:7', 'D1:7', 'SC1_DAT:8'] },
    { f: ['PI.9:0', 'EBI_DATA9:1', 'VCAP_DATA1:2', 'NAND_DATA1:3', 'SD1_DAT2:4', 'eMMC_DATA1:5', 'UART4_TXD:6', 'SC1_PWR:8'] },
    { f: ['PI.10:0', 'EBI_DATA10:1', 'VCAP_DATA2:2', 'NAND_DATA2:3', 'SD1_DAT3:4', 'eMMC_DATA2:5', 'UART4_RXD:6', 'SC1_CD:8'] },
    { f: ['PI.11:0', 'EBI_DATA11:1', 'VCAP_DATA3:2', 'NAND_DATA3:3', 'SC0_RST:4'] },
    { f: ['PI.12:0', 'EBI_DATA12:1', 'VCAP_DATA4:2', 'NAND_DATA4:3', 'SC0_CLK:4', 'UART8_TXD:5', 'SD1_nCD:6'] },
    { f: ['PI.13:0', 'EBI_DATA13:1', 'VCAP_DATA5:2', 'NAND_DATA5:3', 'SC0_DAT:4', 'UART8_RXD:5', 'SD1_nPWR:6'] },
    { f: ['PI.14:0', 'EBI_DATA14:1', 'VCAP_DATA6:2', 'NAND_DATA6:3', 'SC0_PWR:4', 'UART8_RTS:5'] },
    { f: ['PI.15:0', 'EBI_DATA15:1', 'VCAP_DATA7:2', 'NAND_DATA7:3', 'SC0_CD:4', 'UART8_CTS:5', 'CLK_OUT:6'] },

    { f: ['PJ.0:0', 'JTAG_TCK:1'] },
    { f: ['PJ.1:0', 'JTAG_TMS:1'] },
    { f: ['PJ.2:0', 'JTAG_TDI:1'] },
    { f: ['PJ.3:0', 'JTAG_TDO:1'] },
    { f: ['PJ.4:0', 'JTAG_nTRST:1'] },
    { f: ['PJ.5:0'] },
    { f: ['PJ.6:0'] },
    { f: ['PJ.7:0'] }
];

NUTOOL_PIN.g_cfg_gpiosDefines = [
];

NUTOOL_PIN.g_cfg_gpiosDescriptions = [
    'CAN0_RXD:CAN0 bus receiver input.',
    'CAN0_TXD:CAN0 bus transmitter output.',
    'CAN1_RXD:CAN1 bus receiver input.',
    'CAN1_TXD:CAN1 bus transmitter output.',
    // 'CLK_OUT:',
    'EBI_ADDR0:EBI address/data bus bit D.',
    'EBI_ADDR1:EBI address/data bus bit D.',
    'EBI_ADDR2:EBI address/data bus bit D.',
    'EBI_ADDR3:EBI address/data bus bit D.',
    'EBI_ADDR4:EBI address/data bus bit D.',
    'EBI_ADDR5:EBI address/data bus bit D.',
    'EBI_ADDR6:EBI address/data bus bit D.',
    'EBI_ADDR7:EBI address/data bus bit D.',
    'EBI_ADDR8:EBI address/data bus bit D.',
    'EBI_ADDR9:EBI address/data bus bit D.',
    'EBI_DATA0:EBI data bus bit 0.',
    'EBI_DATA1:EBI data bus bit 1.',
    'EBI_DATA2:EBI data bus bit 2.',
    'EBI_DATA3:EBI data bus bit 3.',
    'EBI_DATA4:EBI data bus bit 4.',
    'EBI_DATA5:EBI data bus bit 5.',
    'EBI_DATA6:EBI data bus bit 6.',
    'EBI_DATA7:EBI data bus bit 7.',
    'EBI_DATA8:EBI data bus bit 8.',
    'EBI_DATA9:EBI data bus bit 9.',
    'EBI_DATA10:EBI data bus bit 10.',
    'EBI_DATA11:EBI data bus bit 11.',
    'EBI_DATA12:EBI data bus bit 12.',
    'EBI_DATA13:EBI data bus bit 13.',
    'EBI_DATA14:EBI data bus bit 14.',
    'EBI_DATA15:EBI data bus bit 15.',
    // 'EBI_nBE0:',
    // 'EBI_nBE1:',
    'EBI_nCS0:EBI chip select 0 output pin.',
    'EBI_nCS1:EBI chip select 1 output pin.',
    'EBI_nCS2:EBI chip select 2 output pin.',
    'EBI_nCS3:EBI chip select 3 output pin.',
    'EBI_nCS4:EBI chip select 4 output pin.',
    // 'EBI_nOE:',
    // 'EBI_nWAIT:',
    // 'EBI_nWE:',
    // 'eMMC_CLK:',
    // 'eMMC_CMD:',
    // 'eMMC_DATA0:',
    // 'eMMC_DATA1:',
    // 'eMMC_DATA2:',
    // 'eMMC_DATA3:',
    'I2C0_SCL:I2C0 clock pin.',
    'I2C0_SDA:I2C0 data input/output pin.',
    'I2C1_SCL:I2C1 clock pin.',
    'I2C1_SDA:I2C1 data input/output pin.',
    'I2S_BCLK:I2S_ bit clock output pin.',
    'I2S_DI:I2S_ data input pin.',
    'I2S_DO:I2S_ data output pin.',
    'I2S_LRCK:I2S_ left right channel clock output pin.',
    'I2S_MCLK:I2S_ master clock output pin.',
    'INT0:External interrupt 0 input pin.',
    'INT1:External interrupt 1 input pin.',
    'INT2:External interrupt 2 input pin.',
    'INT3:External interrupt 3 input pin.',
    'INT4:External interrupt 4 input pin.',
    'INT5:External interrupt 5 input pin.',
    'INT6:External interrupt 6 input pin.',
    'INT7:External interrupt 7 input pin.',
    'JTAG_nTRST:JTAG reset input pin.',
    'JTAG_TCK:JTAG clock input pin.',
    'JTAG_TDI:JTAG data input pin.',
    'JTAG_TDO:JTAG data output pin.',
    'JTAG_TMS:JTAG test mode selection input pin.',
    // 'LCD_CLK:',
    // 'LCD_DATA0:',
    // 'LCD_DATA1:',
    // 'LCD_DATA2:',
    // 'LCD_DATA3:',
    // 'LCD_DATA4:',
    // 'LCD_DATA5:',
    // 'LCD_DATA6:',
    // 'LCD_DATA7:',
    // 'LCD_DATA8:',
    // 'LCD_DATA9:',
    // 'LCD_DATA10:',
    // 'LCD_DATA11:',
    // 'LCD_DATA12:',
    // 'LCD_DATA13:',
    // 'LCD_DATA14:',
    // 'LCD_DATA15:',
    // 'LCD_DATA16:',
    // 'LCD_DATA17:',
    // 'LCD_DATA18:',
    // 'LCD_DATA19:',
    // 'LCD_DATA20:',
    // 'LCD_DATA21:',
    // 'LCD_DATA22:',
    // 'LCD_DATA23:',
    // 'LCD_DEN:',
    // 'LCD_HSYNC:',
    // 'LCD_VSYNC:',
    // 'NAND_ALE:',
    // 'NAND_CLE:',
    // 'NAND_DATA0:',
    // 'NAND_DATA1:',
    // 'NAND_DATA2:',
    // 'NAND_DATA3:',
    // 'NAND_DATA4:',
    // 'NAND_DATA5:',
    // 'NAND_DATA6:',
    // 'NAND_DATA7:',
    // 'NAND_nCS0:',
    // 'NAND_nCS1:',
    // 'NAND_nRE:',
    // 'NAND_nWE:',
    // 'NAND_nWP:',
    // 'NAND_RDY0:',
    // 'NAND_RDY1:',
    // 'PWM0:',
    // 'PWM1:',
    // 'PWM2:',
    // 'PWM3:',
    // 'PWRON_SET0:',
    // 'PWRON_SET1:',
    // 'PWRON_SET2:',
    // 'PWRON_SET3:',
    // 'PWRON_SET4:',
    // 'PWRON_SET5:',
    // 'PWRON_SET6:',
    // 'PWRON_SET7:',
    // 'PWRON_SET8:',
    // 'PWRON_SET9:',
    'RMII_MDC:RMII PHY Management Clock output pin.',
    // 'RMII0_CRSDV:',
    // 'RMII0_MDC:',
    // 'RMII0_MDIO:',
    // 'RMII0_PPS:',
    // 'RMII0_REFCLK:',
    // 'RMII0_RXDATA0:',
    // 'RMII0_RXDATA1:',
    // 'RMII0_RXERR:',
    // 'RMII0_TXDATA0:',
    // 'RMII0_TXDATA1:',
    // 'RMII0_TXEN:',
    // 'RMII1_CRSDV:',
    // 'RMII1_MDIO:',
    // 'RMII1_PPS:',
    // 'RMII1_REFCLK:',
    // 'RMII1_RXDATA0:',
    // 'RMII1_RXDATA1:',
    // 'RMII1_RXERR:',
    // 'RMII1_TXDATA0:',
    // 'RMII1_TXDATA1:',
    // 'RMII1_TXEN:',
    // 'RTC_TICK:',
    // 'SC0_CD:',
    'SC0_CLK:Smart Card 0 clock pin.',
    'SC0_DAT:Smart Card 0 data pin.',
    'SC0_PWR:Smart Card 0 power pin.',
    'SC0_RST:Smart Card 0 reset pin.',
    // 'SC1_CD:',
    'SC1_CLK:Smart Card 1 clock pin.',
    'SC1_DAT:Smart Card 1 data pin.',
    'SC1_PWR:Smart Card 1 power pin.',
    'SC1_RST:Smart Card 1 reset pin.',
    'SD0_CLK:SD/SDIO0 clock output pin',
    'SD0_CMD:SD/SDIO0 command/response pin',
    'SD0_DAT0:SD/SDIO0 data line bit 0.',
    'SD0_DAT1:SD/SDIO0 data line bit 1.',
    'SD0_DAT2:SD/SDIO0 data line bit 2.',
    'SD0_DAT3:SD/SDIO0 data line bit 3.',
    'SD0_nCD:SD/SDIO0 card detect input pin',
    // 'SD0_nPWR:',
    'SD1_CLK:SD/SDIO1 clock output pin',
    'SD1_CMD:SD/SDIO1 command/response pin',
    'SD1_DAT0:SD/SDIO1 data line bit 0.',
    'SD1_DAT1:SD/SDIO1 data line bit 1.',
    'SD1_DAT2:SD/SDIO1 data line bit 2.',
    'SD1_DAT3:SD/SDIO1 data line bit 3.',
    'SD1_nCD:SD/SDIO1 card detect input pin',
    // 'SD1_nPWR:',
    'SPI0_CLK:SPI0 serial clock pin.',
    // 'SPI0_DATA2:',
    // 'SPI0_DATA3:',
    // 'SPI0_DI/D1:',
    // 'SPI0_DO/D0:',
    'SPI0_SS0:SPI0 slave select 0 pin.',
    'SPI0_SS1:SPI0 slave select 1 pin.',
    'SPI1_CLK:SPI1 serial clock pin.',
    // 'SPI1_DATA2:',
    // 'SPI1_DATA3:',
    // 'SPI1_DI/D1:',
    // 'SPI1_DO/D0:',
    'SPI1_SS0:SPI1 slave select 0 pin.',
    'SPI1_SS1:SPI1 slave select 1 pin.',
    'TM0_EXT:Timer0 external capture input/toggle output pin.',
    'TM0_TGL:Timer0 event counter input/toggle output pin.',
    'TM1_EXT:Timer1 external capture input/toggle output pin.',
    'TM1_TGL:Timer1 event counter input/toggle output pin.',
    'TM2_EXT:Timer2 external capture input/toggle output pin.',
    'TM2_TGL:Timer2 event counter input/toggle output pin.',
    'TM3_EXT:Timer3 external capture input/toggle output pin.',
    'TM3_TGL:Timer3 event counter input/toggle output pin.',
    'UART0_RXD:UART0 data receiver input pin.',
    'UART0_TXD:UART0 data transmitter output pin.',
    // 'UART1_CD:',
    // 'UART1_CTS:',
    // 'UART1_DSR:',
    // 'UART1_DTR:',
    // 'UART1_RI:',
    // 'UART1_RTS:',
    'UART1_RXD:UART1 data receiver input pin.',
    'UART1_TXD:UART1 data transmitter output pin.',
    // 'UART2_CTS:',
    // 'UART2_RTS:',
    'UART2_RXD:UART2 data receiver input pin.',
    'UART2_TXD:UART2 data transmitter output pin.',
    'UART3_RXD:UART3 data receiver input pin.',
    'UART3_TXD:UART3 data transmitter output pin.',
    // 'UART4_CTS:',
    // 'UART4_RTS:',
    'UART4_RXD:UART4 data receiver input pin.',
    'UART4_TXD:UART4 data transmitter output pin.',
    'UART5_RXD:UART5 data receiver input pin.',
    'UART5_TXD:UART5 data transmitter output pin.',
    // 'UART6_CTS:',
    // 'UART6_RTS:',
    'UART6_RXD:UART6 data receiver input pin.',
    'UART6_TXD:UART6 data transmitter output pin.',
    'UART7_RXD:UART7 data receiver input pin.',
    'UART7_TXD:UART7 data transmitter output pin.',
    // 'UART8_CTS:',
    // 'UART8_RTS:',
    'UART8_RXD:UART8 data receiver input pin.',
    'UART8_TXD:UART8 data transmitter output pin.',
    'UART9_RXD:UART9 data receiver input pin.',
    'UART9_TXD:UART9 data transmitter output pin.',
    // 'UART10_CTS:',
    // 'UART10_RTS:',
    'UART10_RXD:UART10 data receiver input pin.',
    'UART10_TXD:UART10 data transmitter output pin.',
    // 'USB_OVRCUR:',
    // 'USB_PWREN:',
    // 'USB0_PWREN:',
    // 'USB0_VBUSVLD:',
    // 'USB1_PWREN:',
    // 'VCAP_CLKO:',
    // 'VCAP_DATA0:',
    // 'VCAP_DATA1:',
    // 'VCAP_DATA2:',
    // 'VCAP_DATA3:',
    // 'VCAP_DATA4:',
    // 'VCAP_DATA5:',
    // 'VCAP_DATA6:',
    // 'VCAP_DATA7:',
    // 'VCAP_FIELD:',
    // 'VCAP_HSYNC:',
    // 'VCAP_PCLK:',
    // 'VCAP_VSYNC:',
    // 'WDT_nRST:'
];

NUTOOL_PIN.g_cfg_regDescriptions = {};
NUTOOL_PIN.g_cfg_regDescriptions.GPA_MFPL = '0xB0000070';
NUTOOL_PIN.g_cfg_regDescriptions.GPA_MFPH = '0xB0000074';
NUTOOL_PIN.g_cfg_regDescriptions.GPB_MFPL = '0xB0000078';
NUTOOL_PIN.g_cfg_regDescriptions.GPB_MFPH = '0xB000007C';
NUTOOL_PIN.g_cfg_regDescriptions.GPC_MFPL = '0xB0000080';
NUTOOL_PIN.g_cfg_regDescriptions.GPC_MFPH = '0xB0000084';
NUTOOL_PIN.g_cfg_regDescriptions.GPD_MFPL = '0xB0000088';
NUTOOL_PIN.g_cfg_regDescriptions.GPD_MFPH = '0xB000008C';
NUTOOL_PIN.g_cfg_regDescriptions.GPE_MFPL = '0xB0000090';
NUTOOL_PIN.g_cfg_regDescriptions.GPE_MFPH = '0xB0000094';
NUTOOL_PIN.g_cfg_regDescriptions.GPF_MFPL = '0xB0000098';
NUTOOL_PIN.g_cfg_regDescriptions.GPF_MFPH = '0xB000009C';
NUTOOL_PIN.g_cfg_regDescriptions.GPG_MFPL = '0xB00000A0';
NUTOOL_PIN.g_cfg_regDescriptions.GPG_MFPH = '0xB00000A4';
NUTOOL_PIN.g_cfg_regDescriptions.GPH_MFPL = '0xB00000A8';
NUTOOL_PIN.g_cfg_regDescriptions.GPH_MFPH = '0xB00000AC';
NUTOOL_PIN.g_cfg_regDescriptions.GPI_MFPL = '0xB00000B0';
NUTOOL_PIN.g_cfg_regDescriptions.GPI_MFPH = '0xB00000B4';
NUTOOL_PIN.g_cfg_regDescriptions.GPJ_MFPL = '0xB00000B8';

NUTOOL_PIN.g_cfg_gpioMatrix = [];
NUTOOL_PIN.g_cfg_shareBits = [];
NUTOOL_PIN.g_cfg_addGPIO = {};
NUTOOL_PIN.g_cfg_unusedGPIO = {
};
NUTOOL_PIN.g_cfg_WPPin = [];

NUTOOL_PIN.decidepackageNumber = function (given_partNumber_package) {
    var partNumber_package,
        partNumber;

    if (typeof given_partNumber_package === 'undefined') {
        partNumber_package = NUTOOL_PIN.getg_partNumber_package();
    }
    else {
        partNumber_package = given_partNumber_package;
    }

    NUTOOL_PIN.g_packageNumber = partNumber_package.substring(partNumber_package.indexOf('(') + 1);
    NUTOOL_PIN.g_packageNumber = NUTOOL_PIN.g_packageNumber.substring(0, NUTOOL_PIN.g_packageNumber.indexOf(')'));

    partNumber = partNumber_package.substring(0, partNumber_package.indexOf('('));
    switch (NUTOOL_PIN.g_packageNumber) {
        case 'LQFP128':
            NUTOOL_PIN.g_packageNumberIndex = "LQFP128";
            break;
        case 'TQFP64':
            NUTOOL_PIN.g_packageNumberIndex = "TQFP64";
            break;
        default:
            break;
    }
    partNumber_package = null;
    partNumber = null;
};
