// chip content
NUTOOL_PIN.g_cfg_chips = [
    { name: "N9H30K41IEC", pkg: "LQFP128" },
    { name: "N9H30K63IEC", pkg: "LQFP128" },
    { name: "N9H30F51IEC", pkg: "LQFP216" },
    { name: "N9H30F63IEC", pkg: "LQFP216" },
    { name: "N9H30F71IEC", pkg: "LQFP216" }
];

NUTOOL_PIN.g_cfg_pkgs = {
    "LQFP128(14*14)": [
        'USB0_ID', 'PG.1', 'PG.0', 'PG.14', 'PG.13', 'PG.12', 'PG.11', 'PG.10', 'IO_VDD', 'CORE_VDD',
        'DDR_VDD', 'DDR_VDD', 'CORE_VDD', 'PG.9', 'PG.8', 'PG.7', 'PG.6', 'PA.15', 'PA.14', 'PA.13',
        'PA.12', 'PA.11', 'PA.10', 'IO_VDD', 'PA.9', 'PA.8', 'PA.7', 'PA.6', 'PA.5', 'PA.4',
        'PA.3', 'PA.2', 'PA.1', 'PA.0', 'ADC6', 'ADC4', 'AVSS', 'AVDD', 'ADC7', 'ADC5',
        'ADC3', 'RTC_VDD', 'X32_IN', 'X32_OUT', 'CORE_VDD', 'PI.1', 'PI.2', 'PI.3', 'PI.4', 'PI.5',
        'PI.6', 'PI.7', 'PI.8', 'PI.9', 'PI.10', 'PI.11', 'PI.12', 'PI.13', 'PI.14', 'PI.15',
        'IO_VDD', 'PB.2', 'PB.3', 'VSS', 'PB.6', 'PB.7', 'PB.8', 'PB.9', 'PB.10', 'PB.11',
        'PB.12', 'PB.13', 'PB.14', 'PB.15', 'PJ.3', 'PJ.0', 'PJ.1', 'PJ.2', 'PJ.4', 'nRESET',
        'IO_VDD', 'CORE_VDD', 'DDR_VDD', 'DDR_VDD', 'IO_VDD', 'PD.0', 'PD.1', 'PD.2', 'PD.3', 'PD.4',
        'PD.5', 'PD.6', 'PD.7', 'CORE_VDD', 'PLL_VSS', 'PH.3', 'PH.2', 'PE.13', 'PE.12', 'PE.1',
        'PE.0', 'IO_VDD', 'XT1_IN', 'XT1_OUT', 'PF.9', 'PF.8', 'PF.7', 'PF.6', 'PF.5', 'PF.4',
        'PF.3', 'PF.2', 'PF.1', 'PF.0', 'PH.1', 'PH.0', 'PF.10', 'CORE_VDD', 'USB1_DM', 'USB1_DP',
        'USB1_VDD', 'USB1_REXT', 'USBPLL0_VDD', 'USB0_DM', 'USB0_DP', 'USB0_VDD', 'USB0_REXT', 'VSS'
    ],
    "LQFP216(24*24)": [
        'PG.3', 'PG.2', 'PG.1', 'PG.0', 'PG.14', 'PG.13', 'PG.12', 'PG.11', 'PG.10', 'IO_VDD',
        'VSS', 'CORE_VDD', 'VSS', 'DDR_VDD', 'VSS', 'DDR_VDD', 'VSS', 'DDR_VDD', 'VSS', 'IO_VDD',
        'CORE_VDD', 'PF.14', 'PF.13', 'PF.12', 'PF.11', 'PG.9', 'PG.8', 'PG.7', 'PG.6', 'PD.15',
        'PD.14', 'PD.13', 'PD.12', 'PD.11', 'PD.10', 'PD.9', 'PD.8', 'PA.15', 'PA.14', 'PA.13',
        'PA.12', 'PA.11', 'PA.10', 'IO_VDD', 'PA.9', 'PA.8', 'PA.7', 'PA.6', 'PA.5', 'PA.4',
        'PA.3', 'PA.2', 'PA.1', 'PA.0', 'ADC0', 'ADC6', 'ADC4', 'AVSS', 'AVDD', 'ADC7',
        'ADC5', 'ADC1', 'ADC3', 'ADC2', 'VREF', 'RTC_VDD', 'SYS_PWREN', 'SYS_nWAKEUP', 'X32_IN', 'X32_OUT',
        'PH.4', 'PH.5', 'PH.6', 'PH.7', 'PH.8', 'PH.9', 'PH.10', 'PH.11', 'PH.12', 'IO_VDD',
        'VSS', 'CORE_VDD', 'PH.13', 'PH.14', 'PH.15', 'PI.0', 'PI.1', 'PI.2', 'PI.3', 'PI.4',
        'PI.5', 'PI.6', 'PI.7', 'PI.8', 'PI.9', 'PI.10', 'PI.11', 'PI.12', 'PI.13', 'PI.14',
        'PI.15', 'CORE_VDD', 'VSS', 'IO_VDD', 'PB.0', 'PB.1', 'PB.2', 'PB.3', 'PB.4', 'PB.5',
        'PB.6', 'PB.7', 'PB.8', 'PB.9', 'PB.10', 'PB.11', 'PB.12', 'PB.13', 'PB.14', 'PB.15',
        'PG.4', 'PG.5', 'PC.0', 'PC.1', 'PC.2', 'PC.3', 'PC.4', 'PC.5', 'PC.6', 'PC.7',
        'PC.8', 'PC.9', 'PC.10', 'PC.11', 'PC.12', 'PC.13', 'PC.14', 'PJ.3', 'PJ.0', 'PJ.1',
        'PJ.2', 'PJ.4', 'nRESET', 'IO_VDD', 'VSS', 'CORE_VDD', 'VSS', 'DDR_VDD', 'VSS', 'DDR_VDD',
        'VSS', 'DDR_VDD', 'VSS', 'IO_VDD', 'PD.0', 'PD.1', 'PD.2', 'PD.3', 'PD.4', 'PD.5',
        'PD.6', 'PD.7', 'CORE_VDD', 'PLL_VDD', 'PLL_VSS', 'CORE_VDD', 'PH.3', 'PH.2', 'PE.13', 'PE.12',
        'PE.11', 'PE.10', 'PE.9', 'PE.8', 'PE.7', 'PE.6', 'PE.5', 'PE.4', 'PE.3', 'PE.2',
        'PE.1', 'PE.0', 'IO_VDD', 'XT1_IN', 'XT1_OUT', 'VSS', 'PF.9', 'PF.8', 'PF.7', 'PF.6',
        'PF.5', 'PF.4', 'PF.3', 'PF.2', 'PF.1', 'PF.0', 'PH.1', 'PH.0', 'PF.10', 'PE.15',
        'PE.14', 'VSS', 'CORE_VDD', 'USBPLL1_VDD', 'USB1_VSS', 'USB1_DM', 'USB1_DP', 'USB1_VDD', 'USB1_REXT', 'USBPLL0_VDD',
        'USB0_VSS', 'USB0_DM', 'USB0_DP', 'USB0_VDD', 'USB0_REXT', 'USB0_ID'
    ]
};

NUTOOL_PIN.g_cfg_gpios = [
    { f: ['PA.0:0', 'LCD_DATA0:2'] },
    { f: ['PA.1:0', 'LCD_DATA1:2'] },
    { f: ['PA.2:0', 'LCD_DATA2:2'] },
    { f: ['PA.3:0', 'LCD_DATA3:2'] },
    { f: ['PA.4:0', 'LCD_DATA4:2'] },
    { f: ['PA.5:0', 'LCD_DATA5:2'] },
    { f: ['PA.6:0', 'LCD_DATA6:2'] },
    { f: ['PA.7:0', 'LCD_DATA7:2'] },
    { f: ['PA.8:0', 'LCD_DATA8:2'] },
    { f: ['PA.9:0', 'LCD_DATA9:2'] },
    { f: ['PA.10:0', 'LCD_DATA10:2'] },
    { f: ['PA.11:0', 'LCD_DATA11:2'] },
    { f: ['PA.12:0', 'LCD_DATA12:2', 'PWM0:13'] },
    { f: ['PA.13:0', 'LCD_DATA13:2', 'PWM1:13'] },
    { f: ['PA.14:0', 'LCD_DATA14:2', 'PWM2:13'] },
    { f: ['PA.15:0', 'LCD_DATA15:2', 'PWM3:13'] },

    { f: ['PB.0:0', 'NAND_nCS1:5', 'UART5_TXD:9', 'SPI0_SS1:11', 'TM1_TGL:13'] },
    { f: ['PB.1:0', 'NAND_RDY1:5', 'UART5_RXD:9', 'SPI1_SS1:11', 'TM1_CAP:13'] },
    { f: ['PB.2:0', 'UART6_TXD:9', 'PWM0:13', 'TM0_TGL:15'] },
    { f: ['PB.3:0', 'UART6_RXD:9', 'PWM1:13', 'TM0_CAP:15'] },
    { f: ['PB.4:0', 'UART6_RTS:9'] },
    { f: ['PB.5:0', 'UART6_CTS:9'] },
    { f: ['PB.6:0', 'SPI0_SS0:11'] },
    { f: ['PB.7:0', 'SPI0_CLK:11'] },
    { f: ['PB.8:0', 'SPI0_DO:11', 'D0:11'] },
    { f: ['PB.9:0', 'SPI0_DI:11', 'D1:11'] },
    { f: ['PB.10:0', 'UART10_TXD:9', 'SPI0_DATA2:11', 'CAN0_RXD:12'] },
    { f: ['PB.11:0', 'UART10_RXD:9', 'SPI0_DATA3:11', 'CAN0_TXD:12'] },
    { f: ['PB.12:0', 'UART10_TXD:9', 'SPI1_SS0:11'] },
    { f: ['PB.13:0', 'UART10_RXD:9', 'SPI1_CLK:11'] },
    { f: ['PB.14:0', 'UART10_RTS:9', 'SPI1_DO:11', 'D0:11'] },
    { f: ['PB.15:0', 'UART10_CTS:9', 'SPI1_DI:11', 'D1:11'] },

    { f: ['PC.0:0', 'NAND_DATA0:5', 'eMMC_DATA0:6'] },
    { f: ['PC.1:0', 'NAND_DATA1:5', 'eMMC_DATA1:6'] },
    { f: ['PC.2:0', 'NAND_DATA2:5', 'eMMC_DATA2:6'] },
    { f: ['PC.3:0', 'NAND_DATA3:5', 'eMMC_DATA3:6'] },
    { f: ['PC.4:0', 'NAND_DATA4:5', 'eMMC_CMD:6'] },
    { f: ['PC.5:0', 'NAND_DATA5:5', 'eMMC_CLK:6'] },
    { f: ['PC.6:0', 'NAND_DATA6:5', 'UART10_TXD:9', 'TM0_TGL:13'] },
    { f: ['PC.7:0', 'NAND_DATA7:5', 'UART10_RXD:9', 'TM0_CAP:13'] },
    { f: ['PC.8:0', 'NAND_nCS0:5', 'UART10_RTS:9', 'TM1_TGL:13'] },
    { f: ['PC.9:0', 'NAND_ALE:5', 'UART10_CTS:9', 'TM1_CAP:13'] },
    { f: ['PC.10:0', 'NAND_CLE:5', 'UART4_TXD:9', 'TM2_TGL:13'] },
    { f: ['PC.11:0', 'NAND_nWE:5', 'UART4_RXD:9', 'TM2_CAP:13'] },
    { f: ['PC.12:0', 'NAND_nRE:5', 'UART4_RTS:9', 'TM3_TGL:13'] },
    { f: ['PC.13:0', 'NAND_RDY0:5', 'UART4_CTS:9', 'TM3_CAP:13'] },
    { f: ['PC.14:0', 'NAND_nWP:5', 'PWM0:13'] },
    { f: ['PC.15:0'] },

    { f: ['PD.0:0', 'SD0_CMD:6'] },
    { f: ['PD.1:0', 'SD0_CLK:6'] },
    { f: ['PD.2:0', 'SD0_DAT0:6'] },
    { f: ['PD.3:0', 'SD0_DAT1:6'] },
    { f: ['PD.4:0', 'SD0_DAT2:6'] },
    { f: ['PD.5:0', 'SD0_DAT3:6'] },
    { f: ['PD.6:0', 'SD0_nCD:6'] },
    { f: ['PD.7:0'] },
    { f: ['PD.8:0', 'LCD_DATA16:2', 'EBI_nCS0:14'] },
    { f: ['PD.9:0', 'LCD_DATA17:2', 'EBI_nCS1:14'] },
    { f: ['PD.10:0', 'LCD_DATA18:2', 'EBI_nCS2:14'] },
    { f: ['PD.11:0', 'LCD_DATA19:2', 'UART9_TXD:9', 'EBI_nCS3:14'] },
    { f: ['PD.12:0', 'LCD_DATA20:2', 'UART9_RXD:9', 'PWM0:13', 'EBI_nCS4:14'] },
    { f: ['PD.13:0', 'LCD_DATA21:2', 'PWM1:13', 'EBI_nWE:14'] },
    { f: ['PD.14:0', 'LCD_DATA22:2', 'UART9_TXD:9', 'PWM2:13', 'EBI_nOE:14'] },
    { f: ['PD.15:0', 'LCD_DATA23:2', 'UART9_RXD:9', 'PWM3:13', 'EBI_nWAIT:14'] },

    { f: ['PE.0:0', 'UART0_TXD:9'] },
    { f: ['PE.1:0', 'UART0_RXD:9'] },
    { f: ['PE.2:0', 'RMII_MDC:1', 'SD1_CMD:6', 'UART1_TXD:9'] },
    { f: ['PE.3:0', 'RMII1_MDIO:1', 'SD1_CLK:6', 'UART1_RXD:9'] },
    { f: ['PE.4:0', 'RMII1_TXDATA0:1', 'SD1_DAT0:6', 'UART1_RTS:9'] },
    { f: ['PE.5:0', 'RMII1_TXDATA1:1', 'SD1_DAT1:6', 'UART1_CTS:9', 'CLK_OUT:15'] },
    { f: ['PE.6:0', 'RMII1_TXEN:1', 'SD1_DAT2:6', 'UART1_DTR:9'] },
    { f: ['PE.7:0', 'RMII1_REFCLK:1', 'SD1_DAT3:6', 'UART1_DSR:9'] },
    { f: ['PE.8:0', 'RMII1_RXDATA0:1', 'SD1_nCD:6', 'UART1_RI:9'] },
    { f: ['PE.9:0', 'RMII1_RXDATA1:1', 'SD1_nPWR:6', 'UART1_CD:9'] },
    { f: ['PE.10:0', 'RMII1_CRSDV:1', 'UART8_TXD:9'] },
    { f: ['PE.11:0', 'RMII1_RXERR:1', 'UART8_RXD:9'] },
    { f: ['PE.12:0', 'UART8_RTS:9', 'UART3_TXD:10'] },
    { f: ['PE.13:0', 'UART8_CTS:9', 'UART3_RXD:10', 'CLK_OUT:15'] },
    { f: ['PE.14:0', 'USB0_PWREN:7'] },
    { f: ['PE.15:0', 'USB1_PWREN:7'] },

    { f: ['PF.0:0', 'RMII0_MDC:1'] },
    { f: ['PF.1:0', 'RMII0_MDIO:1'] },
    { f: ['PF.2:0', 'RMII0_TXDATA0:1'] },
    { f: ['PF.3:0', 'RMII0_TXDATA1:1'] },
    { f: ['PF.4:0', 'RMII0_TXEN:1'] },
    { f: ['PF.5:0', 'RMII0_REFCLK:1'] },
    { f: ['PF.6:0', 'RMII0_RXDATA0:1'] },
    { f: ['PF.7:0', 'RMII0_RXDATA1:1'] },
    { f: ['PF.8:0', 'RMII0_CRSDV:1'] },
    { f: ['PF.9:0', 'RMII0_RXERR:1'] },
    { f: ['PF.10:0', 'USB_PWREN:7'] },
    { f: ['PF.11:0', 'UART2_TXD:9', 'TM2_TGL:13', 'INT0:15'] },
    { f: ['PF.12:0', 'UART2_RXD:9', 'TM2_CAP:13', 'INT1:15'] },
    { f: ['PF.13:0', 'UART2_RTS:9', 'TM3_TGL:13', 'INT2:15'] },
    { f: ['PF.14:0', 'UART2_CTS:9', 'TM3_CAP:13', 'INT3:15'] },
    { f: ['PF.15:0'] },

    { f: ['PG.0:0', 'I2C0_SCL:8'] },
    { f: ['PG.1:0', 'I2C0_SDA:8'] },
    { f: ['PG.2:0', 'I2C1_SCL:8'] },
    { f: ['PG.3:0', 'I2C1_SDA:8'] },
    { f: ['PG.4:0', 'NAND_nCS1:5', 'UART7_TXD:9', 'SPI1_DATA2:11'] },
    { f: ['PG.5:0', 'NAND_RDY1:5', 'UART7_RXD:9', 'SPI1_DATA3:11'] },
    { f: ['PG.6:0', 'LCD_CLK:2'] },
    { f: ['PG.7:0', 'LCD_HSYNC:2'] },
    { f: ['PG.8:0', 'LCD_VSYNC:2'] },
    { f: ['PG.9:0', 'LCD_DEN:2'] },
    { f: ['PG.10:0', 'I2S_MCLK:8', 'SC0_RST:10'] },
    { f: ['PG.11:0', 'I2S_DO:8', 'UART6_TXD:9', 'SC0_CLK:10'] },
    { f: ['PG.12:0', 'I2S_DI:8', 'UART6_RXD:9', 'SC0_DAT:10'] },
    { f: ['PG.13:0', 'I2S_BCLK:8', 'UART6_RTS:9', 'SC0_PWR:10'] },
    { f: ['PG.14:0', 'I2S_LRCK:8', 'UART6_CTS:9', 'SC0_CD:10', 'CLK_OUT:15'] },
    { f: ['PG.15:0'] },

    { f: ['PH.0:0', 'USB0_VBUSVLD:7', 'INT0:15'] },
    { f: ['PH.1:0', 'USB_OVRCUR:7', 'INT1:15'] },
    { f: ['PH.2:0', 'I2C1_SCL:8', 'UART9_TXD:9', 'CAN0_RXD:12', 'PWM2:13', 'INT2:15'] },
    { f: ['PH.3:0', 'I2C1_SDA:8', 'UART9_RXD:9', 'CAN0_TXD:12', 'PWM3:13', 'INT3:15'] },
    { f: ['PH.4:0', 'UART1_TXD:9', 'RTC_TICK:13', 'EBI_ADDR0:14', 'INT4:15'] },
    { f: ['PH.5:0', 'UART1_RXD:9', 'EBI_ADDR1:14', 'INT5:15'] },
    { f: ['PH.6:0', 'SD1_CMD:6', 'UART1_RTS:9', 'EBI_ADDR2:14', 'INT6:15'] },
    { f: ['PH.7:0', 'SD1_CLK:6', 'UART1_CTS:9', 'EBI_ADDR3:14', 'INT7:15'] },
    { f: ['PH.8:0', 'SD1_DAT0:6', 'UART4_TXD:9', 'EBI_ADDR4:14'] },
    { f: ['PH.9:0', 'SD1_DAT1:6', 'UART4_RXD:9', 'EBI_ADDR5:14'] },
    { f: ['PH.10:0', 'SD1_DAT2:6', 'UART4_RTS:9', 'EBI_ADDR6:14'] },
    { f: ['PH.11:0', 'SD1_DAT3:6', 'UART4_CTS:9', 'EBI_ADDR7:14'] },
    { f: ['PH.12:0', 'SD1_nCD:6', 'UART8_TXD:9', 'SPI0_SS1:11', 'EBI_ADDR8:14'] },
    { f: ['PH.13:0', 'SD1_nPWR:6', 'UART8_RXD:9', 'SPI1_SS1:11', 'EBI_ADDR9:14'] },
    { f: ['PH.14:0', 'UART8_RTS:9', 'CAN1_RXD:12', 'EBI_nBE0:14'] },
    { f: ['PH.15:0', 'UART8_CTS:9', 'CAN1_TXD:12', 'EBI_nBE1:14'] },

    { f: ['PI.0:0', 'EBI_DATA0:14'] },
    { f: ['PI.1:0', 'NAND_nCS0:5', 'UART7_TXD:9', 'EBI_DATA1:14', 'INT6:15'] },
    { f: ['PI.2:0', 'NAND_nWP:5', 'UART7_RXD:9', 'EBI_DATA2:14', 'INT7:15'] },
    { f: ['PI.3:0', 'VCAP_CLKO:3', 'NAND_ALE:5', 'I2C1_SCL:8', 'CAN0_RXD:12', 'EBI_DATA3:14'] },
    { f: ['PI.4:0', 'VCAP_PCLK:3', 'NAND_CLE:5', 'I2C1_SDA:8', 'CAN0_TXD:12', 'EBI_DATA4:14'] },
    { f: ['PI.5:0', 'VCAP_HSYNC:3', 'SD1_CMD:4', 'NAND_nWE:5', 'eMMC_CMD:6', 'UART1_TXD:9', 'SPI1_SS0:11', 'EBI_DATA5:14'] },
    { f: ['PI.6:0', 'VCAP_VSYNC:3', 'SD1_CLK:4', 'NAND_nRE:5', 'eMMC_CLK:6', 'UART1_RXD:9', 'SC1_RST:10', 'SPI1_CLK:11', 'EBI_DATA6:14'] },
    { f: ['PI.7:0', 'VCAP_FIELD:3', 'SD1_DAT0:4', 'NAND_RDY0:5', 'eMMC_DATA3:6', 'UART1_RTS:9', 'SC1_CLK:10', 'SPI1_DO:11', 'D0:11', 'EBI_DATA7:14'] },
    { f: ['PI.8:0', 'VCAP_DATA0:3', 'SD1_DAT1:4', 'NAND_DATA0:5', 'eMMC_DATA0:6', 'UART1_CTS:9', 'SC1_DAT:10', 'SPI1_DI:11', 'D1:11', 'EBI_DATA8:14'] },
    { f: ['PI.9:0', 'VCAP_DATA1:3', 'SD1_DAT2:4', 'NAND_DATA1:5', 'eMMC_DATA1:6', 'UART4_TXD:9', 'SC1_PWR:10', 'EBI_DATA9:14'] },
    { f: ['PI.10:0', 'VCAP_DATA2:3', 'SD1_DAT3:4', 'NAND_DATA2:5', 'eMMC_DATA2:6', 'UART4_RXD:9', 'SC1_CD:10', 'EBI_DATA10:14'] },
    { f: ['PI.11:0', 'VCAP_DATA3:3', 'NAND_DATA3:5', 'SC0_RST:10', 'EBI_DATA11:14'] },
    { f: ['PI.12:0', 'VCAP_DATA4:3', 'SD1_nCD:4', 'NAND_DATA4:5', 'UART8_TXD:9', 'SC0_CLK:10', 'EBI_DATA12:14'] },
    { f: ['PI.13:0', 'VCAP_DATA5:3', 'SD1_nPWR:4', 'NAND_DATA5:5', 'UART8_RXD:9', 'SC0_DAT:10', 'EBI_DATA13:14'] },
    { f: ['PI.14:0', 'VCAP_DATA6:3', 'NAND_DATA6:5', 'UART8_RTS:9', 'SC0_PWR:10', 'EBI_DATA14:14'] },
    { f: ['PI.15:0', 'VCAP_DATA7:3', 'NAND_DATA7:5', 'UART8_CTS:9', 'SC0_CD:10', 'EBI_DATA15:14'] },

    { f: ['PJ.0:0', 'JTAG_TCK:15'] },
    { f: ['PJ.1:0', 'JTAG_TMS:15'] },
    { f: ['PJ.2:0', 'JTAG_TDI:15'] },
    { f: ['PJ.3:0', 'JTAG_TDO:15'] },
    { f: ['PJ.4:0', 'JTAG_nTRST:15'] },
    { f: ['PJ.5:0'] },
    { f: ['PJ.6:0'] },
    { f: ['PJ.7:0'] },
    { f: ['PJ.8:0'] },
    { f: ['PJ.9:0'] },
    { f: ['PJ.10:0'] },
    { f: ['PJ.11:0'] },
    { f: ['PJ.12:0'] },
    { f: ['PJ.13:0'] },
    { f: ['PJ.14:0'] },
    { f: ['PJ.15:0'] }
];

NUTOOL_PIN.g_cfg_gpiosDefines = [
];

NUTOOL_PIN.g_cfg_gpiosDescriptions = [
    'CAN0_RXD:CAN0 bus receiver input.',
    'CAN0_TXD:CAN0 bus transmitter output.',
    'CAN1_RXD:CAN1 bus receiver input.',
    'CAN1_TXD:CAN1 bus transmitter output.',
    // 'CLK_OUT:',
    'EBI_ADDR0:EBI address/data bus bit D.',
    'EBI_ADDR1:EBI address/data bus bit D.',
    'EBI_ADDR2:EBI address/data bus bit D.',
    'EBI_ADDR3:EBI address/data bus bit D.',
    'EBI_ADDR4:EBI address/data bus bit D.',
    'EBI_ADDR5:EBI address/data bus bit D.',
    'EBI_ADDR6:EBI address/data bus bit D.',
    'EBI_ADDR7:EBI address/data bus bit D.',
    'EBI_ADDR8:EBI address/data bus bit D.',
    'EBI_ADDR9:EBI address/data bus bit D.',
    'EBI_DATA0:EBI data bus bit 0.',
    'EBI_DATA1:EBI data bus bit 1.',
    'EBI_DATA2:EBI data bus bit 2.',
    'EBI_DATA3:EBI data bus bit 3.',
    'EBI_DATA4:EBI data bus bit 4.',
    'EBI_DATA5:EBI data bus bit 5.',
    'EBI_DATA6:EBI data bus bit 6.',
    'EBI_DATA7:EBI data bus bit 7.',
    'EBI_DATA8:EBI data bus bit 8.',
    'EBI_DATA9:EBI data bus bit 9.',
    'EBI_DATA10:EBI data bus bit 10.',
    'EBI_DATA11:EBI data bus bit 11.',
    'EBI_DATA12:EBI data bus bit 12.',
    'EBI_DATA13:EBI data bus bit 13.',
    'EBI_DATA14:EBI data bus bit 14.',
    'EBI_DATA15:EBI data bus bit 15.',
    // 'EBI_nBE0:',
    // 'EBI_nBE1:',
    'EBI_nCS0:EBI chip select 0 output pin.',
    'EBI_nCS1:EBI chip select 1 output pin.',
    'EBI_nCS2:EBI chip select 2 output pin.',
    'EBI_nCS3:EBI chip select 3 output pin.',
    'EBI_nCS4:EBI chip select 4 output pin.',
    // 'EBI_nOE:',
    // 'EBI_nWAIT:',
    // 'EBI_nWE:',
    // 'eMMC_CLK:',
    // 'eMMC_CMD:',
    // 'eMMC_DATA0:',
    // 'eMMC_DATA1:',
    // 'eMMC_DATA2:',
    // 'eMMC_DATA3:',
    'I2C0_SCL:I2C0 clock pin.',
    'I2C0_SDA:I2C0 data input/output pin.',
    'I2C1_SCL:I2C1 clock pin.',
    'I2C1_SDA:I2C1 data input/output pin.',
    'I2S_BCLK:I2S_ bit clock output pin.',
    'I2S_DI:I2S_ data input pin.',
    'I2S_DO:I2S_ data output pin.',
    'I2S_LRCK:I2S_ left right channel clock output pin.',
    'I2S_MCLK:I2S_ master clock output pin.',
    'INT0:External interrupt 0 input pin.',
    'INT1:External interrupt 1 input pin.',
    'INT2:External interrupt 2 input pin.',
    'INT3:External interrupt 3 input pin.',
    'INT4:External interrupt 4 input pin.',
    'INT5:External interrupt 5 input pin.',
    'INT6:External interrupt 6 input pin.',
    'INT7:External interrupt 7 input pin.',
    'JTAG_nTRST:JTAG reset input pin.',
    'JTAG_TCK:JTAG clock input pin.',
    'JTAG_TDI:JTAG data input pin.',
    'JTAG_TDO:JTAG data output pin.',
    'JTAG_TMS:JTAG test mode selection input pin.',
    // 'LCD_CLK:',
    // 'LCD_DATA0:',
    // 'LCD_DATA1:',
    // 'LCD_DATA2:',
    // 'LCD_DATA3:',
    // 'LCD_DATA4:',
    // 'LCD_DATA5:',
    // 'LCD_DATA6:',
    // 'LCD_DATA7:',
    // 'LCD_DATA8:',
    // 'LCD_DATA9:',
    // 'LCD_DATA10:',
    // 'LCD_DATA11:',
    // 'LCD_DATA12:',
    // 'LCD_DATA13:',
    // 'LCD_DATA14:',
    // 'LCD_DATA15:',
    // 'LCD_DATA16:',
    // 'LCD_DATA17:',
    // 'LCD_DATA18:',
    // 'LCD_DATA19:',
    // 'LCD_DATA20:',
    // 'LCD_DATA21:',
    // 'LCD_DATA22:',
    // 'LCD_DATA23:',
    // 'LCD_DEN:',
    // 'LCD_HSYNC:',
    // 'LCD_VSYNC:',
    // 'NAND_ALE:',
    // 'NAND_CLE:',
    // 'NAND_DATA0:',
    // 'NAND_DATA1:',
    // 'NAND_DATA2:',
    // 'NAND_DATA3:',
    // 'NAND_DATA4:',
    // 'NAND_DATA5:',
    // 'NAND_DATA6:',
    // 'NAND_DATA7:',
    // 'NAND_nCS0:',
    // 'NAND_nCS1:',
    // 'NAND_nRE:',
    // 'NAND_nWE:',
    // 'NAND_nWP:',
    // 'NAND_RDY0:',
    // 'NAND_RDY1:',
    // 'PWM0:',
    // 'PWM1:',
    // 'PWM2:',
    // 'PWM3:',
    // 'PWRON_SET0:',
    // 'PWRON_SET1:',
    // 'PWRON_SET2:',
    // 'PWRON_SET3:',
    // 'PWRON_SET4:',
    // 'PWRON_SET5:',
    // 'PWRON_SET6:',
    // 'PWRON_SET7:',
    // 'PWRON_SET8:',
    // 'PWRON_SET9:',
    'RMII_MDC:RMII PHY Management Clock output pin.',
    // 'RMII0_CRSDV:',
    // 'RMII0_MDC:',
    // 'RMII0_MDIO:',
    // 'RMII0_PPS:',
    // 'RMII0_REFCLK:',
    // 'RMII0_RXDATA0:',
    // 'RMII0_RXDATA1:',
    // 'RMII0_RXERR:',
    // 'RMII0_TXDATA0:',
    // 'RMII0_TXDATA1:',
    // 'RMII0_TXEN:',
    // 'RMII1_CRSDV:',
    // 'RMII1_MDIO:',
    // 'RMII1_PPS:',
    // 'RMII1_REFCLK:',
    // 'RMII1_RXDATA0:',
    // 'RMII1_RXDATA1:',
    // 'RMII1_RXERR:',
    // 'RMII1_TXDATA0:',
    // 'RMII1_TXDATA1:',
    // 'RMII1_TXEN:',
    // 'RTC_TICK:',
    // 'SC0_CD:',
    'SC0_CLK:Smart Card 0 clock pin.',
    'SC0_DAT:Smart Card 0 data pin.',
    'SC0_PWR:Smart Card 0 power pin.',
    'SC0_RST:Smart Card 0 reset pin.',
    // 'SC1_CD:',
    'SC1_CLK:Smart Card 1 clock pin.',
    'SC1_DAT:Smart Card 1 data pin.',
    'SC1_PWR:Smart Card 1 power pin.',
    'SC1_RST:Smart Card 1 reset pin.',
    'SD0_CLK:SD/SDIO0 clock output pin',
    'SD0_CMD:SD/SDIO0 command/response pin',
    'SD0_DAT0:SD/SDIO0 data line bit 0.',
    'SD0_DAT1:SD/SDIO0 data line bit 1.',
    'SD0_DAT2:SD/SDIO0 data line bit 2.',
    'SD0_DAT3:SD/SDIO0 data line bit 3.',
    'SD0_nCD:SD/SDIO0 card detect input pin',
    // 'SD0_nPWR:',
    'SD1_CLK:SD/SDIO1 clock output pin',
    'SD1_CMD:SD/SDIO1 command/response pin',
    'SD1_DAT0:SD/SDIO1 data line bit 0.',
    'SD1_DAT1:SD/SDIO1 data line bit 1.',
    'SD1_DAT2:SD/SDIO1 data line bit 2.',
    'SD1_DAT3:SD/SDIO1 data line bit 3.',
    'SD1_nCD:SD/SDIO1 card detect input pin',
    // 'SD1_nPWR:',
    'SPI0_CLK:SPI0 serial clock pin.',
    // 'SPI0_DATA2:',
    // 'SPI0_DATA3:',
    // 'SPI0_DI/D1:',
    // 'SPI0_DO/D0:',
    'SPI0_SS0:SPI0 slave select 0 pin.',
    'SPI0_SS1:SPI0 slave select 1 pin.',
    'SPI1_CLK:SPI1 serial clock pin.',
    // 'SPI1_DATA2:',
    // 'SPI1_DATA3:',
    // 'SPI1_DI/D1:',
    // 'SPI1_DO/D0:',
    'SPI1_SS0:SPI1 slave select 0 pin.',
    'SPI1_SS1:SPI1 slave select 1 pin.',
    'TM0_EXT:Timer0 external capture input/toggle output pin.',
    'TM0_TGL:Timer0 event counter input/toggle output pin.',
    'TM1_EXT:Timer1 external capture input/toggle output pin.',
    'TM1_TGL:Timer1 event counter input/toggle output pin.',
    'TM2_EXT:Timer2 external capture input/toggle output pin.',
    'TM2_TGL:Timer2 event counter input/toggle output pin.',
    'TM3_EXT:Timer3 external capture input/toggle output pin.',
    'TM3_TGL:Timer3 event counter input/toggle output pin.',
    'UART0_RXD:UART0 data receiver input pin.',
    'UART0_TXD:UART0 data transmitter output pin.',
    // 'UART1_CD:',
    // 'UART1_CTS:',
    // 'UART1_DSR:',
    // 'UART1_DTR:',
    // 'UART1_RI:',
    // 'UART1_RTS:',
    'UART1_RXD:UART1 data receiver input pin.',
    'UART1_TXD:UART1 data transmitter output pin.',
    // 'UART2_CTS:',
    // 'UART2_RTS:',
    'UART2_RXD:UART2 data receiver input pin.',
    'UART2_TXD:UART2 data transmitter output pin.',
    'UART3_RXD:UART3 data receiver input pin.',
    'UART3_TXD:UART3 data transmitter output pin.',
    // 'UART4_CTS:',
    // 'UART4_RTS:',
    'UART4_RXD:UART4 data receiver input pin.',
    'UART4_TXD:UART4 data transmitter output pin.',
    'UART5_RXD:UART5 data receiver input pin.',
    'UART5_TXD:UART5 data transmitter output pin.',
    // 'UART6_CTS:',
    // 'UART6_RTS:',
    'UART6_RXD:UART6 data receiver input pin.',
    'UART6_TXD:UART6 data transmitter output pin.',
    'UART7_RXD:UART7 data receiver input pin.',
    'UART7_TXD:UART7 data transmitter output pin.',
    // 'UART8_CTS:',
    // 'UART8_RTS:',
    'UART8_RXD:UART8 data receiver input pin.',
    'UART8_TXD:UART8 data transmitter output pin.',
    'UART9_RXD:UART9 data receiver input pin.',
    'UART9_TXD:UART9 data transmitter output pin.',
    // 'UART10_CTS:',
    // 'UART10_RTS:',
    'UART10_RXD:UART10 data receiver input pin.',
    'UART10_TXD:UART10 data transmitter output pin.',
    // 'USB_OVRCUR:',
    // 'USB_PWREN:',
    // 'USB0_PWREN:',
    // 'USB0_VBUSVLD:',
    // 'USB1_PWREN:',
    // 'VCAP_CLKO:',
    // 'VCAP_DATA0:',
    // 'VCAP_DATA1:',
    // 'VCAP_DATA2:',
    // 'VCAP_DATA3:',
    // 'VCAP_DATA4:',
    // 'VCAP_DATA5:',
    // 'VCAP_DATA6:',
    // 'VCAP_DATA7:',
    // 'VCAP_FIELD:',
    // 'VCAP_HSYNC:',
    // 'VCAP_PCLK:',
    // 'VCAP_VSYNC:',
    // 'WDT_nRST:'
];

NUTOOL_PIN.g_cfg_regDescriptions = {};
NUTOOL_PIN.g_cfg_regDescriptions.GPA_MFPL = '0xB0000070';
NUTOOL_PIN.g_cfg_regDescriptions.GPA_MFPH = '0xB0000074';
NUTOOL_PIN.g_cfg_regDescriptions.GPB_MFPL = '0xB0000078';
NUTOOL_PIN.g_cfg_regDescriptions.GPB_MFPH = '0xB000007C';
NUTOOL_PIN.g_cfg_regDescriptions.GPC_MFPL = '0xB0000080';
NUTOOL_PIN.g_cfg_regDescriptions.GPC_MFPH = '0xB0000084';
NUTOOL_PIN.g_cfg_regDescriptions.GPD_MFPL = '0xB0000088';
NUTOOL_PIN.g_cfg_regDescriptions.GPD_MFPH = '0xB000008C';
NUTOOL_PIN.g_cfg_regDescriptions.GPE_MFPL = '0xB0000090';
NUTOOL_PIN.g_cfg_regDescriptions.GPE_MFPH = '0xB0000094';
NUTOOL_PIN.g_cfg_regDescriptions.GPF_MFPL = '0xB0000098';
NUTOOL_PIN.g_cfg_regDescriptions.GPF_MFPH = '0xB000009C';
NUTOOL_PIN.g_cfg_regDescriptions.GPG_MFPL = '0xB00000A0';
NUTOOL_PIN.g_cfg_regDescriptions.GPG_MFPH = '0xB00000A4';
NUTOOL_PIN.g_cfg_regDescriptions.GPH_MFPL = '0xB00000A8';
NUTOOL_PIN.g_cfg_regDescriptions.GPH_MFPH = '0xB00000AC';
NUTOOL_PIN.g_cfg_regDescriptions.GPI_MFPL = '0xB00000B0';
NUTOOL_PIN.g_cfg_regDescriptions.GPI_MFPH = '0xB00000B4';
NUTOOL_PIN.g_cfg_regDescriptions.GPJ_MFPL = '0xB00000B8';

NUTOOL_PIN.g_cfg_gpioMatrix = [];
NUTOOL_PIN.g_cfg_shareBits = [];
NUTOOL_PIN.g_cfg_addGPIO = {};
NUTOOL_PIN.g_cfg_unusedGPIO = {
};
NUTOOL_PIN.g_cfg_WPPin = [];

NUTOOL_PIN.decidepackageNumber = function (given_partNumber_package) {
    var partNumber_package,
        partNumber;

    if (typeof given_partNumber_package === 'undefined') {
        partNumber_package = NUTOOL_PIN.getg_partNumber_package();
    }
    else {
        partNumber_package = given_partNumber_package;
    }

    NUTOOL_PIN.g_packageNumber = partNumber_package.substring(partNumber_package.indexOf('(') + 1);
    NUTOOL_PIN.g_packageNumber = NUTOOL_PIN.g_packageNumber.substring(0, NUTOOL_PIN.g_packageNumber.indexOf(')'));

    partNumber = partNumber_package.substring(0, partNumber_package.indexOf('('));
    switch (NUTOOL_PIN.g_packageNumber) {
        case 'LQFP128':
            NUTOOL_PIN.g_packageNumberIndex = "LQFP128(14*14)";
            break;
        case 'LQFP216':
            NUTOOL_PIN.g_packageNumberIndex = "LQFP216(24*24)";
            break;
        default:
            break;
    }
    partNumber_package = null;
    partNumber = null;
};
