NUTOOL_PIN.g_cfg_chips = [
    { name: "M2A23YG5AC", pkg: "QFN48" },
    { name: "M2A23YE5AC", pkg: "QFN48" },
    { name: "M2A23LG5AC", pkg: "LQFP48" },
    { name: "M2A23LE5AC", pkg: "LQFP48" },
    { name: "M2A23SG5AC", pkg: "LQFP64" },
    { name: "M2A23SE5AC", pkg: "LQFP64" },
    { name: "M2A23NG5ACU", pkg: "QFN48" },
    { name: "M2A23NE5ACU", pkg: "QFN48" },
    { name: "M2A23LG5ACU", pkg: "LQFP48" },
    { name: "M2A23LE5ACU", pkg: "LQFP48" },
    { name: "M2A23SG5ACU", pkg: "LQFP64" },
    { name: "M2A23SE5ACU", pkg: "LQFP64" }
];

NUTOOL_PIN.g_cfg_pkgs = {
    "QFN48(5*5)(PIN:D10R14U10L14)": [
        'PB.5', 'PB.4', 'PB.3', 'PB.2', 'PB.1', 'PB.0', 'PA.11', 'PA.10', 'PA.9', 'PA.8', 
        'PF.5', 'PF.4', 'PF.3', 'PF.2', 'PA.7', 'PA.6', 'PA.5', 'PA.4', 'PA.3', 'PA.2', 
        'PA.1', 'PA.0', 'PF.15', 'nRESET', 'PF.0', 'PF.1', 'PC.5', 'PC.4', 'PC.3', 'PC.2', 
        'PC.1', 'PC.0', 'PA.12', 'PA.13', 'PA.14', 'PA.15', 'VSS', 'LDO_CAP', 'VDD', 'PC.14', 
        'PB.15', 'PB.14', 'PB.13', 'PB.12', 'AVDD', 'AVSS', 'PB.7', 'PB.6', 'VSS'
    ],
    "QFN48(7*7)": [
        'PB.5', 'PB.4', 'PB.3', 'PB.2', 'PB.1', 'PB.0', 'PA.11', 'PA.10', 'PA.9', 'PA.8', 
        'PF.5', 'PF.4', 'PF.3', 'PF.2', 'PA.7', 'PA.6', 'PA.5', 'PA.4', 'PA.3', 'PA.2', 
        'PA.1', 'PA.0', 'PF.15', 'nRESET', 'PF.0', 'PF.1', 'PC.5', 'PC.4', 'PC.3', 'PC.2', 
        'PC.1', 'PC.0', 'PA.12', 'PA.13', 'PA.14', 'PA.15', 'VSS', 'LDO_CAP', 'VDD', 'PC.14', 
        'PB.15', 'PB.14', 'PB.13', 'PB.12', 'AVDD', 'AVSS', 'PB.7', 'PB.6', 'VSS'
    ],
    "LQFP48": [
        'PB.5', 'PB.4', 'PB.3', 'PB.2', 'PB.1', 'PB.0', 'PA.11', 'PA.10', 'PA.9', 'PA.8', 
        'PF.5', 'PF.4', 'PF.3', 'PF.2', 'PA.7', 'PA.6', 'PA.5', 'PA.4', 'PA.3', 'PA.2', 
        'PA.1', 'PA.0', 'PF.15', 'nRESET', 'PF.0', 'PF.1', 'PC.5', 'PC.4', 'PC.3', 'PC.2', 
        'PC.1', 'PC.0', 'PA.12', 'PA.13', 'PA.14', 'PA.15', 'VSS', 'LDO_CAP', 'VDD', 'PC.14', 
        'PB.15', 'PB.14', 'PB.13', 'PB.12', 'AVDD', 'AVSS', 'PB.7', 'PB.6'
    ],
    "LQFP64": [
        'PB.6', 'PB.5', 'PB.4', 'PB.3', 'PB.2', 'PB.1', 'PB.0', 'PA.11', 'PA.10', 'PA.9', 
        'PA.8', 'PF.6', 'PF.14', 'PF.5', 'PF.4', 'PF.3', 'PF.2', 'PC.7', 'PC.6', 'PA.7', 
        'PA.6', 'VSS', 'VDD', 'PD.15', 'PA.5', 'PA.4', 'PA.3', 'PA.2', 'PA.1', 'PA.0', 
        'PF.15', 'nRESET', 'PF.0', 'PF.1', 'PC.5', 'PC.4', 'PC.3', 'PC.2', 'PC.1', 'PC.0', 
        'PD.3', 'PD.2', 'PD.1', 'PD.0', 'PA.12', 'PA.13', 'PA.14', 'PA.15', 'VSS', 'LDO_CAP', 
        'VDD', 'PC.14', 'PB.15', 'PB.14', 'PB.13', 'PB.12', 'AVDD', 'VREF', 'AVSS', 'PB.11', 
        'PB.10', 'PB.9', 'PB.8', 'PB.7'
    ]
};

NUTOOL_PIN.g_cfg_gpios = [
    { f: ['PA.0:0', 'UART1_nRTS:2', 'UART0_RXD:3', 'SPI0_MOSI:4', 'LLSI1_OUT:7', 'CANFD1_RXD:9', 'PWM0_CH5:11', 'BPWM0_CH0:12']},
    { f: ['PA.1:0', 'UART1_nCTS:2', 'UART0_TXD:3', 'SPI0_MISO:4', 'LLSI0_OUT:7', 'CANFD1_TXD:9', 'CANFD1_TXH:10', 'PWM0_CH4:11', 'BPWM0_CH1:12']},
    { f: ['PA.2:0', 'UART1_RXD:2', 'SPI0_CLK:4', 'I2C0_SMBSUS:6', 'CANFD1_RXD:9', 'PWM0_CH3:11', 'BPWM0_CH2:12', 'CANFD1_TXL:13']},
    { f: ['PA.3:0', 'UART1_TXD:2', 'SPI0_SS:4', 'I2C0_SMBAL:6', 'CANFD0_RXD:9', 'PWM0_CH2:11', 'BPWM0_CH3:12', 'CLKO:15']},
    { f: ['PA.4:0', 'UART0_nRTS:2', 'UART0_RXD:3', 'I2C0_SDA:6', 'CANFD0_TXD:9', 'CANFD0_TXH:10', 'PWM0_CH1:11', 'BPWM0_CH4:12', 'CANFD1_TXL:13']},
    { f: ['PA.5:0', 'UART0_nCTS:2', 'UART0_TXD:3', 'I2C0_SCL:6', 'PWM0_CH0:11', 'BPWM0_CH5:12']},
    { f: ['PA.6:0', 'UART0_RXD:2', 'ACMP1_WLAT:13', 'TM3:14', 'INT0:15']},
    { f: ['PA.7:0', 'UART0_TXD:2', 'ACMP0_WLAT:13', 'TM2:14', 'INT1:15']},
    { f: ['PA.8:0', 'UART1_RXD:2', 'USCI0_CTL1:8', 'CANFD1_RXD:9', 'BPWM0_CH3:12', 'TM3_EXT:14', 'INT4:15']},
    { f: ['PA.9:0', 'UART1_TXD:2', 'USCI0_DAT1:8', 'CANFD1_TXD:9', 'CANFD1_TXH:10', 'BPWM0_CH2:12', 'TM2_EXT:14']},
    { f: ['PA.10:0', 'ACMP1_P0:1', 'LLSI1_OUT:7', 'USCI0_DAT0:8', 'CANFD1_TXL:10', 'BPWM0_CH1:12', 'TM1_EXT:14']},
    { f: ['PA.11:0', 'ACMP0_P0:1', 'LLSI0_OUT:7', 'USCI0_CLK:8', 'BPWM0_CH0:12', 'TM0_EXT:14']},
    { f: ['PA.12:0', 'SPI0_SS:4', 'I2C0_SMBAL:6', 'CANFD1_RXD:9', 'CANFD1_TXH:10']},
    { f: ['PA.13:0', 'SPI0_CLK:4', 'I2C0_SMBSUS:6', 'CANFD1_TXD:9', 'CANFD0_TXL:11']},
    { f: ['PA.14:0', 'UART0_TXD:2', 'SPI0_MISO:4', 'LLSI0_OUT:7', 'CANFD0_TXD:9', 'CANFD0_TXH:10', 'ACMP0_WLAT:13']},
    { f: ['PA.15:0', 'UART0_RXD:2', 'SPI0_MOSI:4', 'LLSI1_OUT:7', 'CANFD0_RXD:9', 'CANFD2_TXL:11', 'ACMP1_WLAT:13']},

    { f: ['PB.0:0', 'ADC0_CH0:1', 'USCI0_CTL0:8', 'CANFD0_RXD:9', 'PWM0_CH5:11', 'PWM0_BRAKE1:12', 'CANFD0_TXL:13']},
    { f: ['PB.1:0', 'ADC0_CH1:1', 'USCI1_CLK:8', 'CANFD0_TXD:9', 'CANFD0_TXH:10', 'PWM0_CH4:11', 'PWM0_BRAKE0:12']},
    { f: ['PB.2:0', 'ADC0_CH2:1', 'ACMP0_P1:1', 'UART1_RXD:2', 'I2C0_SMBSUS:6', 'USCI1_DAT0:8', 'CANFD1_RXD:9', 'PWM0_CH3:11', 'TM3:14', 'INT3:15']},
    { f: ['PB.3:0', 'ADC0_CH3:1', 'ACMP0_N:1', 'UART1_TXD:2', 'I2C0_SMBAL:6', 'USCI1_DAT1:8', 'CANFD1_TXD:9', 'CANFD1_TXH:10', 'PWM0_CH2:11', 'CANFD1_TXL:13', 'TM2:14', 'INT2:15']},
    { f: ['PB.4:0', 'ADC0_CH4:1', 'ACMP1_P1:1', 'I2C0_SDA:6', 'USCI1_CTL1:8', 'CANFD0_RXD:9', 'PWM0_CH1:11', 'TM1:14', 'INT1:15']},
    { f: ['PB.5:0', 'ADC0_CH5:1', 'ACMP1_N:1', 'I2C0_SCL:6', 'USCI1_CTL0:8', 'CANFD0_TXD:9', 'CANFD0_TXH:10', 'PWM0_CH0:11', 'TM0:14', 'INT0:15']},
    { f: ['PB.6:0', 'ADC0_CH6:1', 'UART1_RXD:3', 'USCI1_DAT1:8', 'CANFD1_RXD:9', 'CANFD0_TXL:11', 'ACMP1_O:13', 'INT4:14']},
    { f: ['PB.7:0', 'ADC0_CH7:1', 'UART1_TXD:3', 'USCI1_DAT0:8', 'CANFD1_TXD:9', 'CANFD1_TXH:10', 'ACMP0_O:13', 'INT5:14']},
    { f: ['PB.8:0', 'ADC0_CH8:1', 'UART0_RXD:2', 'UART1_nRTS:3', 'USCI1_CLK:8', 'CANFD2_RXD:9', 'CANFD1_TXL:11']},
    { f: ['PB.9:0', 'ADC0_CH9:1', 'UART0_TXD:2', 'UART1_nCTS:3', 'USCI1_CTL1:8', 'CANFD2_TXD:9', 'CANFD2_TXH:10']},
    { f: ['PB.10:0', 'ADC0_CH10:1', 'UART0_nRTS:2', 'USCI1_CTL0:8', 'CANFD0_RXD:9', 'CANFD2_TXL:11']},
    { f: ['PB.11:0', 'ADC0_CH11:1', 'UART0_nCTS:2', 'CANFD0_TXD:9', 'CANFD0_TXH:10']},
    { f: ['PB.12:0', 'ADC0_CH12:1', 'ACMP0_P2:1', 'ACMP1_P2:1', 'UART0_RXD:2', 'SPI0_MOSI:4', 'I2C0_SDA:6', 'USCI0_CLK:8', 'CANFD0_RXD:9', 'TM3_EXT:14']},
    { f: ['PB.13:0', 'ADC0_CH13:1', 'ACMP0_P3:1', 'ACMP1_P3:1', 'UART0_TXD:2', 'SPI0_MISO:4', 'I2C0_SCL:6', 'USCI0_DAT0:8', 'CANFD0_TXD:9', 'CANFD0_TXH:10', 'TM2_EXT:14']},
    { f: ['PB.14:0', 'ADC0_CH14:1', 'UART0_nRTS:2', 'SPI0_CLK:4', 'LLSI1_OUT:7', 'USCI0_DAT1:8', 'CANFD2_RXD:9', 'CANFD0_TXL:11', 'TM1_EXT:14', 'CLKO:15']},
    { f: ['PB.15:0', 'ADC0_CH15:1', 'UART0_nCTS:2', 'SPI0_SS:4', 'LLSI0_OUT:7', 'USCI0_CTL1:8', 'CANFD2_TXD:9', 'CANFD2_TXH:10', 'TM0_EXT:14']},

    { f: ['PC.0:0', 'I2C0_SDA:6', 'USCI0_CTL0:8', 'CANFD2_RXD:9', 'ACMP1_O:13']},
    { f: ['PC.1:0', 'I2C0_SCL:6', 'CANFD2_TXD:9', 'CANFD2_TXH:10', 'ACMP0_O:13', 'ADC0_ST:15']},
    { f: ['PC.2:0', 'I2C0_SMBSUS:6', 'CANFD2_TXL:11']},
    { f: ['PC.3:0', 'I2C0_SMBAL:6', 'CANFD1_TXD:10']},
    { f: ['PC.4:0', 'LLSI1_OUT:7', 'CANFD0_RXD:9', 'CANFD1_RXD:10']},
    { f: ['PC.5:0', 'LLSI0_OUT:7', 'CANFD0_TXD:9']},
    { f: ['PC.6:0', 'UART0_nRTS:2', 'LLSI1_OUT:7', 'TM1:14', 'INT2:15']},
    { f: ['PC.7:0', 'UART0_nCTS:2', 'LLSI0_OUT:7', 'TM0:14', 'INT3:15']},
    { f: ['PC.8:0']},
    { f: ['PC.9:0']},
    { f: ['PC.10:0']},
    { f: ['PC.11:0']},
    { f: ['PC.12:0']},
    { f: ['PC.13:0']},
    { f: ['PC.14:0', 'USCI0_CTL0:8', 'CANFD0_TXL:11', 'TM1:14']},
    { f: ['PC.15:0']},

    { f: ['PD.0:0', 'SPI0_MOSI:4', 'USCI0_CLK:8', 'CANFD1_TXL:11', 'TM2:14']},
    { f: ['PD.1:0', 'SPI0_MISO:4', 'USCI0_DAT0:8']},
    { f: ['PD.2:0', 'UART0_RXD:2', 'SPI0_CLK:4', 'USCI0_DAT1:8']},
    { f: ['PD.3:0', 'UART0_TXD:2', 'SPI0_SS:4', 'USCI0_CTL1:8']},
    { f: ['PD.4:0']},
    { f: ['PD.5:0']},
    { f: ['PD.6:0']},
    { f: ['PD.7:0']},
    { f: ['PD.8:0']},
    { f: ['PD.9:0']},
    { f: ['PD.10:0']},
    { f: ['PD.11:0']},
    { f: ['PD.12:0']},
    { f: ['PD.13:0']},
    { f: ['PD.14:0']},
    { f: ['PD.15:0', 'CANFD0_TXL:11', 'TM3:14', 'INT1:15']},

    { f: ['PE.0:0']},
    { f: ['PE.1:0']},
    { f: ['PE.2:0']},
    { f: ['PE.3:0']},
    { f: ['PE.4:0']},
    { f: ['PE.5:0']},
    { f: ['PE.6:0']},
    { f: ['PE.7:0']},
    { f: ['PE.8:0']},
    { f: ['PE.9:0']},
    { f: ['PE.10:0']},
    { f: ['PE.11:0']},
    { f: ['PE.12:0']},
    { f: ['PE.13:0']},
    { f: ['PE.14:0']},
    { f: ['PE.15:0']},

    { f: ['PF.0:0', 'UART1_TXD:2', 'UART0_TXD:3', 'CANFD2_TXD:9', 'CANFD2_TXH:10', 'ICE_DAT:14']},
    { f: ['PF.1:0', 'UART1_RXD:2', 'UART0_RXD:3', 'CANFD2_RXD:9', 'ICE_CLK:14']},
    { f: ['PF.2:0', 'UART0_RXD:2', 'XT1_OUT:3', 'I2C0_SDA:6', 'CANFD0_RXD:9']},
    { f: ['PF.3:0', 'UART0_TXD:2', 'XT1_IN:3', 'I2C0_SCL:6', 'CANFD0_TXD:9', 'CANFD0_TXH:10']},
    { f: ['PF.4:0', 'X32_OUT:3', 'LLSI1_OUT:7', 'CANFD0_TXL:10', 'PWM0_CH1:11', 'BPWM0_CH5:12']},
    { f: ['PF.5:0', 'X32_IN:3', 'LLSI0_OUT:7', 'PWM0_CH0:11', 'BPWM0_CH4:12', 'ADC0_ST:15']},
    { f: ['PF.6:0', 'SPI0_MOSI:4', 'CLKO:15']},
    { f: ['PF.7:0']},
    { f: ['PF.8:0']},
    { f: ['PF.9:0']},
    { f: ['PF.10:0']},
    { f: ['PF.11:0']},
    { f: ['PF.12:0']},
    { f: ['PF.13:0']},
    { f: ['PF.14:0', 'TM3:14', 'CLKO:15']},
    { f: ['PF.15:0', 'CANFD2_TXL:11', 'CLKO:14', 'INT4:15']}
];

NUTOOL_PIN.g_cfg_gpiosDefines = [
    { f: ['PA.0', 'GPIO:SYS_GPA_MFPL_PA0MFP_GPIO@GPA_MFPL', 'UART1_nRTS:SYS_GPA_MFPL_PA0MFP_UART1_nRTS@GPA_MFPL', 'UART0_RXD:SYS_GPA_MFPL_PA0MFP_UART0_RXD@GPA_MFPL', 'SPI0_MOSI:SYS_GPA_MFPL_PA0MFP_SPI0_MOSI@GPA_MFPL', 'LLSI1_OUT:SYS_GPA_MFPL_PA0MFP_LLSI1_OUT@GPA_MFPL', 'CANFD1_RXD:SYS_GPA_MFPL_PA0MFP_CANFD1_RXD@GPA_MFPL', 'PWM0_CH5:SYS_GPA_MFPL_PA0MFP_PWM0_CH5@GPA_MFPL', 'BPWM0_CH0:SYS_GPA_MFPL_PA0MFP_BPWM0_CH0@GPA_MFPL'] },
    { f: ['PA.1', 'GPIO:SYS_GPA_MFPL_PA1MFP_GPIO@GPA_MFPL', 'UART1_nCTS:SYS_GPA_MFPL_PA1MFP_UART1_nCTS@GPA_MFPL', 'UART0_TXD:SYS_GPA_MFPL_PA1MFP_UART0_TXD@GPA_MFPL', 'SPI0_MISO:SYS_GPA_MFPL_PA1MFP_SPI0_MISO@GPA_MFPL', 'LLSI0_OUT:SYS_GPA_MFPL_PA1MFP_LLSI0_OUT@GPA_MFPL', 'CANFD1_TXD:SYS_GPA_MFPL_PA1MFP_CANFD1_TXD@GPA_MFPL', 'CANFD1_TXH:SYS_GPA_MFPL_PA1MFP_CANFD1_TXH@GPA_MFPL', 'PWM0_CH4:SYS_GPA_MFPL_PA1MFP_PWM0_CH4@GPA_MFPL', 'BPWM0_CH1:SYS_GPA_MFPL_PA1MFP_BPWM0_CH1@GPA_MFPL'] },
    { f: ['PA.2', 'GPIO:SYS_GPA_MFPL_PA2MFP_GPIO@GPA_MFPL', 'UART1_RXD:SYS_GPA_MFPL_PA2MFP_UART1_RXD@GPA_MFPL', 'SPI0_CLK:SYS_GPA_MFPL_PA2MFP_SPI0_CLK@GPA_MFPL', 'I2C0_SMBSUS:SYS_GPA_MFPL_PA2MFP_I2C0_SMBSUS@GPA_MFPL', 'CANFD1_RXD:SYS_GPA_MFPL_PA2MFP_CANFD1_RXD@GPA_MFPL', 'PWM0_CH3:SYS_GPA_MFPL_PA2MFP_PWM0_CH3@GPA_MFPL', 'BPWM0_CH2:SYS_GPA_MFPL_PA2MFP_BPWM0_CH2@GPA_MFPL', 'CANFD1_TXL:SYS_GPA_MFPL_PA2MFP_CANFD1_TXL@GPA_MFPL'] },
    { f: ['PA.3', 'GPIO:SYS_GPA_MFPL_PA3MFP_GPIO@GPA_MFPL', 'UART1_TXD:SYS_GPA_MFPL_PA3MFP_UART1_TXD@GPA_MFPL', 'SPI0_SS:SYS_GPA_MFPL_PA3MFP_SPI0_SS@GPA_MFPL', 'I2C0_SMBAL:SYS_GPA_MFPL_PA3MFP_I2C0_SMBAL@GPA_MFPL', 'CANFD0_RXD:SYS_GPA_MFPL_PA3MFP_CANFD0_RXD@GPA_MFPL', 'PWM0_CH2:SYS_GPA_MFPL_PA3MFP_PWM0_CH2@GPA_MFPL', 'BPWM0_CH3:SYS_GPA_MFPL_PA3MFP_BPWM0_CH3@GPA_MFPL', 'CLKO:SYS_GPA_MFPL_PA3MFP_CLKO@GPA_MFPL'] },
    { f: ['PA.4', 'GPIO:SYS_GPA_MFPL_PA4MFP_GPIO@GPA_MFPL', 'UART0_nRTS:SYS_GPA_MFPL_PA4MFP_UART0_nRTS@GPA_MFPL', 'UART0_RXD:SYS_GPA_MFPL_PA4MFP_UART0_RXD@GPA_MFPL', 'I2C0_SDA:SYS_GPA_MFPL_PA4MFP_I2C0_SDA@GPA_MFPL', 'CANFD0_TXD:SYS_GPA_MFPL_PA4MFP_CANFD0_TXD@GPA_MFPL', 'CANFD0_TXH:SYS_GPA_MFPL_PA4MFP_CANFD0_TXH@GPA_MFPL', 'PWM0_CH1:SYS_GPA_MFPL_PA4MFP_PWM0_CH1@GPA_MFPL', 'BPWM0_CH4:SYS_GPA_MFPL_PA4MFP_BPWM0_CH4@GPA_MFPL', 'CANFD1_TXL:SYS_GPA_MFPL_PA4MFP_CANFD1_TXL@GPA_MFPL'] },
    { f: ['PA.5', 'GPIO:SYS_GPA_MFPL_PA5MFP_GPIO@GPA_MFPL', 'UART0_nCTS:SYS_GPA_MFPL_PA5MFP_UART0_nCTS@GPA_MFPL', 'UART0_TXD:SYS_GPA_MFPL_PA5MFP_UART0_TXD@GPA_MFPL', 'I2C0_SCL:SYS_GPA_MFPL_PA5MFP_I2C0_SCL@GPA_MFPL', 'PWM0_CH0:SYS_GPA_MFPL_PA5MFP_PWM0_CH0@GPA_MFPL', 'BPWM0_CH5:SYS_GPA_MFPL_PA5MFP_BPWM0_CH5@GPA_MFPL'] },
    { f: ['PA.6', 'GPIO:SYS_GPA_MFPL_PA6MFP_GPIO@GPA_MFPL', 'UART0_RXD:SYS_GPA_MFPL_PA6MFP_UART0_RXD@GPA_MFPL', 'ACMP1_WLAT:SYS_GPA_MFPL_PA6MFP_ACMP1_WLAT@GPA_MFPL', 'TM3:SYS_GPA_MFPL_PA6MFP_TM3@GPA_MFPL', 'INT0:SYS_GPA_MFPL_PA6MFP_INT0@GPA_MFPL'] },
    { f: ['PA.7', 'GPIO:SYS_GPA_MFPL_PA7MFP_GPIO@GPA_MFPL', 'UART0_TXD:SYS_GPA_MFPL_PA7MFP_UART0_TXD@GPA_MFPL', 'ACMP0_WLAT:SYS_GPA_MFPL_PA7MFP_ACMP0_WLAT@GPA_MFPL', 'TM2:SYS_GPA_MFPL_PA7MFP_TM2@GPA_MFPL', 'INT1:SYS_GPA_MFPL_PA7MFP_INT1@GPA_MFPL'] },
    { f: ['PA.8', 'GPIO:SYS_GPA_MFPH_PA8MFP_GPIO@GPA_MFPH', 'UART1_RXD:SYS_GPA_MFPH_PA8MFP_UART1_RXD@GPA_MFPH', 'USCI0_CTL1:SYS_GPA_MFPH_PA8MFP_USCI0_CTL1@GPA_MFPH', 'CANFD1_RXD:SYS_GPA_MFPH_PA8MFP_CANFD1_RXD@GPA_MFPH', 'BPWM0_CH3:SYS_GPA_MFPH_PA8MFP_BPWM0_CH3@GPA_MFPH', 'TM3_EXT:SYS_GPA_MFPH_PA8MFP_TM3_EXT@GPA_MFPH', 'INT4:SYS_GPA_MFPH_PA8MFP_INT4@GPA_MFPH'] },
    { f: ['PA.9', 'GPIO:SYS_GPA_MFPH_PA9MFP_GPIO@GPA_MFPH', 'UART1_TXD:SYS_GPA_MFPH_PA9MFP_UART1_TXD@GPA_MFPH', 'USCI0_DAT1:SYS_GPA_MFPH_PA9MFP_USCI0_DAT1@GPA_MFPH', 'CANFD1_TXD:SYS_GPA_MFPH_PA9MFP_CANFD1_TXD@GPA_MFPH', 'CANFD1_TXH:SYS_GPA_MFPH_PA9MFP_CANFD1_TXH@GPA_MFPH', 'BPWM0_CH2:SYS_GPA_MFPH_PA9MFP_BPWM0_CH2@GPA_MFPH', 'TM2_EXT:SYS_GPA_MFPH_PA9MFP_TM2_EXT@GPA_MFPH'] },
    { f: ['PA.10', 'GPIO:SYS_GPA_MFPH_PA10MFP_GPIO@GPA_MFPH', 'ACMP1_P0:SYS_GPA_MFPH_PA10MFP_ACMP1_P0@GPA_MFPH', 'LLSI1_OUT:SYS_GPA_MFPH_PA10MFP_LLSI1_OUT@GPA_MFPH', 'USCI0_DAT0:SYS_GPA_MFPH_PA10MFP_USCI0_DAT0@GPA_MFPH', 'CANFD1_TXL:SYS_GPA_MFPH_PA10MFP_CANFD1_TXL@GPA_MFPH', 'BPWM0_CH1:SYS_GPA_MFPH_PA10MFP_BPWM0_CH1@GPA_MFPH', 'TM1_EXT:SYS_GPA_MFPH_PA10MFP_TM1_EXT@GPA_MFPH'] },
    { f: ['PA.11', 'GPIO:SYS_GPA_MFPH_PA11MFP_GPIO@GPA_MFPH', 'ACMP0_P0:SYS_GPA_MFPH_PA11MFP_ACMP0_P0@GPA_MFPH', 'LLSI0_OUT:SYS_GPA_MFPH_PA11MFP_LLSI0_OUT@GPA_MFPH', 'USCI0_CLK:SYS_GPA_MFPH_PA11MFP_USCI0_CLK@GPA_MFPH', 'BPWM0_CH0:SYS_GPA_MFPH_PA11MFP_BPWM0_CH0@GPA_MFPH', 'TM0_EXT:SYS_GPA_MFPH_PA11MFP_TM0_EXT@GPA_MFPH'] },
    { f: ['PA.12', 'GPIO:SYS_GPA_MFPH_PA12MFP_GPIO@GPA_MFPH', 'SPI0_SS:SYS_GPA_MFPH_PA12MFP_SPI0_SS@GPA_MFPH', 'I2C0_SMBAL:SYS_GPA_MFPH_PA12MFP_I2C0_SMBAL@GPA_MFPH', 'CANFD1_RXD:SYS_GPA_MFPH_PA12MFP_CANFD1_RXD@GPA_MFPH', 'CANFD1_TXH:SYS_GPA_MFPH_PA12MFP_CANFD1_TXH@GPA_MFPH'] },
    { f: ['PA.13', 'GPIO:SYS_GPA_MFPH_PA13MFP_GPIO@GPA_MFPH', 'SPI0_CLK:SYS_GPA_MFPH_PA13MFP_SPI0_CLK@GPA_MFPH', 'I2C0_SMBSUS:SYS_GPA_MFPH_PA13MFP_I2C0_SMBSUS@GPA_MFPH', 'CANFD1_TXD:SYS_GPA_MFPH_PA13MFP_CANFD1_TXD@GPA_MFPH', 'CANFD0_TXL:SYS_GPA_MFPH_PA13MFP_CANFD0_TXL@GPA_MFPH'] },
    { f: ['PA.14', 'GPIO:SYS_GPA_MFPH_PA14MFP_GPIO@GPA_MFPH', 'UART0_TXD:SYS_GPA_MFPH_PA14MFP_UART0_TXD@GPA_MFPH', 'SPI0_MISO:SYS_GPA_MFPH_PA14MFP_SPI0_MISO@GPA_MFPH', 'LLSI0_OUT:SYS_GPA_MFPH_PA14MFP_LLSI0_OUT@GPA_MFPH', 'CANFD0_TXD:SYS_GPA_MFPH_PA14MFP_CANFD0_TXD@GPA_MFPH', 'CANFD0_TXH:SYS_GPA_MFPH_PA14MFP_CANFD0_TXH@GPA_MFPH', 'ACMP0_WLAT:SYS_GPA_MFPH_PA14MFP_ACMP0_WLAT@GPA_MFPH'] },
    { f: ['PA.15', 'GPIO:SYS_GPA_MFPH_PA15MFP_GPIO@GPA_MFPH', 'UART0_RXD:SYS_GPA_MFPH_PA15MFP_UART0_RXD@GPA_MFPH', 'SPI0_MOSI:SYS_GPA_MFPH_PA15MFP_SPI0_MOSI@GPA_MFPH', 'LLSI1_OUT:SYS_GPA_MFPH_PA15MFP_LLSI1_OUT@GPA_MFPH', 'CANFD0_RXD:SYS_GPA_MFPH_PA15MFP_CANFD0_RXD@GPA_MFPH', 'CANFD2_TXL:SYS_GPA_MFPH_PA15MFP_CANFD2_TXL@GPA_MFPH', 'ACMP1_WLAT:SYS_GPA_MFPH_PA15MFP_ACMP1_WLAT@GPA_MFPH'] },
    { f: ['PB.0', 'GPIO:SYS_GPB_MFPL_PB0MFP_GPIO@GPB_MFPL', 'ADC0_CH0:SYS_GPB_MFPL_PB0MFP_ADC0_CH0@GPB_MFPL', 'USCI0_CTL0:SYS_GPB_MFPL_PB0MFP_USCI0_CTL0@GPB_MFPL', 'CANFD0_RXD:SYS_GPB_MFPL_PB0MFP_CANFD0_RXD@GPB_MFPL', 'PWM0_CH5:SYS_GPB_MFPL_PB0MFP_PWM0_CH5@GPB_MFPL', 'PWM0_BRAKE1:SYS_GPB_MFPL_PB0MFP_PWM0_BRAKE1@GPB_MFPL', 'CANFD0_TXL:SYS_GPB_MFPL_PB0MFP_CANFD0_TXL@GPB_MFPL'] },
    { f: ['PB.1', 'GPIO:SYS_GPB_MFPL_PB1MFP_GPIO@GPB_MFPL', 'ADC0_CH1:SYS_GPB_MFPL_PB1MFP_ADC0_CH1@GPB_MFPL', 'USCI1_CLK:SYS_GPB_MFPL_PB1MFP_USCI1_CLK@GPB_MFPL', 'CANFD0_TXD:SYS_GPB_MFPL_PB1MFP_CANFD0_TXD@GPB_MFPL', 'CANFD0_TXH:SYS_GPB_MFPL_PB1MFP_CANFD0_TXH@GPB_MFPL', 'PWM0_CH4:SYS_GPB_MFPL_PB1MFP_PWM0_CH4@GPB_MFPL', 'PWM0_BRAKE0:SYS_GPB_MFPL_PB1MFP_PWM0_BRAKE0@GPB_MFPL'] },
    { f: ['PB.2', 'GPIO:SYS_GPB_MFPL_PB2MFP_GPIO@GPB_MFPL', 'ADC0_CH2:SYS_GPB_MFPL_PB2MFP_ADC0_CH2@GPB_MFPL', 'ACMP0_P1:SYS_GPB_MFPL_PB2MFP_ACMP0_P1@GPB_MFPL', 'UART1_RXD:SYS_GPB_MFPL_PB2MFP_UART1_RXD@GPB_MFPL', 'I2C0_SMBSUS:SYS_GPB_MFPL_PB2MFP_I2C0_SMBSUS@GPB_MFPL', 'USCI1_DAT0:SYS_GPB_MFPL_PB2MFP_USCI1_DAT0@GPB_MFPL', 'CANFD1_RXD:SYS_GPB_MFPL_PB2MFP_CANFD1_RXD@GPB_MFPL', 'PWM0_CH3:SYS_GPB_MFPL_PB2MFP_PWM0_CH3@GPB_MFPL', 'TM3:SYS_GPB_MFPL_PB2MFP_TM3@GPB_MFPL', 'INT3:SYS_GPB_MFPL_PB2MFP_INT3@GPB_MFPL'] },
    { f: ['PB.3', 'GPIO:SYS_GPB_MFPL_PB3MFP_GPIO@GPB_MFPL', 'ADC0_CH3:SYS_GPB_MFPL_PB3MFP_ADC0_CH3@GPB_MFPL', 'ACMP0_N:SYS_GPB_MFPL_PB3MFP_ACMP0_N@GPB_MFPL', 'UART1_TXD:SYS_GPB_MFPL_PB3MFP_UART1_TXD@GPB_MFPL', 'I2C0_SMBAL:SYS_GPB_MFPL_PB3MFP_I2C0_SMBAL@GPB_MFPL', 'USCI1_DAT1:SYS_GPB_MFPL_PB3MFP_USCI1_DAT1@GPB_MFPL', 'CANFD1_TXD:SYS_GPB_MFPL_PB3MFP_CANFD1_TXD@GPB_MFPL', 'CANFD1_TXH:SYS_GPB_MFPL_PB3MFP_CANFD1_TXH@GPB_MFPL', 'PWM0_CH2:SYS_GPB_MFPL_PB3MFP_PWM0_CH2@GPB_MFPL', 'CANFD1_TXL:SYS_GPB_MFPL_PB3MFP_CANFD1_TXL@GPB_MFPL', 'TM2:SYS_GPB_MFPL_PB3MFP_TM2@GPB_MFPL', 'INT2:SYS_GPB_MFPL_PB3MFP_INT2@GPB_MFPL'] },
    { f: ['PB.4', 'GPIO:SYS_GPB_MFPL_PB4MFP_GPIO@GPB_MFPL', 'ADC0_CH4:SYS_GPB_MFPL_PB4MFP_ADC0_CH4@GPB_MFPL', 'ACMP1_P1:SYS_GPB_MFPL_PB4MFP_ACMP1_P1@GPB_MFPL', 'I2C0_SDA:SYS_GPB_MFPL_PB4MFP_I2C0_SDA@GPB_MFPL', 'USCI1_CTL1:SYS_GPB_MFPL_PB4MFP_USCI1_CTL1@GPB_MFPL', 'CANFD0_RXD:SYS_GPB_MFPL_PB4MFP_CANFD0_RXD@GPB_MFPL', 'PWM0_CH1:SYS_GPB_MFPL_PB4MFP_PWM0_CH1@GPB_MFPL', 'TM1:SYS_GPB_MFPL_PB4MFP_TM1@GPB_MFPL', 'INT1:SYS_GPB_MFPL_PB4MFP_INT1@GPB_MFPL'] },
    { f: ['PB.5', 'GPIO:SYS_GPB_MFPL_PB5MFP_GPIO@GPB_MFPL', 'ADC0_CH5:SYS_GPB_MFPL_PB5MFP_ADC0_CH5@GPB_MFPL', 'ACMP1_N:SYS_GPB_MFPL_PB5MFP_ACMP1_N@GPB_MFPL', 'I2C0_SCL:SYS_GPB_MFPL_PB5MFP_I2C0_SCL@GPB_MFPL', 'USCI1_CTL0:SYS_GPB_MFPL_PB5MFP_USCI1_CTL0@GPB_MFPL', 'CANFD0_TXD:SYS_GPB_MFPL_PB5MFP_CANFD0_TXD@GPB_MFPL', 'CANFD0_TXH:SYS_GPB_MFPL_PB5MFP_CANFD0_TXH@GPB_MFPL', 'PWM0_CH0:SYS_GPB_MFPL_PB5MFP_PWM0_CH0@GPB_MFPL', 'TM0:SYS_GPB_MFPL_PB5MFP_TM0@GPB_MFPL', 'INT0:SYS_GPB_MFPL_PB5MFP_INT0@GPB_MFPL'] },
    { f: ['PB.6', 'GPIO:SYS_GPB_MFPL_PB6MFP_GPIO@GPB_MFPL', 'ADC0_CH6:SYS_GPB_MFPL_PB6MFP_ADC0_CH6@GPB_MFPL', 'UART1_RXD:SYS_GPB_MFPL_PB6MFP_UART1_RXD@GPB_MFPL', 'USCI1_DAT1:SYS_GPB_MFPL_PB6MFP_USCI1_DAT1@GPB_MFPL', 'CANFD1_RXD:SYS_GPB_MFPL_PB6MFP_CANFD1_RXD@GPB_MFPL', 'CANFD0_TXL:SYS_GPB_MFPL_PB6MFP_CANFD0_TXL@GPB_MFPL', 'ACMP1_O:SYS_GPB_MFPL_PB6MFP_ACMP1_O@GPB_MFPL', 'INT4:SYS_GPB_MFPL_PB6MFP_INT4@GPB_MFPL'] },
    { f: ['PB.7', 'GPIO:SYS_GPB_MFPL_PB7MFP_GPIO@GPB_MFPL', 'ADC0_CH7:SYS_GPB_MFPL_PB7MFP_ADC0_CH7@GPB_MFPL', 'UART1_TXD:SYS_GPB_MFPL_PB7MFP_UART1_TXD@GPB_MFPL', 'USCI1_DAT0:SYS_GPB_MFPL_PB7MFP_USCI1_DAT0@GPB_MFPL', 'CANFD1_TXD:SYS_GPB_MFPL_PB7MFP_CANFD1_TXD@GPB_MFPL', 'CANFD1_TXH:SYS_GPB_MFPL_PB7MFP_CANFD1_TXH@GPB_MFPL', 'ACMP0_O:SYS_GPB_MFPL_PB7MFP_ACMP0_O@GPB_MFPL', 'INT5:SYS_GPB_MFPL_PB7MFP_INT5@GPB_MFPL'] },
    { f: ['PB.8', 'GPIO:SYS_GPB_MFPH_PB8MFP_GPIO@GPB_MFPH', 'ADC0_CH8:SYS_GPB_MFPH_PB8MFP_ADC0_CH8@GPB_MFPH', 'UART0_RXD:SYS_GPB_MFPH_PB8MFP_UART0_RXD@GPB_MFPH', 'UART1_nRTS:SYS_GPB_MFPH_PB8MFP_UART1_nRTS@GPB_MFPH', 'USCI1_CLK:SYS_GPB_MFPH_PB8MFP_USCI1_CLK@GPB_MFPH', 'CANFD2_RXD:SYS_GPB_MFPH_PB8MFP_CANFD2_RXD@GPB_MFPH', 'CANFD1_TXL:SYS_GPB_MFPH_PB8MFP_CANFD1_TXL@GPB_MFPH'] },
    { f: ['PB.9', 'GPIO:SYS_GPB_MFPH_PB9MFP_GPIO@GPB_MFPH', 'ADC0_CH9:SYS_GPB_MFPH_PB9MFP_ADC0_CH9@GPB_MFPH', 'UART0_TXD:SYS_GPB_MFPH_PB9MFP_UART0_TXD@GPB_MFPH', 'UART1_nCTS:SYS_GPB_MFPH_PB9MFP_UART1_nCTS@GPB_MFPH', 'USCI1_CTL1:SYS_GPB_MFPH_PB9MFP_USCI1_CTL1@GPB_MFPH', 'CANFD2_TXD:SYS_GPB_MFPH_PB9MFP_CANFD2_TXD@GPB_MFPH', 'CANFD2_TXH:SYS_GPB_MFPH_PB9MFP_CANFD2_TXH@GPB_MFPH'] },
    { f: ['PB.10', 'GPIO:SYS_GPB_MFPH_PB10MFP_GPIO@GPB_MFPH', 'ADC0_CH10:SYS_GPB_MFPH_PB10MFP_ADC0_CH10@GPB_MFPH', 'UART0_nRTS:SYS_GPB_MFPH_PB10MFP_UART0_nRTS@GPB_MFPH', 'USCI1_CTL0:SYS_GPB_MFPH_PB10MFP_USCI1_CTL0@GPB_MFPH', 'CANFD0_RXD:SYS_GPB_MFPH_PB10MFP_CANFD0_RXD@GPB_MFPH', 'CANFD2_TXL:SYS_GPB_MFPH_PB10MFP_CANFD2_TXL@GPB_MFPH'] },
    { f: ['PB.11', 'GPIO:SYS_GPB_MFPH_PB11MFP_GPIO@GPB_MFPH', 'ADC0_CH11:SYS_GPB_MFPH_PB11MFP_ADC0_CH11@GPB_MFPH', 'UART0_nCTS:SYS_GPB_MFPH_PB11MFP_UART0_nCTS@GPB_MFPH', 'CANFD0_TXD:SYS_GPB_MFPH_PB11MFP_CANFD0_TXD@GPB_MFPH', 'CANFD0_TXH:SYS_GPB_MFPH_PB11MFP_CANFD0_TXH@GPB_MFPH'] },
    { f: ['PB.12', 'GPIO:SYS_GPB_MFPH_PB12MFP_GPIO@GPB_MFPH', 'ADC0_CH12:SYS_GPB_MFPH_PB12MFP_ADC0_CH12@GPB_MFPH', 'ACMP0_P2:SYS_GPB_MFPH_PB12MFP_ACMP0_P2@GPB_MFPH', 'ACMP1_P2:SYS_GPB_MFPH_PB12MFP_ACMP1_P2@GPB_MFPH', 'UART0_RXD:SYS_GPB_MFPH_PB12MFP_UART0_RXD@GPB_MFPH', 'SPI0_MOSI:SYS_GPB_MFPH_PB12MFP_SPI0_MOSI@GPB_MFPH', 'I2C0_SDA:SYS_GPB_MFPH_PB12MFP_I2C0_SDA@GPB_MFPH', 'USCI0_CLK:SYS_GPB_MFPH_PB12MFP_USCI0_CLK@GPB_MFPH', 'CANFD0_RXD:SYS_GPB_MFPH_PB12MFP_CANFD0_RXD@GPB_MFPH', 'TM3_EXT:SYS_GPB_MFPH_PB12MFP_TM3_EXT@GPB_MFPH'] },
    { f: ['PB.13', 'GPIO:SYS_GPB_MFPH_PB13MFP_GPIO@GPB_MFPH', 'ADC0_CH13:SYS_GPB_MFPH_PB13MFP_ADC0_CH13@GPB_MFPH', 'ACMP0_P3:SYS_GPB_MFPH_PB13MFP_ACMP0_P3@GPB_MFPH', 'ACMP1_P3:SYS_GPB_MFPH_PB13MFP_ACMP1_P3@GPB_MFPH', 'UART0_TXD:SYS_GPB_MFPH_PB13MFP_UART0_TXD@GPB_MFPH', 'SPI0_MISO:SYS_GPB_MFPH_PB13MFP_SPI0_MISO@GPB_MFPH', 'I2C0_SCL:SYS_GPB_MFPH_PB13MFP_I2C0_SCL@GPB_MFPH', 'USCI0_DAT0:SYS_GPB_MFPH_PB13MFP_USCI0_DAT0@GPB_MFPH', 'CANFD0_TXD:SYS_GPB_MFPH_PB13MFP_CANFD0_TXD@GPB_MFPH', 'CANFD0_TXH:SYS_GPB_MFPH_PB13MFP_CANFD0_TXH@GPB_MFPH', 'TM2_EXT:SYS_GPB_MFPH_PB13MFP_TM2_EXT@GPB_MFPH'] },
    { f: ['PB.14', 'GPIO:SYS_GPB_MFPH_PB14MFP_GPIO@GPB_MFPH', 'ADC0_CH14:SYS_GPB_MFPH_PB14MFP_ADC0_CH14@GPB_MFPH', 'UART0_nRTS:SYS_GPB_MFPH_PB14MFP_UART0_nRTS@GPB_MFPH', 'SPI0_CLK:SYS_GPB_MFPH_PB14MFP_SPI0_CLK@GPB_MFPH', 'LLSI1_OUT:SYS_GPB_MFPH_PB14MFP_LLSI1_OUT@GPB_MFPH', 'USCI0_DAT1:SYS_GPB_MFPH_PB14MFP_USCI0_DAT1@GPB_MFPH', 'CANFD2_RXD:SYS_GPB_MFPH_PB14MFP_CANFD2_RXD@GPB_MFPH', 'CANFD0_TXL:SYS_GPB_MFPH_PB14MFP_CANFD0_TXL@GPB_MFPH', 'TM1_EXT:SYS_GPB_MFPH_PB14MFP_TM1_EXT@GPB_MFPH', 'CLKO:SYS_GPB_MFPH_PB14MFP_CLKO@GPB_MFPH'] },
    { f: ['PB.15', 'GPIO:SYS_GPB_MFPH_PB15MFP_GPIO@GPB_MFPH', 'ADC0_CH15:SYS_GPB_MFPH_PB15MFP_ADC0_CH15@GPB_MFPH', 'UART0_nCTS:SYS_GPB_MFPH_PB15MFP_UART0_nCTS@GPB_MFPH', 'SPI0_SS:SYS_GPB_MFPH_PB15MFP_SPI0_SS@GPB_MFPH', 'LLSI0_OUT:SYS_GPB_MFPH_PB15MFP_LLSI0_OUT@GPB_MFPH', 'USCI0_CTL1:SYS_GPB_MFPH_PB15MFP_USCI0_CTL1@GPB_MFPH', 'CANFD2_TXD:SYS_GPB_MFPH_PB15MFP_CANFD2_TXD@GPB_MFPH', 'CANFD2_TXH:SYS_GPB_MFPH_PB15MFP_CANFD2_TXH@GPB_MFPH', 'TM0_EXT:SYS_GPB_MFPH_PB15MFP_TM0_EXT@GPB_MFPH'] },
    { f: ['PC.0', 'GPIO:SYS_GPC_MFPL_PC0MFP_GPIO@GPC_MFPL', 'I2C0_SDA:SYS_GPC_MFPL_PC0MFP_I2C0_SDA@GPC_MFPL', 'USCI0_CTL0:SYS_GPC_MFPL_PC0MFP_USCI0_CTL0@GPC_MFPL', 'CANFD2_RXD:SYS_GPC_MFPL_PC0MFP_CANFD2_RXD@GPC_MFPL', 'ACMP1_O:SYS_GPC_MFPL_PC0MFP_ACMP1_O@GPC_MFPL'] },
    { f: ['PC.1', 'GPIO:SYS_GPC_MFPL_PC1MFP_GPIO@GPC_MFPL', 'I2C0_SCL:SYS_GPC_MFPL_PC1MFP_I2C0_SCL@GPC_MFPL', 'CANFD2_TXD:SYS_GPC_MFPL_PC1MFP_CANFD2_TXD@GPC_MFPL', 'CANFD2_TXH:SYS_GPC_MFPL_PC1MFP_CANFD2_TXH@GPC_MFPL', 'ACMP0_O:SYS_GPC_MFPL_PC1MFP_ACMP0_O@GPC_MFPL', 'ADC0_ST:SYS_GPC_MFPL_PC1MFP_ADC0_ST@GPC_MFPL'] },
    { f: ['PC.2', 'GPIO:SYS_GPC_MFPL_PC2MFP_GPIO@GPC_MFPL', 'I2C0_SMBSUS:SYS_GPC_MFPL_PC2MFP_I2C0_SMBSUS@GPC_MFPL', 'CANFD2_TXL:SYS_GPC_MFPL_PC2MFP_CANFD2_TXL@GPC_MFPL'] },
    { f: ['PC.3', 'GPIO:SYS_GPC_MFPL_PC3MFP_GPIO@GPC_MFPL', 'I2C0_SMBAL:SYS_GPC_MFPL_PC3MFP_I2C0_SMBAL@GPC_MFPL', 'CANFD1_TXD:SYS_GPC_MFPL_PC3MFP_CANFD1_TXD@GPC_MFPL'] },
    { f: ['PC.4', 'GPIO:SYS_GPC_MFPL_PC4MFP_GPIO@GPC_MFPL', 'LLSI1_OUT:SYS_GPC_MFPL_PC4MFP_LLSI1_OUT@GPC_MFPL', 'CANFD0_RXD:SYS_GPC_MFPL_PC4MFP_CANFD0_RXD@GPC_MFPL', 'CANFD1_RXD:SYS_GPC_MFPL_PC4MFP_CANFD1_RXD@GPC_MFPL'] },
    { f: ['PC.5', 'GPIO:SYS_GPC_MFPL_PC5MFP_GPIO@GPC_MFPL', 'LLSI0_OUT:SYS_GPC_MFPL_PC5MFP_LLSI0_OUT@GPC_MFPL', 'CANFD0_TXD:SYS_GPC_MFPL_PC5MFP_CANFD0_TXD@GPC_MFPL'] },
    { f: ['PC.6', 'GPIO:SYS_GPC_MFPL_PC6MFP_GPIO@GPC_MFPL', 'UART0_nRTS:SYS_GPC_MFPL_PC6MFP_UART0_nRTS@GPC_MFPL', 'LLSI1_OUT:SYS_GPC_MFPL_PC6MFP_LLSI1_OUT@GPC_MFPL', 'TM1:SYS_GPC_MFPL_PC6MFP_TM1@GPC_MFPL', 'INT2:SYS_GPC_MFPL_PC6MFP_INT2@GPC_MFPL'] },
    { f: ['PC.7', 'GPIO:SYS_GPC_MFPL_PC7MFP_GPIO@GPC_MFPL', 'UART0_nCTS:SYS_GPC_MFPL_PC7MFP_UART0_nCTS@GPC_MFPL', 'LLSI0_OUT:SYS_GPC_MFPL_PC7MFP_LLSI0_OUT@GPC_MFPL', 'TM0:SYS_GPC_MFPL_PC7MFP_TM0@GPC_MFPL', 'INT3:SYS_GPC_MFPL_PC7MFP_INT3@GPC_MFPL'] },
    { f: ['PC.14', 'GPIO:SYS_GPC_MFPH_PC14MFP_GPIO@GPC_MFPH', 'USCI0_CTL0:SYS_GPC_MFPH_PC14MFP_USCI0_CTL0@GPC_MFPH', 'CANFD0_TXL:SYS_GPC_MFPH_PC14MFP_CANFD0_TXL@GPC_MFPH', 'TM1:SYS_GPC_MFPH_PC14MFP_TM1@GPC_MFPH'] },
    { f: ['PD.0', 'GPIO:SYS_GPD_MFPL_PD0MFP_GPIO@GPD_MFPL', 'SPI0_MOSI:SYS_GPD_MFPL_PD0MFP_SPI0_MOSI@GPD_MFPL', 'USCI0_CLK:SYS_GPD_MFPL_PD0MFP_USCI0_CLK@GPD_MFPL', 'CANFD1_TXL:SYS_GPD_MFPL_PD0MFP_CANFD1_TXL@GPD_MFPL', 'TM2:SYS_GPD_MFPL_PD0MFP_TM2@GPD_MFPL'] },
    { f: ['PD.1', 'GPIO:SYS_GPD_MFPL_PD1MFP_GPIO@GPD_MFPL', 'SPI0_MISO:SYS_GPD_MFPL_PD1MFP_SPI0_MISO@GPD_MFPL', 'USCI0_DAT0:SYS_GPD_MFPL_PD1MFP_USCI0_DAT0@GPD_MFPL'] },
    { f: ['PD.2', 'GPIO:SYS_GPD_MFPL_PD2MFP_GPIO@GPD_MFPL', 'UART0_RXD:SYS_GPD_MFPL_PD2MFP_UART0_RXD@GPD_MFPL', 'SPI0_CLK:SYS_GPD_MFPL_PD2MFP_SPI0_CLK@GPD_MFPL', 'USCI0_DAT1:SYS_GPD_MFPL_PD2MFP_USCI0_DAT1@GPD_MFPL'] },
    { f: ['PD.3', 'GPIO:SYS_GPD_MFPL_PD3MFP_GPIO@GPD_MFPL', 'UART0_TXD:SYS_GPD_MFPL_PD3MFP_UART0_TXD@GPD_MFPL', 'SPI0_SS:SYS_GPD_MFPL_PD3MFP_SPI0_SS@GPD_MFPL', 'USCI0_CTL1:SYS_GPD_MFPL_PD3MFP_USCI0_CTL1@GPD_MFPL'] },
    { f: ['PD.15', 'GPIO:SYS_GPD_MFPH_PD15MFP_GPIO@GPD_MFPH', 'CANFD0_TXL:SYS_GPD_MFPH_PD15MFP_CANFD0_TXL@GPD_MFPH', 'TM3:SYS_GPD_MFPH_PD15MFP_TM3@GPD_MFPH', 'INT1:SYS_GPD_MFPH_PD15MFP_INT1@GPD_MFPH'] },
    { f: ['PF.0', 'GPIO:SYS_GPF_MFPL_PF0MFP_GPIO@GPF_MFPL', 'UART1_TXD:SYS_GPF_MFPL_PF0MFP_UART1_TXD@GPF_MFPL', 'UART0_TXD:SYS_GPF_MFPL_PF0MFP_UART0_TXD@GPF_MFPL', 'CANFD2_TXD:SYS_GPF_MFPL_PF0MFP_CANFD2_TXD@GPF_MFPL', 'CANFD2_TXH:SYS_GPF_MFPL_PF0MFP_CANFD2_TXH@GPF_MFPL', 'ICE_DAT:SYS_GPF_MFPL_PF0MFP_ICE_DAT@GPF_MFPL'] },
    { f: ['PF.1', 'GPIO:SYS_GPF_MFPL_PF1MFP_GPIO@GPF_MFPL', 'UART1_RXD:SYS_GPF_MFPL_PF1MFP_UART1_RXD@GPF_MFPL', 'UART0_RXD:SYS_GPF_MFPL_PF1MFP_UART0_RXD@GPF_MFPL', 'CANFD2_RXD:SYS_GPF_MFPL_PF1MFP_CANFD2_RXD@GPF_MFPL', 'ICE_CLK:SYS_GPF_MFPL_PF1MFP_ICE_CLK@GPF_MFPL'] },
    { f: ['PF.2', 'GPIO:SYS_GPF_MFPL_PF2MFP_GPIO@GPF_MFPL', 'UART0_RXD:SYS_GPF_MFPL_PF2MFP_UART0_RXD@GPF_MFPL', 'XT1_OUT:SYS_GPF_MFPL_PF2MFP_XT1_OUT@GPF_MFPL', 'I2C0_SDA:SYS_GPF_MFPL_PF2MFP_I2C0_SDA@GPF_MFPL', 'CANFD0_RXD:SYS_GPF_MFPL_PF2MFP_CANFD0_RXD@GPF_MFPL'] },
    { f: ['PF.3', 'GPIO:SYS_GPF_MFPL_PF3MFP_GPIO@GPF_MFPL', 'UART0_TXD:SYS_GPF_MFPL_PF3MFP_UART0_TXD@GPF_MFPL', 'XT1_IN:SYS_GPF_MFPL_PF3MFP_XT1_IN@GPF_MFPL', 'I2C0_SCL:SYS_GPF_MFPL_PF3MFP_I2C0_SCL@GPF_MFPL', 'CANFD0_TXD:SYS_GPF_MFPL_PF3MFP_CANFD0_TXD@GPF_MFPL', 'CANFD0_TXH:SYS_GPF_MFPL_PF3MFP_CANFD0_TXH@GPF_MFPL'] },
    { f: ['PF.4', 'GPIO:SYS_GPF_MFPL_PF4MFP_GPIO@GPF_MFPL', 'X32_OUT:SYS_GPF_MFPL_PF4MFP_X32_OUT@GPF_MFPL', 'LLSI1_OUT:SYS_GPF_MFPL_PF4MFP_LLSI1_OUT@GPF_MFPL', 'CANFD0_TXL:SYS_GPF_MFPL_PF4MFP_CANFD0_TXL@GPF_MFPL', 'PWM0_CH1:SYS_GPF_MFPL_PF4MFP_PWM0_CH1@GPF_MFPL', 'BPWM0_CH5:SYS_GPF_MFPL_PF4MFP_BPWM0_CH5@GPF_MFPL'] },
    { f: ['PF.5', 'GPIO:SYS_GPF_MFPL_PF5MFP_GPIO@GPF_MFPL', 'X32_IN:SYS_GPF_MFPL_PF5MFP_X32_IN@GPF_MFPL', 'LLSI0_OUT:SYS_GPF_MFPL_PF5MFP_LLSI0_OUT@GPF_MFPL', 'PWM0_CH0:SYS_GPF_MFPL_PF5MFP_PWM0_CH0@GPF_MFPL', 'BPWM0_CH4:SYS_GPF_MFPL_PF5MFP_BPWM0_CH4@GPF_MFPL', 'ADC0_ST:SYS_GPF_MFPL_PF5MFP_ADC0_ST@GPF_MFPL'] },
    { f: ['PF.6', 'GPIO:SYS_GPF_MFPL_PF6MFP_GPIO@GPF_MFPL', 'SPI0_MOSI:SYS_GPF_MFPL_PF6MFP_SPI0_MOSI@GPF_MFPL', 'CLKO:SYS_GPF_MFPL_PF6MFP_CLKO@GPF_MFPL'] },
    { f: ['PF.14', 'GPIO:SYS_GPF_MFPH_PF14MFP_GPIO@GPF_MFPH', 'TM3:SYS_GPF_MFPH_PF14MFP_TM3@GPF_MFPH', 'CLKO:SYS_GPF_MFPH_PF14MFP_CLKO@GPF_MFPH'] },
    { f: ['PF.15', 'GPIO:SYS_GPF_MFPH_PF15MFP_GPIO@GPF_MFPH', 'CANFD2_TXL:SYS_GPF_MFPH_PF15MFP_CANFD2_TXL@GPF_MFPH', 'CLKO:SYS_GPF_MFPH_PF15MFP_CLKO@GPF_MFPH', 'INT4:SYS_GPF_MFPH_PF15MFP_INT4@GPF_MFPH'] }
];

NUTOOL_PIN.g_cfg_gpiosDescriptions = [
    'ACMP0_N:Analog comparator 0 negative input  pin.',
    'ACMP0_O:Analog comparator 0 output pin.',
    'ACMP0_P0:Analog comparator 0 positive input 0 pin.',
    'ACMP0_P1:Analog comparator 0 positive input 1 pin.',
    'ACMP0_P2:Analog comparator 0 positive input 2 pin.',
    'ACMP0_P3:Analog comparator 0 positive input 3 pin.',
    'ACMP0_WLAT:Analog comparator 0 window latch input pin',
    'ACMP1_N:Analog comparator 1 negative input  pin.',
    'ACMP1_O:Analog comparator 1 output pin.',
    'ACMP1_P0:Analog comparator 1 positive input 0 pin.',
    'ACMP1_P1:Analog comparator 1 positive input 1 pin.',
    'ACMP1_P2:Analog comparator 1 positive input 2 pin.',
    'ACMP1_P3:Analog comparator 1 positive input 3 pin.',
    'ACMP1_WLAT:Analog comparator 1 window latch input pin',
    'BPWM0_CH0:BPWM0 channel 0 output/capture input.',
    'BPWM0_CH1:BPWM0 channel 1 output/capture input.',
    'BPWM0_CH2:BPWM0 channel 2 output/capture input.',
    'BPWM0_CH3:BPWM0 channel 3 output/capture input.',
    'BPWM0_CH4:BPWM0 channel 4 output/capture input.',
    'BPWM0_CH5:BPWM0 channel 5 output/capture input.',
    'CANFD0_RXD:CANF bus receiver input.',
    'CANFD0_TXD:CANF bus transmitter output.',
    'CANFD1_RXD:CANF bus receiver input.',
    'CANFD1_TXD:CANF bus transmitter output.',
    'CANFD2_RXD:CANF bus receiver input.',
    'CANFD2_TXD:CANF bus transmitter output.',
    'CLKO:Clock Out',
    'EADC0_CH0:EADC0 channel 0 analog input.',
    'EADC0_CH1:EADC0 channel 1 analog input.',
    'EADC0_CH2:EADC0 channel 2 analog input.',
    'EADC0_CH3:EADC0 channel 3 analog input.',
    'EADC0_CH4:EADC0 channel 4 analog input.',
    'EADC0_CH5:EADC0 channel 5 analog input.',
    'EADC0_CH12:EADC0 channel 12 analog input.',
    'EADC0_CH13:EADC0 channel 13 analog input.',
    'EADC0_CH14:EADC0 channel 14 analog input.',
    'EADC0_CH15:EADC0 channel 15 analog input.',
    'EADC0_ST:EADC0 external trigger input.',
    'I2C0_SCL:I2C0 clock pin.',
    'I2C0_SDA:I2C0 data input/output pin.',
    'I2C0_SMBAL:I2C0 SMBus SMBALTER pin ',
    'I2C0_SMBSUS:I2C0 SMBus SMBSUS pin (PMBus CONTROL pin)',
    'ICE_CLK:Serial wired debugger clock pin.',
    'ICE_DAT:Serial wired debugger data pin.',
    'INT0:External interrupt 0 input pin.',
    'INT1:External interrupt 1 input pin.',
    'INT2:External interrupt 2 input pin.',
    'INT3:External interrupt 3 input pin.',
    'INT4:External interrupt 4 input pin.',
    'LLSI0_OUT:LED Lighting Strip Interface 0 output pin.',
    'LLSI1_OUT:LED Lighting Strip Interface 1 output pin.',
    'Pin Name:Description',
    'PWM0_BRAKE0:PWM0 Brake 0 input pin.',
    'PWM0_BRAKE1:PWM0 Brake 1 input pin.',
    'PWM0_CH0:PWM0 channel 0 output/capture input.',
    'PWM0_CH1:PWM0 channel 1 output/capture input.',
    'PWM0_CH2:PWM0 channel 2 output/capture input.',
    'PWM0_CH3:PWM0 channel 3 output/capture input.',
    'PWM0_CH4:PWM0 channel 4 output/capture input.',
    'PWM0_CH5:PWM0 channel 5 output/capture input.',
    'SPI0_CLK:SPI0 serial clock pin.',
    'SPI0_MISO:SPI0 MISO (Master In, Slave Out) pin.',
    'SPI0_MOSI:SPI0 MOSI (Master Out, Slave In) pin.',
    'SPI0_SS:SPI0 slave select  pin.',
    'TM0:Timer0 event counter input/toggle output pin.',
    'TM0_EXT:Timer0 external capture input/toggle output pin.',
    'TM1:Timer1 event counter input/toggle output pin.',
    'TM1_EXT:Timer1 external capture input/toggle output pin.',
    'TM2:Timer2 event counter input/toggle output pin.',
    'TM2_EXT:Timer2 external capture input/toggle output pin.',
    'TM3:Timer3 event counter input/toggle output pin.',
    'TM3_EXT:Timer3 external capture input/toggle output pin.',
    'UART0_nCTS:UART0 clear to Send input pin.',
    'UART0_nRTS:UART0 request to Send output pin.',
    'UART0_RXD:UART0 data receiver input pin.',
    'UART0_TXD:UART0 data transmitter output pin.',
    'UART1_nCTS:UART1 clear to Send input pin.',
    'UART1_nRTS:UART1 request to Send output pin.',
    'UART1_RXD:UART1 data receiver input pin.',
    'UART1_TXD:UART1 data transmitter output pin.',
    'USCI0_CLK:USCI0 clock pin.',
    'USCI0_CTL0:USCI0 control 0 pin.',
    'USCI0_CTL1:USCI0 control 1 pin.',
    'USCI0_DAT0:USCI0 data 0 pin.',
    'USCI0_DAT1:USCI0 data 1 pin.',
    'USCI1_CLK:USCI1 clock pin.',
    'USCI1_CTL0:USCI1 control 0 pin.',
    'USCI1_CTL1:USCI1 control 1 pin.',
    'USCI1_DAT0:USCI1 data 0 pin.',
    'USCI1_DAT1:USCI1 data 1 pin.',
    'X32_IN:External 32.768 kHz crystal input pin.',
    'X32_OUT:External 32.768 kHz crystal output pin.',
    'XT1_IN:External 4~24 MHz (high speed) crystal input pin.',
    'XT1_OUT:External 4~24 MHz (high speed) crystal output pin.'
];

NUTOOL_PIN.g_cfg_regDescriptions = {};
NUTOOL_PIN.g_cfg_regDescriptions.GPA_MFPL = '0x40000030';
NUTOOL_PIN.g_cfg_regDescriptions.GPA_MFPH = '0x40000034';
NUTOOL_PIN.g_cfg_regDescriptions.GPB_MFPL = '0x40000038';
NUTOOL_PIN.g_cfg_regDescriptions.GPB_MFPH = '0x4000003C';
NUTOOL_PIN.g_cfg_regDescriptions.GPC_MFPL = '0x40000040';
NUTOOL_PIN.g_cfg_regDescriptions.GPC_MFPH = '0x40000044';
NUTOOL_PIN.g_cfg_regDescriptions.GPD_MFPL = '0x40000048';
NUTOOL_PIN.g_cfg_regDescriptions.GPD_MFPH = '0x4000004C';
NUTOOL_PIN.g_cfg_regDescriptions.GPE_MFPL = '0x40000050';
NUTOOL_PIN.g_cfg_regDescriptions.GPE_MFPH = '0x40000054';
NUTOOL_PIN.g_cfg_regDescriptions.GPF_MFPL = '0x40000058';
NUTOOL_PIN.g_cfg_regDescriptions.GPF_MFPH = '0x4000005C';

NUTOOL_PIN.g_cfg_gpioMatrix = [];
NUTOOL_PIN.g_cfg_shareBits = [];
NUTOOL_PIN.g_cfg_addGPIO = {};
NUTOOL_PIN.g_cfg_unusedGPIO = {
    'M2A23YG5AC': {
        'ALL': []
    },
    'M2A23YE5AC': {
        'ALL': []
    },
    'M2A23LG5AC': {
        'ALL': []
    },
    'M2A23LE5AC': {
        'ALL': []
    },
    'M2A23SG5AC': {
        'ALL': []
    },
    'M2A23SE5AC': {
        'ALL': []
    },
    'M2A23NG5ACU': {
        'ALL': []
    },
    'M2A23NE5ACU': {
        'ALL': []
    },
    'M2A23LG5ACU': {
        'ALL': []
    },
    'M2A23LE5ACU': {
        'ALL': []
    },
    'M2A23SG5ACU': {
        'ALL': []
    },
    'M2A23SE5ACU': {
        'ALL': []
    }
};

NUTOOL_PIN.g_cfg_OrCAD = {
    "QFN48(5*5)(PIN:D10R14U10L14)": [
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', ''
    ],
    "QFN48(7*7)": [
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', ''
    ],
    "LQFP48": [
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', ''
    ],
    "LQFP64": [
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', '', '', '', '', '', '', '', 
        '', '', '', ''
    ]
};

NUTOOL_PIN.decidepackageNumber = function (given_partNumber_package) {
    var partNumber_package;
    var partNumber;

    if (typeof given_partNumber_package === 'undefined') {
        partNumber_package = NUTOOL_PIN.getg_partNumber_package();
    }
    else {
        partNumber_package = given_partNumber_package;
    }

    NUTOOL_PIN.g_packageNumber = partNumber_package.substring(partNumber_package.indexOf('(') + 1);
    NUTOOL_PIN.g_packageNumber = NUTOOL_PIN.g_packageNumber.substring(0, NUTOOL_PIN.g_packageNumber.lastIndexOf(')'));

    partNumber = partNumber_package.substring(0, partNumber_package.indexOf('('));
    switch (partNumber) {
        case 'M2A23YE5AC':
        case 'M2A23YG5AC':
            NUTOOL_PIN.g_packageNumberIndex = "QFN48(5*5)(PIN:D10R14U10L14)";
            break;
        case 'M2A23NE5ACU':
        case 'M2A23NG5ACU':
            NUTOOL_PIN.g_packageNumberIndex = "QFN48(7*7)";
            break;
        default:
            NUTOOL_PIN.g_packageNumberIndex = NUTOOL_PIN.g_packageNumber;
            break;
    }
    partNumber = null;
    partNumber_package = null;
};